In [1]:
import pandas as pd
import json
import os

In [2]:
CSV_PATH = "csv/github_agent_repos_python_20251225.csv"

# Load CSV into a DataFrame
df = pd.read_csv(CSV_PATH)

In [4]:
print(f"Total rows loaded: {len(df)}")
print(df.columns)  # show all column names
df.head(2)

Total rows loaded: 13690
Index(['full_name', 'description', 'stars', 'forks', 'language', 'url',
       'updated_year', 'last_updated', 'created_year', 'created_at',
       'watchers_count', 'size', 'license', 'languages', 'primary_language',
       'topics', 'readme_snippet'],
      dtype='object')

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,watchers_count,size,license,languages,primary_language,topics,readme_snippet
0,khoj-ai/khoj,Your AI second brain. Self-hostable. Get answe...,32004,1904,Python,https://github.com/khoj-ai/khoj,2025,2025-12-08T04:36:04+00:00,2021,2021-08-16T01:48:44+00:00,32004,117290,GNU Affero General Public License v3.0,"{'Python': 1568495, 'TypeScript': 1137924, 'CS...",Python,"['semantic-search', 'emacs', 'obsidian-md', 'c...",Overview Khojis a personal AI app to extend yo...
1,fractalego/wafl,Using LLMs and rules for a local personal agent,16,0,Python,https://github.com/fractalego/wafl,2025,2025-01-17T15:58:54+00:00,2021,2021-12-12T17:49:28+00:00,16,6904,MIT License,"{'Python': 181831, 'HTML': 6498, 'CSS': 2214, ...",Python,"['chatbot', 'local-model', 'personal-agent', '...",WAFL 0.1.0 WAFL is a framework for personal ag...

In [5]:
FEW_SHOT_JSON = "data/few_shot_examples_1.json"


# Initialize empty examples list
examples = []

In [6]:
if os.path.exists(FEW_SHOT_JSON):
    # Check if file is non-empty
    if os.path.getsize(FEW_SHOT_JSON) > 0:
        try:
            with open(FEW_SHOT_JSON, "r") as f:
                examples = json.load(f)
        except json.JSONDecodeError:
            print(f"Warning: {FEW_SHOT_JSON} is not valid JSON. Starting with empty list.")
            examples = []
    else:
        print(f"{FEW_SHOT_JSON} is empty. Starting with empty list.")
else:
    print(f"{FEW_SHOT_JSON} does not exist. Starting with empty list.")

print(f"Loaded {len(examples)} few-shot examples.")

data/few_shot_examples_1.json does not exist. Starting with empty list.
Loaded 0 few-shot examples.

In [7]:
agentic_framework = (df[df["full_name"] == "kaushikb11/awesome-llm-agents"].iloc[0].to_dict())
print(agentic_framework)

{'full_name': 'kaushikb11/awesome-llm-agents', 'description': 'A curated list of awesome LLM agents frameworks.', 'stars': 1231, 'forks': 131, 'language': 'Python', 'url': 'https://github.com/kaushikb11/awesome-llm-agents', 'updated_year': 2025, 'last_updated': '2025-12-21T02:24:03+00:00', 'created_year': 2023, 'created_at': '2023-04-04T10:22:43+00:00', 'watchers_count': 1231, 'size': 76, 'license': nan, 'languages': "{'Python': 4698}", 'primary_language': 'Python', 'topics': "['agents', 'langchain', 'llm']", 'readme_snippet': 'Awesome LLM Agent Frameworks A curated list of awesome LLM frameworks and agent development tools. If you have a\nsuggestion, feel free to open an issue or pull request. (Last updated: 2025-12-21)'}

In [8]:
agentic_framework.setdefault("category", "agentic framework")

'agentic framework'

In [9]:
print(agentic_framework)

{'full_name': 'kaushikb11/awesome-llm-agents', 'description': 'A curated list of awesome LLM agents frameworks.', 'stars': 1231, 'forks': 131, 'language': 'Python', 'url': 'https://github.com/kaushikb11/awesome-llm-agents', 'updated_year': 2025, 'last_updated': '2025-12-21T02:24:03+00:00', 'created_year': 2023, 'created_at': '2023-04-04T10:22:43+00:00', 'watchers_count': 1231, 'size': 76, 'license': nan, 'languages': "{'Python': 4698}", 'primary_language': 'Python', 'topics': "['agents', 'langchain', 'llm']", 'readme_snippet': 'Awesome LLM Agent Frameworks A curated list of awesome LLM frameworks and agent development tools. If you have a\nsuggestion, feel free to open an issue or pull request. (Last updated: 2025-12-21)', 'category': 'agentic framework'}

In [10]:
examples.append(agentic_framework)

In [11]:
agentic_benchmark = (df[df["full_name"] == "THUDM/AgentBench"].iloc[0].to_dict())
print(agentic_benchmark)

{'full_name': 'THUDM/AgentBench', 'description': "A Comprehensive Benchmark to Evaluate LLMs as Agents (ICLR'24)", 'stars': 3022, 'forks': 221, 'language': 'Python', 'url': 'https://github.com/THUDM/AgentBench', 'updated_year': 2025, 'last_updated': '2025-11-17T07:28:33+00:00', 'created_year': 2023, 'created_at': '2023-07-28T04:32:06+00:00', 'watchers_count': 3022, 'size': 30392, 'license': 'Apache License 2.0', 'languages': "{'Python': 263997, 'Shell': 18426, 'PDDL': 17067, 'Dockerfile': 7312}", 'primary_language': 'Python', 'topics': "['chatgpt', 'gpt-4', 'llm', 'llm-agent']", 'readme_snippet': 'AgentBench 👋 Join ourSlackforQ & Aorcollaborationon next version of AgentBench!'}

In [12]:
agentic_benchmark.setdefault("category", "agentic benchmark")

'agentic benchmark'

In [13]:
examples.append(agentic_benchmark)

In [14]:
print(examples)

[{'full_name': 'kaushikb11/awesome-llm-agents', 'description': 'A curated list of awesome LLM agents frameworks.', 'stars': 1231, 'forks': 131, 'language': 'Python', 'url': 'https://github.com/kaushikb11/awesome-llm-agents', 'updated_year': 2025, 'last_updated': '2025-12-21T02:24:03+00:00', 'created_year': 2023, 'created_at': '2023-04-04T10:22:43+00:00', 'watchers_count': 1231, 'size': 76, 'license': nan, 'languages': "{'Python': 4698}", 'primary_language': 'Python', 'topics': "['agents', 'langchain', 'llm']", 'readme_snippet': 'Awesome LLM Agent Frameworks A curated list of awesome LLM frameworks and agent development tools. If you have a\nsuggestion, feel free to open an issue or pull request. (Last updated: 2025-12-21)', 'category': 'agentic framework'}, {'full_name': 'THUDM/AgentBench', 'description': "A Comprehensive Benchmark to Evaluate LLMs as Agents (ICLR'24)", 'stars': 3022, 'forks': 221, 'language': 'Python', 'url': 'https://github.com/THUDM/AgentBench', 'updated_year': 2025, 'last_updated': '2025-11-17T07:28:33+00:00', 'created_year': 2023, 'created_at': '2023-07-28T04:32:06+00:00', 'watchers_count': 3022, 'size': 30392, 'license': 'Apache License 2.0', 'languages': "{'Python': 263997, 'Shell': 18426, 'PDDL': 17067, 'Dockerfile': 7312}", 'primary_language': 'Python', 'topics': "['chatgpt', 'gpt-4', 'llm', 'llm-agent']", 'readme_snippet': 'AgentBench 👋 Join ourSlackforQ & Aorcollaborationon next version of AgentBench!', 'category': 'agentic benchmark'}]

In [15]:
foundation_model = (df[df["full_name"] == "zai-org/GLM-4.5"].iloc[0].to_dict())
print(foundation_model)

{'full_name': 'zai-org/GLM-4.5', 'description': 'GLM-4.5: Agentic, Reasoning, and Coding (ARC) Foundation Models', 'stars': 3491, 'forks': 366, 'language': 'Python', 'url': 'https://github.com/zai-org/GLM-4.5', 'updated_year': 2025, 'last_updated': '2025-12-23T06:11:48+00:00', 'created_year': 2025, 'created_at': '2025-07-20T09:24:09+00:00', 'watchers_count': 3491, 'size': 7703, 'license': 'Apache License 2.0', 'languages': "{'Python': 3759}", 'primary_language': 'Python', 'topics': "['agent', 'llm', 'moe', 'reasoning-language-models', 'glm']", 'readme_snippet': 'GLM-4.7 & GLM-4.6 & GLM-4.5 👋 Join ourWeChatorDiscordcommunity.📖 Check out the GLM-4.7technical blog,technical report(GLM-4.5), andZhipu AI technical documentation.📍 Use GLM-4.7 API services onZ.ai API Platform.👉 One click toGLM-4.7.'}

In [16]:
foundation_model.setdefault("category", "foundation model")

'foundation model'

In [17]:
examples.append(foundation_model)

In [18]:
documents_about_llm_agents = (df[df["full_name"] == "oxbshw/LLM-Agents-Ecosystem-Handbook"].iloc[0].to_dict())
print(documents_about_llm_agents)

{'full_name': 'oxbshw/LLM-Agents-Ecosystem-Handbook', 'description': 'One-stop handbook for building, deploying, and understanding LLM agents with 60+ skeletons, tutorials, ecosystem guides, and evaluation tools.', 'stars': 355, 'forks': 48, 'language': 'Python', 'url': 'https://github.com/oxbshw/LLM-Agents-Ecosystem-Handbook', 'updated_year': 2025, 'last_updated': '2025-09-08T01:59:44+00:00', 'created_year': 2025, 'created_at': '2025-09-08T01:24:26+00:00', 'watchers_count': 355, 'size': 1803, 'license': 'MIT License', 'languages': "{'Python': 95865, 'Jupyter Notebook': 1109}", 'primary_language': 'Python', 'topics': "['ai', 'ai-agent', 'ai-agents', 'fine-tuning', 'finetuning-llms', 'freamework', 'llm', 'llmops', 'local-development', 'mcp-server', 'memory', 'rag', 'rag-chatbot', 'voice-agent']", 'readme_snippet': 'LLM Agents & Ecosystem Handbook A polished, curated collection ofLarge Language Model (LLM) agents, tutorials and ecosystem insights. This handbook highlights projects that push the boundaries of generative AI, multi-agent collaboration, retrieval-augmented generation (RAG), voice and game agents, and more. It goes beyond simple link aggregation, aiming to be a one-stop reference for building, deploying, and understanding LLM applications across the entire stack.'}

In [19]:
documents_about_llm_agents.setdefault("category", "documents about llm agents")
examples.append(documents_about_llm_agents)

In [20]:
collection_of_llm_agent_projects = (df[df["full_name"] == "Shubhamsaboo/awesome-llm-apps"].iloc[0].to_dict())
print(collection_of_llm_agent_projects)

{'full_name': 'Shubhamsaboo/awesome-llm-apps', 'description': 'Collection of awesome LLM apps with AI Agents and RAG using OpenAI, Anthropic, Gemini and opensource models.', 'stars': 84036, 'forks': 11933, 'language': 'Python', 'url': 'https://github.com/Shubhamsaboo/awesome-llm-apps', 'updated_year': 2025, 'last_updated': '2025-12-19T05:51:14+00:00', 'created_year': 2024, 'created_at': '2024-04-29T05:30:25+00:00', 'watchers_count': 84036, 'size': 193633, 'license': 'Apache License 2.0', 'languages': "{'Python': 2241945, 'JavaScript': 835003, 'TypeScript': 204202, 'HTML': 32350, 'CSS': 8864, 'PLpgSQL': 3012, 'Dockerfile': 1506, 'Shell': 621}", 'primary_language': 'Python', 'topics': "['llms', 'rag', 'python']", 'readme_snippet': '🌟 Awesome LLM Apps A curated collection ofAwesome LLM apps built with RAG, AI Agents, Multi-agent Teams, MCP, Voice Agents, and more.This repository features LLM apps that use models fromOpenAI,Anthropic,Google,xAIand open-source models likeQwenorLlamathat you can run locally on your computer.'}

In [21]:
collection_of_llm_agent_projects.setdefault("category", "collection of llm agent projects")
examples.append(collection_of_llm_agent_projects)

In [22]:
collection_of_datasets = (df[df["full_name"] == "fangyuan-ksgk/RuleAlign"].iloc[0].to_dict())
print(collection_of_datasets)

{'full_name': 'fangyuan-ksgk/RuleAlign', 'description': 'Rule-Based Adherance evaluation for LLM Agent', 'stars': 3, 'forks': 0, 'language': 'Python', 'url': 'https://github.com/fangyuan-ksgk/RuleAlign', 'updated_year': 2024, 'last_updated': '2024-09-02T02:31:10+00:00', 'created_year': 2024, 'created_at': '2024-08-18T09:35:56+00:00', 'watchers_count': 3, 'size': 133, 'license': nan, 'languages': "{'Python': 23146, 'Jupyter Notebook': 3432, 'Shell': 350}", 'primary_language': 'Python', 'topics': '[]', 'readme_snippet': 'RuleAlign Dataset RuleAlign is a dataset designed to evaluate rule-based alignment of language models. It accompanies the paper "Iterative Graph Reasoning" and contains:'}

In [23]:
collection_of_datasets.setdefault("category", "collection of datasets")
examples.append(collection_of_datasets)

In [24]:
LLM_based_agentic_system = (df[df["full_name"] == "sathvik-23/hope"].iloc[0].to_dict())
print(LLM_based_agentic_system)

{'full_name': 'sathvik-23/hope', 'description': "Voice Agent Project :  This project implements a voice agent that can:  1. Convert speech to text using Whisper 2. Generate responses using Google's Gemini LLM 3. Convert text responses to speech using gTTS 4. Store all interactions in MongoDB", 'stars': 0, 'forks': 0, 'language': 'Python', 'url': 'https://github.com/sathvik-23/hope', 'updated_year': 2025, 'last_updated': '2025-05-14T20:41:01+00:00', 'created_year': 2025, 'created_at': '2025-05-14T14:28:25+00:00', 'watchers_count': 0, 'size': 513, 'license': nan, 'languages': "{'Python': 5141}", 'primary_language': 'Python', 'topics': '[]', 'readme_snippet': 'Voice Agent Project hope/\n├── venv/                      # Main project virtual environment\n├── requirements.txt           # Main project dependencies\n├── .env                      # Environment variables (not committed)\n├── Piper-tts/\n│   ├── venv/                  # Piper-tts virtual environment\n│   └── requirements.txt       # Piper-tts dependencies\n├── whisper/\n│   ├── venv/                  # Whisper virtual environment\n│   └── requirements.txt       # Whisper dependencies\n├── audio/\n│   ├── input/                 # Input audio files\n│   └── output/                # Generated audio responses\n├── voice_agent.py             # Main implementation\n├── test_voice_agent.py        # Test script\n└── README.md                  # This file'}

In [25]:
LLM_based_agentic_system.setdefault("category", "llm-based agentic system")
examples.append(LLM_based_agentic_system)

In [26]:
len(examples)

7

In [27]:
df_examples = pd.DataFrame(examples)

print("Total examples:", len(df_examples))
df_examples[["full_name", "category", "readme_snippet"]]

Total examples: 7

,full_name,category,readme_snippet
0,kaushikb11/awesome-llm-agents,agentic framework,Awesome LLM Agent Frameworks A curated list of...
1,THUDM/AgentBench,agentic benchmark,AgentBench 👋 Join ourSlackforQ & Aorcollaborat...
2,zai-org/GLM-4.5,foundation model,GLM-4.7 & GLM-4.6 & GLM-4.5 👋 Join ourWeChator...
3,oxbshw/LLM-Agents-Ecosystem-Handbook,documents about llm agents,"LLM Agents & Ecosystem Handbook A polished, cu..."
4,Shubhamsaboo/awesome-llm-apps,collection of llm agent projects,🌟 Awesome LLM Apps A curated collection ofAwes...
5,fangyuan-ksgk/RuleAlign,collection of datasets,RuleAlign Dataset RuleAlign is a dataset desig...
6,sathvik-23/hope,llm-based agentic system,Voice Agent Project hope/\n├── venv/ ...

In [28]:
with open(FEW_SHOT_JSON, "w") as f:
    json.dump(examples, f, indent=4)