In [17]:
import pandas as pd
import json
import os

In [6]:
CSV_PATH = "csv/github_agent_repos_python_final.csv"

# Load CSV into a DataFrame
df = pd.read_csv(CSV_PATH)

In [7]:
print(f"Total rows loaded: {len(df)}")
print(df.columns)  # show all column names
df.head(1)

Total rows loaded: 13847
Index(['full_name', 'description', 'stars', 'forks', 'language', 'url',
       'updated_year', 'last_updated', 'created_year', 'created_at',
       'watchers_count', 'size', 'license', 'languages', 'primary_language',
       'topics', 'readme_content'],
      dtype='object')

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,watchers_count,size,license,languages,primary_language,topics,readme_content
0,khoj-ai/khoj,Your AI second brain. Self-hostable. Get answe...,32136,1920,Python,https://github.com/khoj-ai/khoj,2026,2026-01-06T20:15:01+00:00,2021,2021-08-16T01:48:44+00:00,32136,117773,GNU Affero General Public License v3.0,"{'Python': 1636286, 'TypeScript': 1160260, 'CS...",Python,"['semantic-search', 'emacs', 'obsidian-md', 'c...","<p align=""center""><img src=""https://assets.kho..."

In [15]:
FEW_SHOT_JSON = "data/few_shot_examples.json"


# Initialize empty examples list
examples = []

In [18]:
if os.path.exists(FEW_SHOT_JSON):
    # Check if file is non-empty
    if os.path.getsize(FEW_SHOT_JSON) > 0:
        try:
            with open(FEW_SHOT_JSON, "r") as f:
                examples = json.load(f)
        except json.JSONDecodeError:
            print(f"Warning: {FEW_SHOT_JSON} is not valid JSON. Starting with empty list.")
            examples = []
    else:
        print(f"{FEW_SHOT_JSON} is empty. Starting with empty list.")
else:
    print(f"{FEW_SHOT_JSON} does not exist. Starting with empty list.")

print(f"Loaded {len(examples)} few-shot examples.")

data/few_shot_examples.json is empty. Starting with empty list.
Loaded 0 few-shot examples.

In [19]:
agentic_framework = (df[df["full_name"] == "kaushikb11/awesome-llm-agents"].iloc[0].to_dict())
print(agentic_framework)

{'full_name': 'kaushikb11/awesome-llm-agents', 'description': 'A curated list of awesome LLM agents frameworks.', 'stars': 1263, 'forks': 134, 'language': 'Python', 'url': 'https://github.com/kaushikb11/awesome-llm-agents', 'updated_year': 2026, 'last_updated': '2026-01-04T02:32:04+00:00', 'created_year': 2023, 'created_at': '2023-04-04T10:22:43+00:00', 'watchers_count': 1263, 'size': 39, 'license': nan, 'languages': "{'Python': 4698}", 'primary_language': 'Python', 'topics': "['agents', 'langchain', 'llm']", 'readme_content': '# Awesome LLM Agent Frameworks [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)\n\nA curated list of awesome LLM frameworks and agent development tools. If you have a\nsuggestion, feel free to open an issue or pull request. (Last updated: 2026-01-04)\n\n## Frameworks\n\n- [CrewAI](https://github.com/joaomdmoura/crewAI) - Framework for orchestrating\n  role-playing AI agents\n\n  42,166 stars · 5,646 forks · 269 contributors · 187 issues · Python · MIT\n\n  - Role-based agent design\n  - Multi-agent collaboration\n  - Flexible memory system\n  - Built-in error handling\n\n\n- [Langchain](https://github.com/hwchase17/langchain) - Building applications with LLMs\n  through composability\n\n  123,299 stars · 20,329 forks · 470 contributors · 354 issues · Python · MIT\n\n  - Modular and extensible architecture\n  - Unified interface for LLMs\n  - Pre-built agent toolkits\n  - CSV, JSON, and SQL agents\n  - Python and Pandas integration\n  - Vector store capabilities\n\n\n- [Microsoft AutoGen](https://github.com/microsoft/autogen) - Framework for building\n  multi-agent conversational systems\n\n  53,102 stars · 8,065 forks · 446 contributors · 536 issues · Python · CC-BY-4.0\n\n  - Multi-agent architecture\n  - Customizable agents\n  - Code execution support\n  - Flexible human involvement\n  - Advanced conversation management\n\n\n- [OpenManus](https://github.com/FoundationAgents/OpenManus) - Open-source AI agent\n  platform for building general-purpose agents\n\n  52,009 stars · 9,129 forks · 53 contributors · 522 issues · Python · MIT\n\n  - Modular architecture for customization\n  - Data analysis and visualization agents\n  - Reinforcement learning integration (OpenManus-RL)\n  - No invitation code required\n  - Built by MetaGPT contributors\n\n\n- [Llama Index](https://github.com/run-llama/llama_index) - Data framework for LLM\n  applications\n\n  46,128 stars · 6,678 forks · 474 contributors · 277 issues · Python · MIT\n\n  - Advanced indexing and retrieval\n  - Support for 160+ data sources\n  - Customizable RAG workflows\n  - Structured data handling\n  - Query optimization\n\n\n- [Microsoft Semantic Kernel](https://github.com/microsoft/semantic-kernel) -\n  Integration framework for AI models\n\n  26,959 stars · 4,408 forks · 389 contributors · 540 issues · C# · MIT\n\n  - Enterprise-grade security\n  - Multi-language support\n  - Plugin architecture\n  - Responsible AI features\n  - Memory management\n\n\n- [Dify](https://github.com/langgenius/dify) - Open-source framework for LLM\n  applications\n\n  124,493 stars · 19,359 forks · 464 contributors · 660 issues · Python · NOASSERTION\n\n  - Visual prompt orchestration\n  - Long context integration\n  - API-based development\n  - Multi-model support\n  - RAG pipeline\n\n\n- [Haystack](https://github.com/deepset-ai/haystack) - End-to-end NLP framework\n\n  23,780 stars · 2,542 forks · 307 contributors · 112 issues · MDX · Apache-2.0\n\n  - Document processing\n  - Neural search\n  - Question answering\n  - Semantic search\n  - Agent capabilities\n\n\n- [Embedchain](https://github.com/embedchain/embedchain) - Framework for ChatGPT-like\n  bots\n\n  44,944 stars · 4,903 forks · 245 contributors · 586 issues · Python · Apache-2.0\n\n  - Multi-source data ingestion\n  - Automated embedding\n  - Context window management\n  - Multiple LLM support\n  - RAG optimization\n\n\n- [Google ADK](https://github.com/google/adk-python) - Agent Development Kit for\n  building, evaluating, and deploying AI agents\n\n  16,907 stars · 2,718 forks · 213 contributors · 532 issues · Python · Apache-2.0\n\n  - Code-first development approach\n  - Modular multi-agent systems\n  - Model-agnostic and deployment-agnostic\n  - Built-in developer UI (adk-web)\n  - Deploy on Cloud Run or Vertex AI\n\n\n- [SuperAGI](https://github.com/TransformerOptimus/SuperAGI) - Open-source autonomous AI\n  agent framework\n\n  17,019 stars · 2,144 forks · 63 contributors · 202 issues · Python · MIT\n\n  - Customizable agent workflows\n  - Tool creation framework\n  - Performance monitoring\n  - Resource management\n  - Multi-vector memory storage\n\n\n- [Kiln AI](https://github.com/Kiln-AI/Kiln) - Tools for building AI products including\n  agents, evals, RAG systems, and fine-tuning\n\n  4,516 stars · 334 forks · 12 contributors · 34 issues · Python · NOASSERTION\n\n  - Free desktop application for no-code development\n  - Evaluation frameworks\n  - RAG system building\n  - Synthetic data generation\n  - Agent development tools\n\n\n- [AGiXT](https://github.com/Josh-XT/AGiXT) - Scalable framework for AI agents\n\n  3,139 stars · 443 forks · 41 contributors · 1 issues · Python · MIT\n\n  - Multi-provider support\n  - Chain of thought processing\n  - Extensible plugin system\n  - Command chaining\n  - Web UI included\n\n\n- [XAgent](https://github.com/OpenBMB/XAgent) - Autonomous LLM-based agent framework\n\n  8,484 stars · 891 forks · 33 contributors · 55 issues · Python · Apache-2.0\n\n  - Human-like planning\n  - Autonomous task decomposition\n  - Tool learning capabilities\n  - Advanced error recovery\n  - Built-in action validation\n\n\n- [Neurolink](https://github.com/juspay/neurolink) - Multi-provider AI agent framework\n  with workflow orchestration capabilities, unifying 12+ providers (OpenAI, Google,\n  Anthropic, AWS, Azure, Groq, Together AI, Mistral, Cohere, Fireworks, Cloudflare,\n  Ollama)\n\n  102 stars · 88 forks · 50 contributors · 402 issues · TypeScript · MIT\n\n  - Multi-agent framework with workflow orchestration\n  - Unified interface for 12+ AI providers\n  - Edge-first architecture with local/cloud deployment\n  - Production-grade streaming and tool calling\n  - Battle-tested at Juspay (15M+ requests/month)\n\n\n- [OpenAgents](https://github.com/xlang-ai/OpenAgents) - Open platform for language\n  agents\n\n  4,656 stars · 512 forks · 16 contributors · 12 issues · Python · Apache-2.0\n\n  - Data analysis capabilities\n  - Web browsing integration\n  - Coding assistance\n  - Plugin ecosystem\n  - Interactive visualization\n\n\n- [AI Legion](https://github.com/eumemic/ai-legion) - Swarm framework for autonomous\n  agents\n\n  1,431 stars · 174 forks · 6 contributors · 8 issues · TypeScript · MIT\n\n  - Multi-agent coordination\n  - Dynamic task allocation\n  - Emergent behavior support\n  - Flexible agent roles\n  - Real-time collaboration\n\n\n- [Agent Protocol](https://github.com/e2b-dev/agent-protocol) - Unified interface for AI\n  agents\n\n  1,432 stars · 171 forks · 14 contributors · 42 issues · Python · MIT\n\n  - Standardized communication\n  - Language-agnostic design\n  - Tool integration specs\n  - Interoperability focus\n  - Protocol versioning\n\n\n- [Agents.js](https://github.com/Webgburnet/Agents.js) - JavaScript framework for\n  building AI agents\n\n  - Browser-native implementation\n  - Event-driven architecture\n  - Tool abstraction layer\n  - Memory management\n  - Real-time processing- [Cache-to-Cache](https://github.com/thu-nics/C2C) - Novel paradigm for direct \n  semantic communication between LLMs via KV-Cache\n\n  87 stars · 6 forks · 2 contributors · 2 issues · Python · Apache-2.0\n\n  - Direct semantic communication via KV-Cache\n  - Multi-agent system integration\n  - Neural cache projection and fusion- [CAMEL](https://github.com/camel-ai/camel) - Communicative Agents for "Mind"\n  Exploration\n\n  14,875 stars · 1,638 forks · 171 contributors · 599 issues · Python · Apache-2.0\n\n  - Role-playing framework\n  - Task-oriented dialogue\n  - Multi-agent conversations\n  - Behavioral analysis\n  - Cognitive architecture- [BabyAGI](https://github.com/yoheinakajima/babyagi) - Lightweight framework for AI\n  task management\n\n  - Task prioritization\n  - Autonomous execution\n  - Memory persistence\n  - Goal-oriented planning\n  - Resource optimization- [Autonomous-GPT](https://github.com/Significant-Gravitas/Auto-GPT) - Framework for\n  autonomous GPT-4 agents\n\n  179,412 stars · 46,089 forks · 433 contributors · 273 issues · Python · NOASSERTION\n\n  - Internet access capabilities\n  - Long-term memory\n  - Goal-oriented behavior\n  - File operations\n  - Command execution- [MetaGPT](https://github.com/geekan/MetaGPT) - Multi-agent framework for software\n  development\n\n  59,615 stars · 7,299 forks · 115 contributors · 57 issues · Python · MIT\n\n  - Role-based development\n  - Code generation\n  - Project management\n  - Documentation writing\n  - Testing automation- [GenoMAS](https://github.com/Liu-Hy/GenoMAS) - Multi-agent framework for scientific\n  discovery and automated data analysis\n\n  123 stars · 19 forks · 1 contributors · 0 issues · Python · MIT\n\n  - Guided planning framework\n  - Typed message-passing protocol\n  - Heterogeneous LLM architecture\n  - Domain-agnostic design\n  - Scientific workflow automation- [minions](https://github.com/getminions/minions) - Extensible framework for AI\n  assistants\n\n  - Custom behavior definition\n  - Tool integration\n  - State management\n  - Event handling\n  - Parallel execution- [ix](https://github.com/kreneskyp/ix) - Autonomous agent framework\n\n  1,037 stars · 129 forks · 5 contributors · 14 issues · Python · MIT\n\n  - Visual workflow builder\n  - Sandbox environments\n  - Tool integration\n  - Process monitoring\n  - Agent collaboration- [saplings](https://github.com/shobrook/saplings) - Build smarter agents using tree\n  search\n\n  269 stars · 17 forks · 4 contributors · 0 issues · Python · Apache-2.0\n\n  - Boost reasoning abilities\n  - Supports popular search algorithms\n  - Minimal setup, 2 lines of code- [Smolagents](https://github.com/huggingface/smolagents) - Minimalist framework for\n  building powerful agents\n\n  24,406 stars · 2,180 forks · 189 contributors · 327 issues · Python · Apache-2.0\n\n  - Code-first approach\n  - Multi-agent orchestration\n  - LLM provider flexibility\n  - Tool integration\n  - Hub integration for sharing- [Flowise](https://github.com/FlowiseAI/Flowise) - Drag & drop UI framework for\n  building LLM flows\n\n  47,784 stars · 23,485 forks · 268 contributors · 747 issues · TypeScript · NOASSERTION\n\n  - Visual flow builder\n  - Custom LLM integrations\n  - API generation\n  - Authentication support\n  - Docker deployment\n\n\n- [Pydantic AI](https://github.com/pydantic/pydantic-ai) - Production-grade agent\n  framework built on Pydantic\n\n  14,116 stars · 1,513 forks · 332 contributors · 422 issues · Python · MIT\n\n  - Type-safe development\n  - Multi-model support\n  - Structured responses\n  - Dependency injection\n  - Logfire integration\n\n\n- [Upsonic](https://github.com/upsonic/upsonic) - Reliable agent framework that\n  support MCP.\n\n  7,737 stars · 712 forks · 33 contributors · 78 issues · Python · MIT\n\n  - Easy-to-activate reliability layers\n  - Model Context Protocol (MCP)\n  - Integrated Browser Use and Computer Use\n  - Isolated environment to run agents\n  - Task-Centric Design\n\n\n- [EvoAgentX](https://github.com/EvoAgentX/EvoAgentX) - Building a Self-Evolving\n  Ecosystem of AI Agents\n\n  2,431 stars · 193 forks · 24 contributors · 12 issues · Python · NOASSERTION\n\n  - Easy Agent and Workflow Customization\n  - Workflow Optimization & Self-Evolving\n  - Agent/workflow evolution algorithms integrated\n  - Execution Toolkit\n\n\n- [Portia AI](https://github.com/portiaAI/portia-sdk-python) - Open source framework for predictable,\n  controllable and authenticated agents.\n\n  1,141 stars · 101 forks · 26 contributors · 44 issues · Python · NOASSERTION\n\n  - Structured planning\n  - Stateful execution\n  - Human in the loop controls\n  - Tool catalogue with built-in auth\n  - MCP support- [Agentic Radar](https://github.com/splx-ai/agentic-radar) - A security scanner for\n  agentic workflows\n\n  848 stars · 106 forks · 8 contributors · 10 issues · Python · Apache-2.0\n\n  - Scans agentic workflow source code\n  - Finds vulnerabilities (CVE & OWASP)\n  - Generates interactive reports\n  - Suggests remediation steps\n  - Supports popular agentic workflows\n- [AgentFlow](https://github.com/lupantech/AgentFlow) - Trainable multi-agent framework\n  with in-the-flow optimization\n\n  1,465 stars · 188 forks · 4 contributors · 7 issues · Python · MIT\n\n  - Four specialized modules (planner, executor, verifier, generator)\n  - Flow-GRPO reinforcement learning\n  - Tool integration (math, coding, scientific, search)\n  - Stanford research project\n  - Performance gains over monolithic approaches\n\n\n- [Mastra](https://github.com/mastra-ai/mastra) - TypeScript AI agent framework with\n  assistants, RAG, and observability\n\n  19,103 stars · 1,379 forks · 279 contributors · 300 issues · TypeScript · NOASSERTION\n\n  - Type-safe development\n  - Multi-model support (GPT-4, Claude, Gemini, Llama)\n  - Structured responses\n  - API generation\n  - Tool integration\n\n\n- [Flappy](https://github.com/pleisto/flappy) - Production-ready LLM agent SDK\n\n  307 stars · 23 forks · 7 contributors · 10 issues · Rust · Apache-2.0\n\n  - Production-grade reliability\n  - Type-safe agent development\n  - Multi-language support\n  - Performance optimized\n  - Developer-friendly SDK\n\n\n- [CleverBee](https://github.com/SureScaleAI/cleverbee) - Deep research assistant agent\n  with web browsing capabilities\n\n  309 stars · 16 forks · 1 contributors · 1 issues · Python · AGPL-3.0\n\n  - Interactive web UI via Chainlit\n  - MCP tool support for external integrations\n  - Multi-LLM research (configurable LLMs)\n  - Automated web browsing with Playwright\n  - Token tracking and cost estimation\n\n\n- [RAI](https://github.com/RobotecAI/rai) - Agentic framework for robotics using ROS 2\n\n  428 stars · 54 forks · 22 contributors · 59 issues · Python · Apache-2.0\n\n  - ROS 2 integration\n  - Complex action execution\n  - Scenario-based testing\n  - Voice interaction support\n  - Vendor-agnostic architecture\n\n\n- [Floom](https://github.com/FloomAI/Floom) - AI gateway and agent/pipeline marketplace\n\n  46 stars · 4 forks · 2 contributors · 0 issues · C# · MIT\n\n  - AI pipeline orchestration\n  - Agent marketplace integration\n  - Kubernetes-style architecture\n  - Streamlined AI integration\n  - DevOps-friendly deployment\n\n\n- [CoreAgent](https://github.com/CoreAgent-Project/CoreAgent) - Minimalist agent framework\n  with stateful tools\n\n  25 stars · 3 forks · 2 issues · Python\n\n  - Simplicity-first design\n  - Stateful tool support\n  - Multi-agent coordination\n  - Shared state management\n  - Built-in tools library- [Project Alice](https://github.com/MarianoMolina/project_alice) - Framework and\n  platform for building and deploying agentic workflows\n\n  253 stars · 34 forks · 1 contributors · 1 issues · Python · BSD-3-Clause\n\n  - No-code and coding interface\n  - Visual workflow builder\n  - Live demo available\n  - Workflow deployment platform\n  - Alpha stage development- [AgentSquare](https://github.com/tsinghua-fib-lab/AgentSquare) - Automatic LLM agent\n  search in modular design space\n\n  199 stars · 14 forks · 10 issues · HTML\n\n  - Module evolution and recombination\n  - Planning, Reasoning, Tool Use, Memory modules\n  - Adaptive agent search framework\n  - Unified framework for six agent tasks\n  - Tsinghua University research project\n'}

In [20]:
agentic_framework.setdefault("category", "agentic framework")

'agentic framework'

In [21]:
print(agentic_framework)

{'full_name': 'kaushikb11/awesome-llm-agents', 'description': 'A curated list of awesome LLM agents frameworks.', 'stars': 1263, 'forks': 134, 'language': 'Python', 'url': 'https://github.com/kaushikb11/awesome-llm-agents', 'updated_year': 2026, 'last_updated': '2026-01-04T02:32:04+00:00', 'created_year': 2023, 'created_at': '2023-04-04T10:22:43+00:00', 'watchers_count': 1263, 'size': 39, 'license': nan, 'languages': "{'Python': 4698}", 'primary_language': 'Python', 'topics': "['agents', 'langchain', 'llm']", 'readme_content': '# Awesome LLM Agent Frameworks [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)\n\nA curated list of awesome LLM frameworks and agent development tools. If you have a\nsuggestion, feel free to open an issue or pull request. (Last updated: 2026-01-04)\n\n## Frameworks\n\n- [CrewAI](https://github.com/joaomdmoura/crewAI) - Framework for orchestrating\n  role-playing AI agents\n\n  42,166 stars · 5,646 forks · 269 contributors · 187 issues · Python · MIT\n\n  - Role-based agent design\n  - Multi-agent collaboration\n  - Flexible memory system\n  - Built-in error handling\n\n\n- [Langchain](https://github.com/hwchase17/langchain) - Building applications with LLMs\n  through composability\n\n  123,299 stars · 20,329 forks · 470 contributors · 354 issues · Python · MIT\n\n  - Modular and extensible architecture\n  - Unified interface for LLMs\n  - Pre-built agent toolkits\n  - CSV, JSON, and SQL agents\n  - Python and Pandas integration\n  - Vector store capabilities\n\n\n- [Microsoft AutoGen](https://github.com/microsoft/autogen) - Framework for building\n  multi-agent conversational systems\n\n  53,102 stars · 8,065 forks · 446 contributors · 536 issues · Python · CC-BY-4.0\n\n  - Multi-agent architecture\n  - Customizable agents\n  - Code execution support\n  - Flexible human involvement\n  - Advanced conversation management\n\n\n- [OpenManus](https://github.com/FoundationAgents/OpenManus) - Open-source AI agent\n  platform for building general-purpose agents\n\n  52,009 stars · 9,129 forks · 53 contributors · 522 issues · Python · MIT\n\n  - Modular architecture for customization\n  - Data analysis and visualization agents\n  - Reinforcement learning integration (OpenManus-RL)\n  - No invitation code required\n  - Built by MetaGPT contributors\n\n\n- [Llama Index](https://github.com/run-llama/llama_index) - Data framework for LLM\n  applications\n\n  46,128 stars · 6,678 forks · 474 contributors · 277 issues · Python · MIT\n\n  - Advanced indexing and retrieval\n  - Support for 160+ data sources\n  - Customizable RAG workflows\n  - Structured data handling\n  - Query optimization\n\n\n- [Microsoft Semantic Kernel](https://github.com/microsoft/semantic-kernel) -\n  Integration framework for AI models\n\n  26,959 stars · 4,408 forks · 389 contributors · 540 issues · C# · MIT\n\n  - Enterprise-grade security\n  - Multi-language support\n  - Plugin architecture\n  - Responsible AI features\n  - Memory management\n\n\n- [Dify](https://github.com/langgenius/dify) - Open-source framework for LLM\n  applications\n\n  124,493 stars · 19,359 forks · 464 contributors · 660 issues · Python · NOASSERTION\n\n  - Visual prompt orchestration\n  - Long context integration\n  - API-based development\n  - Multi-model support\n  - RAG pipeline\n\n\n- [Haystack](https://github.com/deepset-ai/haystack) - End-to-end NLP framework\n\n  23,780 stars · 2,542 forks · 307 contributors · 112 issues · MDX · Apache-2.0\n\n  - Document processing\n  - Neural search\n  - Question answering\n  - Semantic search\n  - Agent capabilities\n\n\n- [Embedchain](https://github.com/embedchain/embedchain) - Framework for ChatGPT-like\n  bots\n\n  44,944 stars · 4,903 forks · 245 contributors · 586 issues · Python · Apache-2.0\n\n  - Multi-source data ingestion\n  - Automated embedding\n  - Context window management\n  - Multiple LLM support\n  - RAG optimization\n\n\n- [Google ADK](https://github.com/google/adk-python) - Agent Development Kit for\n  building, evaluating, and deploying AI agents\n\n  16,907 stars · 2,718 forks · 213 contributors · 532 issues · Python · Apache-2.0\n\n  - Code-first development approach\n  - Modular multi-agent systems\n  - Model-agnostic and deployment-agnostic\n  - Built-in developer UI (adk-web)\n  - Deploy on Cloud Run or Vertex AI\n\n\n- [SuperAGI](https://github.com/TransformerOptimus/SuperAGI) - Open-source autonomous AI\n  agent framework\n\n  17,019 stars · 2,144 forks · 63 contributors · 202 issues · Python · MIT\n\n  - Customizable agent workflows\n  - Tool creation framework\n  - Performance monitoring\n  - Resource management\n  - Multi-vector memory storage\n\n\n- [Kiln AI](https://github.com/Kiln-AI/Kiln) - Tools for building AI products including\n  agents, evals, RAG systems, and fine-tuning\n\n  4,516 stars · 334 forks · 12 contributors · 34 issues · Python · NOASSERTION\n\n  - Free desktop application for no-code development\n  - Evaluation frameworks\n  - RAG system building\n  - Synthetic data generation\n  - Agent development tools\n\n\n- [AGiXT](https://github.com/Josh-XT/AGiXT) - Scalable framework for AI agents\n\n  3,139 stars · 443 forks · 41 contributors · 1 issues · Python · MIT\n\n  - Multi-provider support\n  - Chain of thought processing\n  - Extensible plugin system\n  - Command chaining\n  - Web UI included\n\n\n- [XAgent](https://github.com/OpenBMB/XAgent) - Autonomous LLM-based agent framework\n\n  8,484 stars · 891 forks · 33 contributors · 55 issues · Python · Apache-2.0\n\n  - Human-like planning\n  - Autonomous task decomposition\n  - Tool learning capabilities\n  - Advanced error recovery\n  - Built-in action validation\n\n\n- [Neurolink](https://github.com/juspay/neurolink) - Multi-provider AI agent framework\n  with workflow orchestration capabilities, unifying 12+ providers (OpenAI, Google,\n  Anthropic, AWS, Azure, Groq, Together AI, Mistral, Cohere, Fireworks, Cloudflare,\n  Ollama)\n\n  102 stars · 88 forks · 50 contributors · 402 issues · TypeScript · MIT\n\n  - Multi-agent framework with workflow orchestration\n  - Unified interface for 12+ AI providers\n  - Edge-first architecture with local/cloud deployment\n  - Production-grade streaming and tool calling\n  - Battle-tested at Juspay (15M+ requests/month)\n\n\n- [OpenAgents](https://github.com/xlang-ai/OpenAgents) - Open platform for language\n  agents\n\n  4,656 stars · 512 forks · 16 contributors · 12 issues · Python · Apache-2.0\n\n  - Data analysis capabilities\n  - Web browsing integration\n  - Coding assistance\n  - Plugin ecosystem\n  - Interactive visualization\n\n\n- [AI Legion](https://github.com/eumemic/ai-legion) - Swarm framework for autonomous\n  agents\n\n  1,431 stars · 174 forks · 6 contributors · 8 issues · TypeScript · MIT\n\n  - Multi-agent coordination\n  - Dynamic task allocation\n  - Emergent behavior support\n  - Flexible agent roles\n  - Real-time collaboration\n\n\n- [Agent Protocol](https://github.com/e2b-dev/agent-protocol) - Unified interface for AI\n  agents\n\n  1,432 stars · 171 forks · 14 contributors · 42 issues · Python · MIT\n\n  - Standardized communication\n  - Language-agnostic design\n  - Tool integration specs\n  - Interoperability focus\n  - Protocol versioning\n\n\n- [Agents.js](https://github.com/Webgburnet/Agents.js) - JavaScript framework for\n  building AI agents\n\n  - Browser-native implementation\n  - Event-driven architecture\n  - Tool abstraction layer\n  - Memory management\n  - Real-time processing- [Cache-to-Cache](https://github.com/thu-nics/C2C) - Novel paradigm for direct \n  semantic communication between LLMs via KV-Cache\n\n  87 stars · 6 forks · 2 contributors · 2 issues · Python · Apache-2.0\n\n  - Direct semantic communication via KV-Cache\n  - Multi-agent system integration\n  - Neural cache projection and fusion- [CAMEL](https://github.com/camel-ai/camel) - Communicative Agents for "Mind"\n  Exploration\n\n  14,875 stars · 1,638 forks · 171 contributors · 599 issues · Python · Apache-2.0\n\n  - Role-playing framework\n  - Task-oriented dialogue\n  - Multi-agent conversations\n  - Behavioral analysis\n  - Cognitive architecture- [BabyAGI](https://github.com/yoheinakajima/babyagi) - Lightweight framework for AI\n  task management\n\n  - Task prioritization\n  - Autonomous execution\n  - Memory persistence\n  - Goal-oriented planning\n  - Resource optimization- [Autonomous-GPT](https://github.com/Significant-Gravitas/Auto-GPT) - Framework for\n  autonomous GPT-4 agents\n\n  179,412 stars · 46,089 forks · 433 contributors · 273 issues · Python · NOASSERTION\n\n  - Internet access capabilities\n  - Long-term memory\n  - Goal-oriented behavior\n  - File operations\n  - Command execution- [MetaGPT](https://github.com/geekan/MetaGPT) - Multi-agent framework for software\n  development\n\n  59,615 stars · 7,299 forks · 115 contributors · 57 issues · Python · MIT\n\n  - Role-based development\n  - Code generation\n  - Project management\n  - Documentation writing\n  - Testing automation- [GenoMAS](https://github.com/Liu-Hy/GenoMAS) - Multi-agent framework for scientific\n  discovery and automated data analysis\n\n  123 stars · 19 forks · 1 contributors · 0 issues · Python · MIT\n\n  - Guided planning framework\n  - Typed message-passing protocol\n  - Heterogeneous LLM architecture\n  - Domain-agnostic design\n  - Scientific workflow automation- [minions](https://github.com/getminions/minions) - Extensible framework for AI\n  assistants\n\n  - Custom behavior definition\n  - Tool integration\n  - State management\n  - Event handling\n  - Parallel execution- [ix](https://github.com/kreneskyp/ix) - Autonomous agent framework\n\n  1,037 stars · 129 forks · 5 contributors · 14 issues · Python · MIT\n\n  - Visual workflow builder\n  - Sandbox environments\n  - Tool integration\n  - Process monitoring\n  - Agent collaboration- [saplings](https://github.com/shobrook/saplings) - Build smarter agents using tree\n  search\n\n  269 stars · 17 forks · 4 contributors · 0 issues · Python · Apache-2.0\n\n  - Boost reasoning abilities\n  - Supports popular search algorithms\n  - Minimal setup, 2 lines of code- [Smolagents](https://github.com/huggingface/smolagents) - Minimalist framework for\n  building powerful agents\n\n  24,406 stars · 2,180 forks · 189 contributors · 327 issues · Python · Apache-2.0\n\n  - Code-first approach\n  - Multi-agent orchestration\n  - LLM provider flexibility\n  - Tool integration\n  - Hub integration for sharing- [Flowise](https://github.com/FlowiseAI/Flowise) - Drag & drop UI framework for\n  building LLM flows\n\n  47,784 stars · 23,485 forks · 268 contributors · 747 issues · TypeScript · NOASSERTION\n\n  - Visual flow builder\n  - Custom LLM integrations\n  - API generation\n  - Authentication support\n  - Docker deployment\n\n\n- [Pydantic AI](https://github.com/pydantic/pydantic-ai) - Production-grade agent\n  framework built on Pydantic\n\n  14,116 stars · 1,513 forks · 332 contributors · 422 issues · Python · MIT\n\n  - Type-safe development\n  - Multi-model support\n  - Structured responses\n  - Dependency injection\n  - Logfire integration\n\n\n- [Upsonic](https://github.com/upsonic/upsonic) - Reliable agent framework that\n  support MCP.\n\n  7,737 stars · 712 forks · 33 contributors · 78 issues · Python · MIT\n\n  - Easy-to-activate reliability layers\n  - Model Context Protocol (MCP)\n  - Integrated Browser Use and Computer Use\n  - Isolated environment to run agents\n  - Task-Centric Design\n\n\n- [EvoAgentX](https://github.com/EvoAgentX/EvoAgentX) - Building a Self-Evolving\n  Ecosystem of AI Agents\n\n  2,431 stars · 193 forks · 24 contributors · 12 issues · Python · NOASSERTION\n\n  - Easy Agent and Workflow Customization\n  - Workflow Optimization & Self-Evolving\n  - Agent/workflow evolution algorithms integrated\n  - Execution Toolkit\n\n\n- [Portia AI](https://github.com/portiaAI/portia-sdk-python) - Open source framework for predictable,\n  controllable and authenticated agents.\n\n  1,141 stars · 101 forks · 26 contributors · 44 issues · Python · NOASSERTION\n\n  - Structured planning\n  - Stateful execution\n  - Human in the loop controls\n  - Tool catalogue with built-in auth\n  - MCP support- [Agentic Radar](https://github.com/splx-ai/agentic-radar) - A security scanner for\n  agentic workflows\n\n  848 stars · 106 forks · 8 contributors · 10 issues · Python · Apache-2.0\n\n  - Scans agentic workflow source code\n  - Finds vulnerabilities (CVE & OWASP)\n  - Generates interactive reports\n  - Suggests remediation steps\n  - Supports popular agentic workflows\n- [AgentFlow](https://github.com/lupantech/AgentFlow) - Trainable multi-agent framework\n  with in-the-flow optimization\n\n  1,465 stars · 188 forks · 4 contributors · 7 issues · Python · MIT\n\n  - Four specialized modules (planner, executor, verifier, generator)\n  - Flow-GRPO reinforcement learning\n  - Tool integration (math, coding, scientific, search)\n  - Stanford research project\n  - Performance gains over monolithic approaches\n\n\n- [Mastra](https://github.com/mastra-ai/mastra) - TypeScript AI agent framework with\n  assistants, RAG, and observability\n\n  19,103 stars · 1,379 forks · 279 contributors · 300 issues · TypeScript · NOASSERTION\n\n  - Type-safe development\n  - Multi-model support (GPT-4, Claude, Gemini, Llama)\n  - Structured responses\n  - API generation\n  - Tool integration\n\n\n- [Flappy](https://github.com/pleisto/flappy) - Production-ready LLM agent SDK\n\n  307 stars · 23 forks · 7 contributors · 10 issues · Rust · Apache-2.0\n\n  - Production-grade reliability\n  - Type-safe agent development\n  - Multi-language support\n  - Performance optimized\n  - Developer-friendly SDK\n\n\n- [CleverBee](https://github.com/SureScaleAI/cleverbee) - Deep research assistant agent\n  with web browsing capabilities\n\n  309 stars · 16 forks · 1 contributors · 1 issues · Python · AGPL-3.0\n\n  - Interactive web UI via Chainlit\n  - MCP tool support for external integrations\n  - Multi-LLM research (configurable LLMs)\n  - Automated web browsing with Playwright\n  - Token tracking and cost estimation\n\n\n- [RAI](https://github.com/RobotecAI/rai) - Agentic framework for robotics using ROS 2\n\n  428 stars · 54 forks · 22 contributors · 59 issues · Python · Apache-2.0\n\n  - ROS 2 integration\n  - Complex action execution\n  - Scenario-based testing\n  - Voice interaction support\n  - Vendor-agnostic architecture\n\n\n- [Floom](https://github.com/FloomAI/Floom) - AI gateway and agent/pipeline marketplace\n\n  46 stars · 4 forks · 2 contributors · 0 issues · C# · MIT\n\n  - AI pipeline orchestration\n  - Agent marketplace integration\n  - Kubernetes-style architecture\n  - Streamlined AI integration\n  - DevOps-friendly deployment\n\n\n- [CoreAgent](https://github.com/CoreAgent-Project/CoreAgent) - Minimalist agent framework\n  with stateful tools\n\n  25 stars · 3 forks · 2 issues · Python\n\n  - Simplicity-first design\n  - Stateful tool support\n  - Multi-agent coordination\n  - Shared state management\n  - Built-in tools library- [Project Alice](https://github.com/MarianoMolina/project_alice) - Framework and\n  platform for building and deploying agentic workflows\n\n  253 stars · 34 forks · 1 contributors · 1 issues · Python · BSD-3-Clause\n\n  - No-code and coding interface\n  - Visual workflow builder\n  - Live demo available\n  - Workflow deployment platform\n  - Alpha stage development- [AgentSquare](https://github.com/tsinghua-fib-lab/AgentSquare) - Automatic LLM agent\n  search in modular design space\n\n  199 stars · 14 forks · 10 issues · HTML\n\n  - Module evolution and recombination\n  - Planning, Reasoning, Tool Use, Memory modules\n  - Adaptive agent search framework\n  - Unified framework for six agent tasks\n  - Tsinghua University research project\n', 'category': 'agentic framework'}

In [22]:
examples.append(agentic_framework)

In [23]:
agentic_benchmark = (df[df["full_name"] == "THUDM/AgentBench"].iloc[0].to_dict())
print(agentic_benchmark)

{'full_name': 'THUDM/AgentBench', 'description': "A Comprehensive Benchmark to Evaluate LLMs as Agents (ICLR'24)", 'stars': 3065, 'forks': 221, 'language': 'Python', 'url': 'https://github.com/THUDM/AgentBench', 'updated_year': 2025, 'last_updated': '2025-11-17T07:28:33+00:00', 'created_year': 2023, 'created_at': '2023-07-28T04:32:06+00:00', 'watchers_count': 3065, 'size': 30392, 'license': 'Apache License 2.0', 'languages': "{'Python': 263997, 'Shell': 18426, 'PDDL': 17067, 'Dockerfile': 7312}", 'primary_language': 'Python', 'topics': "['chatgpt', 'gpt-4', 'llm', 'llm-agent']", 'readme_content': '# AgentBench\n\n![](./assets/cover.jpg)\n\n<p align="center">\n   <a href="https://docs.google.com/spreadsheets/d/e/2PACX-1vRR3Wl7wsCgHpwUw1_eUXW_fptAPLL3FkhnW_rua0O1Ji_GIVrpTjY5LaKAhwO-WeARjnY_KNw0SYNJ/pubhtml" target="_blank">🌐 Leaderboard (new)</a> | <a href="https://twitter.com/thukeg" target="_blank">🐦 Twitter</a> | <a href="mailto:agentbench@googlegroups.com">✉️ Google Group</a> | <a href="https://arxiv.org/abs/2308.03688" target="_blank">📃 Paper </a>\n</p>\n\n<p align="center">\n👋 Join our <a href="https://join.slack.com/t/agentbenchcol-huw1944/shared_invite/zt-20ixabcuv-31cFLBAkqGQxQkJqrWVEVg" target="_blank">Slack</a>  for <i>Q & A</i> or <i><b>collaboration</b> on next version of AgentBench</i>!\n</p>\n\n## 🔥[2025.10.10] Introducing **AgentBench FC (Function Calling)** based on [AgentRL](https://github.com/THUDM/AgentRL)\n\nThe current repository contains the function-calling version of AgentBench, integrated with [AgentRL](https://github.com/THUDM/AgentRL), an end-to-end multitask and mutliturn LLM Agent RL framework.\nIf you wish to use the older version, you can revert to [v0.1](https://github.com/THUDM/AgentBench/tree/v0.1) and [v0.2](https://github.com/THUDM/AgentBench/tree/v0.2).\n\nComparing to the original AgentBench, this version uses a function-calling style prompt,\nand adds fully-containerized deployment support for the following tasks:\n\n- `alfworld` (AF)\n- `dbbench` (DB)\n- `knowledgegraph` (KG)\n- `os_interaction` (OS)\n- `webshop` (WS)\n\n### Quick Start\n\nWe support a quick one-command setup for all the above tasks using Docker Compose.\n\nBefore starting, please download or build the following Docker images required by the tasks:\n\n```shell\n# dbbench\ndocker pull mysql:8\n\n# os_interaction\ndocker build -t local-os/default -f ./data/os_interaction/res/dockerfiles/default data/os_interaction/res/dockerfiles\ndocker build -t local-os/packages -f ./data/os_interaction/res/dockerfiles/packages data/os_interaction/res/dockerfiles\ndocker build -t local-os/ubuntu -f ./data/os_interaction/res/dockerfiles/ubuntu data/os_interaction/res/dockerfiles\n```\n\nTo run the KG freebase server, you will also need a copy of the data found [here](https://github.com/dki-lab/Freebase-Setup).\nDownload, extract and place the data at `./virtuoso_db/virtuoso.db` (or modify `extra/docker-compose.yml` and set the mount point to your data location).\n\nThen, you can bring up the stack with:\n\n```shell\ndocker compose -f extra/docker-compose.yml up\n```\n\nThis command will download or build the necessary Docker images and start the following services in Docker:\n\n- AgentRL Controller\n- `alfworld` task worker (x1, increase as needed)\n- `dbbench` task worker (x1, increase as needed)\n- `knowledgegraph` task worker (x1, increase as needed)\n- `os_interaction` task worker (x1, increase as needed)\n- `webshop` task worker (x1, increase as needed)\n- freebase server (for `knowledgegraph` task)\n- Redis server (for container allocation)\n\nIf your machine already has Redis (version 7+) running, you can omit the Redis service from the `docker-compose.yml`.\n\n> [!WARNING]  \n> Please note that the `webshop` environment requires ~16GB of RAM to start,\n> and the current implementation of `alfworld` leaks memory and disk space until the task worker is restarted.\n> Make sure your machine has sufficient resources before running.\n\n### Benchmarking Results\n\nWe report the results of various models on the test set of AgentBench FC.\n\n![img.png](assets/fc_leaderboard.png)\n\nPlease see our [Leaderboard](https://docs.google.com/spreadsheets/d/e/2PACX-1vRR3Wl7wsCgHpwUw1_eUXW_fptAPLL3FkhnW_rua0O1Ji_GIVrpTjY5LaKAhwO-WeARjnY_KNw0SYNJ/pubhtml) for full results.\nPlease contact [agentbench_fc&#64;googlegroups.com](mailto:agentbench_fc@googlegroups.com) if you have any questions or would like to contribute your results.\n\n---\n\n## 🔥[2024.08.13] Introducing [VisualAgentBench](https://github.com/THUDM/VisualAgentBench)\n\nVisualAgentBench is designed for evaluating and training visual foundation agents based on large multimodel models (LMMs). We introduce 5 distinct environments spanning \n\n* Embodied: VAB-OmniGibson, VAB-Minecraft\n* GUI: VAB-Mobile, VAB-WebArena-Lite\n* Visual Design: VAB-CSS\n\nto systematically benchmark 17 LMMs (proprietary & open LMMs). We also provide the trajectory dataset for behavior cloning training on open LMMs for you to develop your own visual foundation agents!\n\n---\n\nThe following is the introduction to the original AgentBench (v0.2).\n\n# AgentBench: Evaluating LLMs as Agents\n\nhttps://github.com/THUDM/AgentBench/assets/129033897/656eed6e-d9d9-4d07-b568-f43f5a451f04\n\n**AgentBench** is the first benchmark designed to evaluate **LLM-as-Agent** across a diverse spectrum of different\nenvironments. It encompasses 8 distinct environments to provide a more comprehensive evaluation of the LLMs\' ability to\noperate as autonomous agents in various scenarios. These environments include 5 freshly created domains, namely\n\n-   Operating System (OS)\n-   Database (DB)\n-   Knowledge Graph (KG)\n-   Digital Card Game (DCG)\n-   Lateral Thinking Puzzles (LTP)\n\nas well as 3 recompiled from published datasets:\n\n-   House-Holding (HH) ([ALFWorld](https://github.com/alfworld/alfworld))\n-   Web Shopping (WS) ([WebShop](https://github.com/princeton-nlp/webshop))\n-   Web Browsing (WB) ([Mind2Web](https://github.com/OSU-NLP-Group/Mind2Web))\n\n![](./assets/agentbench.png)\n\n## Table of Contents\n\n-   [Dataset Summary](#dataset-summary)\n-   [Leaderboard](#leaderboard)\n-   [Quick Start](#quick-start)\n-   [Next Steps](#next-steps)\n-   [Citation](#citation)\n\n## Dataset Summary\n\nWe offer two splits for each dataset: Dev and Test. The multi-turn interaction requires an LLMs to generate around 4k\nand 13k times respectively.\n\n![](./assets/statistics.png)\n\n## Leaderboard\n\nHere is the scores on test set (standard) results of AgentBench.\n\n![](./assets/leaderboard.png)\n\nWhile LLMs begin to manifest their proficiency in LLM-as-Agent, gaps between models and the distance towards practical\nusability are significant.\n\n![](./assets/intro.png)\n\n## Quick Start\n\nThis section will guide you on how to quickly use gpt-3.5-turbo-0613 as an agent to launch the `dbbench-std` and `os-std` tasks.\nFor the specific framework structure, please refer to [Framework Introduction](docs/Introduction_en.md).\nFor more detailed configuration and launch methods, please check [Configuration Guide](docs/Config_en.md)\nand [Program Entrance Guide](docs/Entrance_en.md).\n\n### Step 1. Prerequisites\n\nClone this repo and install the dependencies.\n\n```bash\ncd AgentBench\nconda create -n agent-bench python=3.9\nconda activate agent-bench\npip install -r requirements.txt\n```\n\nEnsure that [Docker](https://www.docker.com/) is properly installed.\n\n```bash\ndocker ps\n```\n\nBuild required images for `dbbench-std` and `os-std`.\n\n```bash\ndocker pull mysql\ndocker pull ubuntu\ndocker build -f data/os_interaction/res/dockerfiles/default data/os_interaction/res/dockerfiles --tag local-os/default\ndocker build -f data/os_interaction/res/dockerfiles/packages data/os_interaction/res/dockerfiles --tag local-os/packages\ndocker build -f data/os_interaction/res/dockerfiles/ubuntu data/os_interaction/res/dockerfiles --tag local-os/ubuntu\n```\n\n### Step 2. Configure the Agent\n\nFill in your OpenAI API Key at the correct location in `configs/agents/openai-chat.yaml`. (e.g. `gpt-3.5-turbo-0613`)\n\nYou can try using `python -m src.client.agent_test` to check if your agent is configured correctly.\n\nBy default, `gpt-3.5-turbo-0613` will be started. You can replace it with other agents by modifying the parameters:\n\n```bash\npython -m src.client.agent_test --config configs/agents/api_agents.yaml --agent gpt-3.5-turbo-0613\n```\n\n### Step 3. Start the task server\n\nStarting the task worker involves specific tasks. Manual starting might be cumbersome; hence, we provide an automated\nscript.\n\nThe assumption for this step is that ports from 5000 to 5015 are available. For Mac OS system, you may want to follow [here](https://stackoverflow.com/questions/69955686/why-cant-i-run-the-project-on-port-5000) to free port 5000 to use.\n\n```bash\npython -m src.start_task -a\n```\n\nThis will launch five task_workers each for `dbbench-std` and `os-std` tasks and automatically connect them\nto the controller on port 5000. **After executing this command, please allow approximately 1 minute for the task setup to complete.** If the terminal shows ".... 200 OK", you can open another terminal and follow step 4.\n\n### Step 4. Start the assigner\n\nThis step is to actually start the tasks.\n\nIf everything is correctly configured so far, you can now initiate the task tests.\n\n```bash\npython -m src.assigner\n```\n\n## Next Steps\n\nIf you wish to launch more tasks or use other models, you can refer to the content\nin [Configuration Guide](docs/Config_en.md) and [Program Entrance Guide](docs/Entrance_en.md).\n\nFor the environment of the remaining five tasks, you will need to download the Docker images we provide.\n\n```\nlonginyu/agentbench-ltp\nlonginyu/agentbench-webshop\nlonginyu/agentbench-mind2web\nlonginyu/agentbench-card_game\nlonginyu/agentbench-alfworld\n```\n\nThe resource consumption of a single task_worker for the eight tasks is roughly as follows; consider this when\nlaunching:\n\n| Task Name | Start-up Speed | Memory Consumption |\n| --------- | -------------- | ------------------ |\n| webshop   | ~3min          | ~15G               |\n| mind2web  | ~5min          | ~1G                |\n| db        | ~20s           | < 500M             |\n| alfworld  | ~10s           | < 500M             |\n| card_game | ~5s            | < 500M             |\n| ltp       | ~5s            | < 500M             |\n| os        | ~5s            | < 500M             |\n| kg        | ~5s            | < 500M             |\n\n\n### Deploy the KnowledgeGraph service loacally\nthe KnowledgeGraph task depends on an online service which now is not stable, if you want to deploy the service locally, you can follow steps below:\n\n**step1.** <br />\ndownload the database and setup the service [freebase-setup](https://github.com/dki-lab/Freebase-Setup).\n\n\n**step2.** <br />\nchange this line `sparql_url: "http://164.107.116.56:3093/sparql"` to `sparql_url: "<your service api of sparql>"` in `/configs/tasks/kg.yaml`.\n\n**P.S.** you should start your KG service before you start the agent tasks services.\n\n## Extending AgentBench\n\nIf you wish to add new tasks to AgentBench, you may refer to [Extension Guide](docs/Extension_en.md).\n\n## References\n\nAvalon task is merged from [AvalonBench](https://github.com/jonathanmli/Avalon-LLM/), which implements a multi-agent framework.\n\n## Citation\n\n```\n@article{liu2023agentbench,\n  title   = {AgentBench: Evaluating LLMs as Agents},\n  author  = {Xiao Liu and Hao Yu and Hanchen Zhang and Yifan Xu and Xuanyu Lei and Hanyu Lai and Yu Gu and Hangliang Ding and Kaiwen Men and Kejuan Yang and Shudan Zhang and Xiang Deng and Aohan Zeng and Zhengxiao Du and Chenhui Zhang and Sheng Shen and Tianjun Zhang and Yu Su and Huan Sun and Minlie Huang and Yuxiao Dong and Jie Tang},\n  year    = {2023},\n  journal = {arXiv preprint arXiv: 2308.03688}\n}\n```\n'}

In [24]:
agentic_benchmark.setdefault("category", "agentic benchmark")

'agentic benchmark'

In [25]:
examples.append(agentic_benchmark)

In [26]:
print(examples)

[{'full_name': 'kaushikb11/awesome-llm-agents', 'description': 'A curated list of awesome LLM agents frameworks.', 'stars': 1263, 'forks': 134, 'language': 'Python', 'url': 'https://github.com/kaushikb11/awesome-llm-agents', 'updated_year': 2026, 'last_updated': '2026-01-04T02:32:04+00:00', 'created_year': 2023, 'created_at': '2023-04-04T10:22:43+00:00', 'watchers_count': 1263, 'size': 39, 'license': nan, 'languages': "{'Python': 4698}", 'primary_language': 'Python', 'topics': "['agents', 'langchain', 'llm']", 'readme_content': '# Awesome LLM Agent Frameworks [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)\n\nA curated list of awesome LLM frameworks and agent development tools. If you have a\nsuggestion, feel free to open an issue or pull request. (Last updated: 2026-01-04)\n\n## Frameworks\n\n- [CrewAI](https://github.com/joaomdmoura/crewAI) - Framework for orchestrating\n  role-playing AI agents\n\n  42,166 stars · 5,646 forks · 269 contributors · 187 issues · Python · MIT\n\n  - Role-based agent design\n  - Multi-agent collaboration\n  - Flexible memory system\n  - Built-in error handling\n\n\n- [Langchain](https://github.com/hwchase17/langchain) - Building applications with LLMs\n  through composability\n\n  123,299 stars · 20,329 forks · 470 contributors · 354 issues · Python · MIT\n\n  - Modular and extensible architecture\n  - Unified interface for LLMs\n  - Pre-built agent toolkits\n  - CSV, JSON, and SQL agents\n  - Python and Pandas integration\n  - Vector store capabilities\n\n\n- [Microsoft AutoGen](https://github.com/microsoft/autogen) - Framework for building\n  multi-agent conversational systems\n\n  53,102 stars · 8,065 forks · 446 contributors · 536 issues · Python · CC-BY-4.0\n\n  - Multi-agent architecture\n  - Customizable agents\n  - Code execution support\n  - Flexible human involvement\n  - Advanced conversation management\n\n\n- [OpenManus](https://github.com/FoundationAgents/OpenManus) - Open-source AI agent\n  platform for building general-purpose agents\n\n  52,009 stars · 9,129 forks · 53 contributors · 522 issues · Python · MIT\n\n  - Modular architecture for customization\n  - Data analysis and visualization agents\n  - Reinforcement learning integration (OpenManus-RL)\n  - No invitation code required\n  - Built by MetaGPT contributors\n\n\n- [Llama Index](https://github.com/run-llama/llama_index) - Data framework for LLM\n  applications\n\n  46,128 stars · 6,678 forks · 474 contributors · 277 issues · Python · MIT\n\n  - Advanced indexing and retrieval\n  - Support for 160+ data sources\n  - Customizable RAG workflows\n  - Structured data handling\n  - Query optimization\n\n\n- [Microsoft Semantic Kernel](https://github.com/microsoft/semantic-kernel) -\n  Integration framework for AI models\n\n  26,959 stars · 4,408 forks · 389 contributors · 540 issues · C# · MIT\n\n  - Enterprise-grade security\n  - Multi-language support\n  - Plugin architecture\n  - Responsible AI features\n  - Memory management\n\n\n- [Dify](https://github.com/langgenius/dify) - Open-source framework for LLM\n  applications\n\n  124,493 stars · 19,359 forks · 464 contributors · 660 issues · Python · NOASSERTION\n\n  - Visual prompt orchestration\n  - Long context integration\n  - API-based development\n  - Multi-model support\n  - RAG pipeline\n\n\n- [Haystack](https://github.com/deepset-ai/haystack) - End-to-end NLP framework\n\n  23,780 stars · 2,542 forks · 307 contributors · 112 issues · MDX · Apache-2.0\n\n  - Document processing\n  - Neural search\n  - Question answering\n  - Semantic search\n  - Agent capabilities\n\n\n- [Embedchain](https://github.com/embedchain/embedchain) - Framework for ChatGPT-like\n  bots\n\n  44,944 stars · 4,903 forks · 245 contributors · 586 issues · Python · Apache-2.0\n\n  - Multi-source data ingestion\n  - Automated embedding\n  - Context window management\n  - Multiple LLM support\n  - RAG optimization\n\n\n- [Google ADK](https://github.com/google/adk-python) - Agent Development Kit for\n  building, evaluating, and deploying AI agents\n\n  16,907 stars · 2,718 forks · 213 contributors · 532 issues · Python · Apache-2.0\n\n  - Code-first development approach\n  - Modular multi-agent systems\n  - Model-agnostic and deployment-agnostic\n  - Built-in developer UI (adk-web)\n  - Deploy on Cloud Run or Vertex AI\n\n\n- [SuperAGI](https://github.com/TransformerOptimus/SuperAGI) - Open-source autonomous AI\n  agent framework\n\n  17,019 stars · 2,144 forks · 63 contributors · 202 issues · Python · MIT\n\n  - Customizable agent workflows\n  - Tool creation framework\n  - Performance monitoring\n  - Resource management\n  - Multi-vector memory storage\n\n\n- [Kiln AI](https://github.com/Kiln-AI/Kiln) - Tools for building AI products including\n  agents, evals, RAG systems, and fine-tuning\n\n  4,516 stars · 334 forks · 12 contributors · 34 issues · Python · NOASSERTION\n\n  - Free desktop application for no-code development\n  - Evaluation frameworks\n  - RAG system building\n  - Synthetic data generation\n  - Agent development tools\n\n\n- [AGiXT](https://github.com/Josh-XT/AGiXT) - Scalable framework for AI agents\n\n  3,139 stars · 443 forks · 41 contributors · 1 issues · Python · MIT\n\n  - Multi-provider support\n  - Chain of thought processing\n  - Extensible plugin system\n  - Command chaining\n  - Web UI included\n\n\n- [XAgent](https://github.com/OpenBMB/XAgent) - Autonomous LLM-based agent framework\n\n  8,484 stars · 891 forks · 33 contributors · 55 issues · Python · Apache-2.0\n\n  - Human-like planning\n  - Autonomous task decomposition\n  - Tool learning capabilities\n  - Advanced error recovery\n  - Built-in action validation\n\n\n- [Neurolink](https://github.com/juspay/neurolink) - Multi-provider AI agent framework\n  with workflow orchestration capabilities, unifying 12+ providers (OpenAI, Google,\n  Anthropic, AWS, Azure, Groq, Together AI, Mistral, Cohere, Fireworks, Cloudflare,\n  Ollama)\n\n  102 stars · 88 forks · 50 contributors · 402 issues · TypeScript · MIT\n\n  - Multi-agent framework with workflow orchestration\n  - Unified interface for 12+ AI providers\n  - Edge-first architecture with local/cloud deployment\n  - Production-grade streaming and tool calling\n  - Battle-tested at Juspay (15M+ requests/month)\n\n\n- [OpenAgents](https://github.com/xlang-ai/OpenAgents) - Open platform for language\n  agents\n\n  4,656 stars · 512 forks · 16 contributors · 12 issues · Python · Apache-2.0\n\n  - Data analysis capabilities\n  - Web browsing integration\n  - Coding assistance\n  - Plugin ecosystem\n  - Interactive visualization\n\n\n- [AI Legion](https://github.com/eumemic/ai-legion) - Swarm framework for autonomous\n  agents\n\n  1,431 stars · 174 forks · 6 contributors · 8 issues · TypeScript · MIT\n\n  - Multi-agent coordination\n  - Dynamic task allocation\n  - Emergent behavior support\n  - Flexible agent roles\n  - Real-time collaboration\n\n\n- [Agent Protocol](https://github.com/e2b-dev/agent-protocol) - Unified interface for AI\n  agents\n\n  1,432 stars · 171 forks · 14 contributors · 42 issues · Python · MIT\n\n  - Standardized communication\n  - Language-agnostic design\n  - Tool integration specs\n  - Interoperability focus\n  - Protocol versioning\n\n\n- [Agents.js](https://github.com/Webgburnet/Agents.js) - JavaScript framework for\n  building AI agents\n\n  - Browser-native implementation\n  - Event-driven architecture\n  - Tool abstraction layer\n  - Memory management\n  - Real-time processing- [Cache-to-Cache](https://github.com/thu-nics/C2C) - Novel paradigm for direct \n  semantic communication between LLMs via KV-Cache\n\n  87 stars · 6 forks · 2 contributors · 2 issues · Python · Apache-2.0\n\n  - Direct semantic communication via KV-Cache\n  - Multi-agent system integration\n  - Neural cache projection and fusion- [CAMEL](https://github.com/camel-ai/camel) - Communicative Agents for "Mind"\n  Exploration\n\n  14,875 stars · 1,638 forks · 171 contributors · 599 issues · Python · Apache-2.0\n\n  - Role-playing framework\n  - Task-oriented dialogue\n  - Multi-agent conversations\n  - Behavioral analysis\n  - Cognitive architecture- [BabyAGI](https://github.com/yoheinakajima/babyagi) - Lightweight framework for AI\n  task management\n\n  - Task prioritization\n  - Autonomous execution\n  - Memory persistence\n  - Goal-oriented planning\n  - Resource optimization- [Autonomous-GPT](https://github.com/Significant-Gravitas/Auto-GPT) - Framework for\n  autonomous GPT-4 agents\n\n  179,412 stars · 46,089 forks · 433 contributors · 273 issues · Python · NOASSERTION\n\n  - Internet access capabilities\n  - Long-term memory\n  - Goal-oriented behavior\n  - File operations\n  - Command execution- [MetaGPT](https://github.com/geekan/MetaGPT) - Multi-agent framework for software\n  development\n\n  59,615 stars · 7,299 forks · 115 contributors · 57 issues · Python · MIT\n\n  - Role-based development\n  - Code generation\n  - Project management\n  - Documentation writing\n  - Testing automation- [GenoMAS](https://github.com/Liu-Hy/GenoMAS) - Multi-agent framework for scientific\n  discovery and automated data analysis\n\n  123 stars · 19 forks · 1 contributors · 0 issues · Python · MIT\n\n  - Guided planning framework\n  - Typed message-passing protocol\n  - Heterogeneous LLM architecture\n  - Domain-agnostic design\n  - Scientific workflow automation- [minions](https://github.com/getminions/minions) - Extensible framework for AI\n  assistants\n\n  - Custom behavior definition\n  - Tool integration\n  - State management\n  - Event handling\n  - Parallel execution- [ix](https://github.com/kreneskyp/ix) - Autonomous agent framework\n\n  1,037 stars · 129 forks · 5 contributors · 14 issues · Python · MIT\n\n  - Visual workflow builder\n  - Sandbox environments\n  - Tool integration\n  - Process monitoring\n  - Agent collaboration- [saplings](https://github.com/shobrook/saplings) - Build smarter agents using tree\n  search\n\n  269 stars · 17 forks · 4 contributors · 0 issues · Python · Apache-2.0\n\n  - Boost reasoning abilities\n  - Supports popular search algorithms\n  - Minimal setup, 2 lines of code- [Smolagents](https://github.com/huggingface/smolagents) - Minimalist framework for\n  building powerful agents\n\n  24,406 stars · 2,180 forks · 189 contributors · 327 issues · Python · Apache-2.0\n\n  - Code-first approach\n  - Multi-agent orchestration\n  - LLM provider flexibility\n  - Tool integration\n  - Hub integration for sharing- [Flowise](https://github.com/FlowiseAI/Flowise) - Drag & drop UI framework for\n  building LLM flows\n\n  47,784 stars · 23,485 forks · 268 contributors · 747 issues · TypeScript · NOASSERTION\n\n  - Visual flow builder\n  - Custom LLM integrations\n  - API generation\n  - Authentication support\n  - Docker deployment\n\n\n- [Pydantic AI](https://github.com/pydantic/pydantic-ai) - Production-grade agent\n  framework built on Pydantic\n\n  14,116 stars · 1,513 forks · 332 contributors · 422 issues · Python · MIT\n\n  - Type-safe development\n  - Multi-model support\n  - Structured responses\n  - Dependency injection\n  - Logfire integration\n\n\n- [Upsonic](https://github.com/upsonic/upsonic) - Reliable agent framework that\n  support MCP.\n\n  7,737 stars · 712 forks · 33 contributors · 78 issues · Python · MIT\n\n  - Easy-to-activate reliability layers\n  - Model Context Protocol (MCP)\n  - Integrated Browser Use and Computer Use\n  - Isolated environment to run agents\n  - Task-Centric Design\n\n\n- [EvoAgentX](https://github.com/EvoAgentX/EvoAgentX) - Building a Self-Evolving\n  Ecosystem of AI Agents\n\n  2,431 stars · 193 forks · 24 contributors · 12 issues · Python · NOASSERTION\n\n  - Easy Agent and Workflow Customization\n  - Workflow Optimization & Self-Evolving\n  - Agent/workflow evolution algorithms integrated\n  - Execution Toolkit\n\n\n- [Portia AI](https://github.com/portiaAI/portia-sdk-python) - Open source framework for predictable,\n  controllable and authenticated agents.\n\n  1,141 stars · 101 forks · 26 contributors · 44 issues · Python · NOASSERTION\n\n  - Structured planning\n  - Stateful execution\n  - Human in the loop controls\n  - Tool catalogue with built-in auth\n  - MCP support- [Agentic Radar](https://github.com/splx-ai/agentic-radar) - A security scanner for\n  agentic workflows\n\n  848 stars · 106 forks · 8 contributors · 10 issues · Python · Apache-2.0\n\n  - Scans agentic workflow source code\n  - Finds vulnerabilities (CVE & OWASP)\n  - Generates interactive reports\n  - Suggests remediation steps\n  - Supports popular agentic workflows\n- [AgentFlow](https://github.com/lupantech/AgentFlow) - Trainable multi-agent framework\n  with in-the-flow optimization\n\n  1,465 stars · 188 forks · 4 contributors · 7 issues · Python · MIT\n\n  - Four specialized modules (planner, executor, verifier, generator)\n  - Flow-GRPO reinforcement learning\n  - Tool integration (math, coding, scientific, search)\n  - Stanford research project\n  - Performance gains over monolithic approaches\n\n\n- [Mastra](https://github.com/mastra-ai/mastra) - TypeScript AI agent framework with\n  assistants, RAG, and observability\n\n  19,103 stars · 1,379 forks · 279 contributors · 300 issues · TypeScript · NOASSERTION\n\n  - Type-safe development\n  - Multi-model support (GPT-4, Claude, Gemini, Llama)\n  - Structured responses\n  - API generation\n  - Tool integration\n\n\n- [Flappy](https://github.com/pleisto/flappy) - Production-ready LLM agent SDK\n\n  307 stars · 23 forks · 7 contributors · 10 issues · Rust · Apache-2.0\n\n  - Production-grade reliability\n  - Type-safe agent development\n  - Multi-language support\n  - Performance optimized\n  - Developer-friendly SDK\n\n\n- [CleverBee](https://github.com/SureScaleAI/cleverbee) - Deep research assistant agent\n  with web browsing capabilities\n\n  309 stars · 16 forks · 1 contributors · 1 issues · Python · AGPL-3.0\n\n  - Interactive web UI via Chainlit\n  - MCP tool support for external integrations\n  - Multi-LLM research (configurable LLMs)\n  - Automated web browsing with Playwright\n  - Token tracking and cost estimation\n\n\n- [RAI](https://github.com/RobotecAI/rai) - Agentic framework for robotics using ROS 2\n\n  428 stars · 54 forks · 22 contributors · 59 issues · Python · Apache-2.0\n\n  - ROS 2 integration\n  - Complex action execution\n  - Scenario-based testing\n  - Voice interaction support\n  - Vendor-agnostic architecture\n\n\n- [Floom](https://github.com/FloomAI/Floom) - AI gateway and agent/pipeline marketplace\n\n  46 stars · 4 forks · 2 contributors · 0 issues · C# · MIT\n\n  - AI pipeline orchestration\n  - Agent marketplace integration\n  - Kubernetes-style architecture\n  - Streamlined AI integration\n  - DevOps-friendly deployment\n\n\n- [CoreAgent](https://github.com/CoreAgent-Project/CoreAgent) - Minimalist agent framework\n  with stateful tools\n\n  25 stars · 3 forks · 2 issues · Python\n\n  - Simplicity-first design\n  - Stateful tool support\n  - Multi-agent coordination\n  - Shared state management\n  - Built-in tools library- [Project Alice](https://github.com/MarianoMolina/project_alice) - Framework and\n  platform for building and deploying agentic workflows\n\n  253 stars · 34 forks · 1 contributors · 1 issues · Python · BSD-3-Clause\n\n  - No-code and coding interface\n  - Visual workflow builder\n  - Live demo available\n  - Workflow deployment platform\n  - Alpha stage development- [AgentSquare](https://github.com/tsinghua-fib-lab/AgentSquare) - Automatic LLM agent\n  search in modular design space\n\n  199 stars · 14 forks · 10 issues · HTML\n\n  - Module evolution and recombination\n  - Planning, Reasoning, Tool Use, Memory modules\n  - Adaptive agent search framework\n  - Unified framework for six agent tasks\n  - Tsinghua University research project\n', 'category': 'agentic framework'}, {'full_name': 'THUDM/AgentBench', 'description': "A Comprehensive Benchmark to Evaluate LLMs as Agents (ICLR'24)", 'stars': 3065, 'forks': 221, 'language': 'Python', 'url': 'https://github.com/THUDM/AgentBench', 'updated_year': 2025, 'last_updated': '2025-11-17T07:28:33+00:00', 'created_year': 2023, 'created_at': '2023-07-28T04:32:06+00:00', 'watchers_count': 3065, 'size': 30392, 'license': 'Apache License 2.0', 'languages': "{'Python': 263997, 'Shell': 18426, 'PDDL': 17067, 'Dockerfile': 7312}", 'primary_language': 'Python', 'topics': "['chatgpt', 'gpt-4', 'llm', 'llm-agent']", 'readme_content': '# AgentBench\n\n![](./assets/cover.jpg)\n\n<p align="center">\n   <a href="https://docs.google.com/spreadsheets/d/e/2PACX-1vRR3Wl7wsCgHpwUw1_eUXW_fptAPLL3FkhnW_rua0O1Ji_GIVrpTjY5LaKAhwO-WeARjnY_KNw0SYNJ/pubhtml" target="_blank">🌐 Leaderboard (new)</a> | <a href="https://twitter.com/thukeg" target="_blank">🐦 Twitter</a> | <a href="mailto:agentbench@googlegroups.com">✉️ Google Group</a> | <a href="https://arxiv.org/abs/2308.03688" target="_blank">📃 Paper </a>\n</p>\n\n<p align="center">\n👋 Join our <a href="https://join.slack.com/t/agentbenchcol-huw1944/shared_invite/zt-20ixabcuv-31cFLBAkqGQxQkJqrWVEVg" target="_blank">Slack</a>  for <i>Q & A</i> or <i><b>collaboration</b> on next version of AgentBench</i>!\n</p>\n\n## 🔥[2025.10.10] Introducing **AgentBench FC (Function Calling)** based on [AgentRL](https://github.com/THUDM/AgentRL)\n\nThe current repository contains the function-calling version of AgentBench, integrated with [AgentRL](https://github.com/THUDM/AgentRL), an end-to-end multitask and mutliturn LLM Agent RL framework.\nIf you wish to use the older version, you can revert to [v0.1](https://github.com/THUDM/AgentBench/tree/v0.1) and [v0.2](https://github.com/THUDM/AgentBench/tree/v0.2).\n\nComparing to the original AgentBench, this version uses a function-calling style prompt,\nand adds fully-containerized deployment support for the following tasks:\n\n- `alfworld` (AF)\n- `dbbench` (DB)\n- `knowledgegraph` (KG)\n- `os_interaction` (OS)\n- `webshop` (WS)\n\n### Quick Start\n\nWe support a quick one-command setup for all the above tasks using Docker Compose.\n\nBefore starting, please download or build the following Docker images required by the tasks:\n\n```shell\n# dbbench\ndocker pull mysql:8\n\n# os_interaction\ndocker build -t local-os/default -f ./data/os_interaction/res/dockerfiles/default data/os_interaction/res/dockerfiles\ndocker build -t local-os/packages -f ./data/os_interaction/res/dockerfiles/packages data/os_interaction/res/dockerfiles\ndocker build -t local-os/ubuntu -f ./data/os_interaction/res/dockerfiles/ubuntu data/os_interaction/res/dockerfiles\n```\n\nTo run the KG freebase server, you will also need a copy of the data found [here](https://github.com/dki-lab/Freebase-Setup).\nDownload, extract and place the data at `./virtuoso_db/virtuoso.db` (or modify `extra/docker-compose.yml` and set the mount point to your data location).\n\nThen, you can bring up the stack with:\n\n```shell\ndocker compose -f extra/docker-compose.yml up\n```\n\nThis command will download or build the necessary Docker images and start the following services in Docker:\n\n- AgentRL Controller\n- `alfworld` task worker (x1, increase as needed)\n- `dbbench` task worker (x1, increase as needed)\n- `knowledgegraph` task worker (x1, increase as needed)\n- `os_interaction` task worker (x1, increase as needed)\n- `webshop` task worker (x1, increase as needed)\n- freebase server (for `knowledgegraph` task)\n- Redis server (for container allocation)\n\nIf your machine already has Redis (version 7+) running, you can omit the Redis service from the `docker-compose.yml`.\n\n> [!WARNING]  \n> Please note that the `webshop` environment requires ~16GB of RAM to start,\n> and the current implementation of `alfworld` leaks memory and disk space until the task worker is restarted.\n> Make sure your machine has sufficient resources before running.\n\n### Benchmar

In [27]:
foundation_model = (df[df["full_name"] == "zai-org/GLM-4.5"].iloc[0].to_dict())
print(foundation_model)

{'full_name': 'zai-org/GLM-4.5', 'description': 'GLM-4.5: Agentic, Reasoning, and Coding (ARC) Foundation Models', 'stars': 3723, 'forks': 386, 'language': 'Python', 'url': 'https://github.com/zai-org/GLM-4.5', 'updated_year': 2025, 'last_updated': '2025-12-23T06:11:48+00:00', 'created_year': 2025, 'created_at': '2025-07-20T09:24:09+00:00', 'watchers_count': 3723, 'size': 7703, 'license': 'Apache License 2.0', 'languages': "{'Python': 3759}", 'primary_language': 'Python', 'topics': "['agent', 'llm', 'moe', 'reasoning-language-models', 'glm']", 'readme_content': '# GLM-4.7 & GLM-4.6 & GLM-4.5\n\n[中文阅读](./README_zh.md) | [日本語版](./README_ja.md)\n\n<div align="center">\n<img src=resources/logo.svg width="15%"/>\n</div>\n<p align="center">\n    👋 Join our <a href="resources/WECHAT.md" target="_blank">WeChat</a> or <a href="https://discord.gg/QR7SARHRxK" target="_blank">Discord</a> community.\n    <br>\n    📖 Check out the GLM-4.7 <a href="https://z.ai/blog/glm-4.7" target="_blank">technical blog</a>, <a href="https://arxiv.org/abs/2508.06471" target="_blank">technical report(GLM-4.5)</a>, and <a href="https://zhipu-ai.feishu.cn/wiki/Gv3swM0Yci7w7Zke9E0crhU7n7D" target="_blank">Zhipu AI technical documentation</a>.\n    <br>\n    📍 Use GLM-4.7 API services on <a href="https://docs.z.ai/guides/llm/glm-4.7">Z.ai API Platform</a>.\n    <br>\n    👉 One click to <a href="https://chat.z.ai">GLM-4.7</a>.\n</p>\n\n## Model Introduction\n\n### GLM-4.7\n\n**GLM-4.7**, your new coding partner, is coming with the following features:\n\n- **Core Coding**: GLM-4.7 brings clear gains, compared to its predecessor GLM-4.6, in multilingual agentic coding and terminal-based tasks, including (73.8%, +5.8%) on SWE-bench, (66.7%, +12.9%) on SWE-bench Multilingual, and (41%, +16.5%) on Terminal Bench 2.0. GLM-4.7 also supports thinking before acting, with significant improvements on complex tasks in mainstream agent frameworks such as Claude Code, Kilo Code, Cline, and Roo Code.\n- **Vibe Coding**: GLM-4.7 takes a big step forward in improving UI quality. It produces cleaner, more modern webpages and generates better-looking slides with more accurate layout and sizing.\n- **Tool Using**: GLM-4.7 achieves significantly improvements in Tool using. Significant better performances can be seen on benchmarks such as τ^2-Bench and on web browsing via BrowseComp.\n- **Complex Reasoning**: GLM-4.7 delivers a substantial boost in mathematical and reasoning capabilities, achieving (42.8%, +12.4%) on the HLE (Humanity’s Last Exam) benchmark compared to GLM-4.6.\n\nMore general, one would also witness significant improvements in many other scenarios such as chat, creative writing, and role-play scenario.\n\n![bench](resources/bench_glm47.png)\n\n**Interleaved Thinking & Preserved Thinking**\n\n![thinking](resources/thinking.png)\n\nGLM-4.7 further enhances **Interleaved Thinking** (a feature introduced since GLM-4.5) and introduces **Preserved Thinking** and **Turn-level Thinking**. By thinking between actions and staying consistent across turns, it makes complex tasks more stable and more controllable:\n- **Interleaved Thinking**: The model thinks before every response and tool calling, improving instruction following and the quality of generation.\n- **Preserved Thinking**: In coding agent scenarios, the model automatically retains all thinking blocks across multi-turn conversations, reusing the existing reasoning instead of re-deriving from scratch. This reduces information loss and inconsistencies, and is well-suited for long-horizon, complex tasks.\n- **Turn-level Thinking**: The model supports per-turn control over reasoning within a session—disable thinking for lightweight requests to reduce latency/cost, enable it for complex tasks to improve accuracy and stability.\n\nMore details: https://docs.z.ai/guides/capabilities/thinking-mode\n\n### GLM-4.6\n\nCompared with GLM-4.5, **GLM-4.6**  brings several key improvements:\n\n- **Longer context window:** The context window has been expanded from 128K to 200K tokens, enabling the model to handle more complex agentic tasks.\n- **Superior coding performance:** The model achieves higher scores on code benchmarks and demonstrates better real-world performance in applications such as Claude Code、Cline、Roo Code and Kilo Code, including improvements in generating visually polished front-end pages.\n- **Advanced reasoning:** GLM-4.6 shows a clear improvement in reasoning performance and supports tool use during inference, leading to stronger overall capability.\n- **More capable agents:** GLM-4.6 exhibits stronger performance in tool using and search-based agents, and integrates more effectively within agent frameworks.\n- **Refined writing:** Better aligns with human preferences in style and readability, and performs more naturally in role-playing scenarios.\n\nWe evaluated GLM-4.6 across eight public benchmarks covering agents, reasoning, and coding. Results show clear gains over GLM-4.5, with GLM-4.6 also holding competitive advantages over leading domestic and international models such as **DeepSeek-V3.1-Terminus** and **Claude Sonnet 4**.\n\n### GLM-4.5\n\nThe **GLM-4.5** series models are foundation models designed for intelligent agents. GLM-4.5 has **355** billion total\nparameters with **32** billion active parameters, while GLM-4.5-Air adopts a more compact design with **106** billion\ntotal parameters and **12** billion active parameters. GLM-4.5 models unify reasoning, coding, and intelligent agent\ncapabilities to meet the complex demands of intelligent agent applications.\n\nBoth GLM-4.5 and GLM-4.5-Air are hybrid reasoning models that provide two modes: thinking mode for complex reasoning and\ntool usage, and non-thinking mode for immediate responses.\n\nWe have open-sourced the base models, hybrid reasoning models, and FP8 versions of the hybrid reasoning models for both\nGLM-4.5 and GLM-4.5-Air. They are released under the MIT open-source license and can be used commercially and for\nsecondary development.\n\nAs demonstrated in our comprehensive evaluation across 12 industry-standard benchmarks, GLM-4.5 achieves exceptional\nperformance with a score of **63.2**, in the **3rd** place among all the proprietary and open-source models. Notably,\nGLM-4.5-Air delivers competitive results at **59.8** while maintaining superior efficiency.\n\nFor more eval results, show cases, and technical details, please visit our [technical report](https://arxiv.org/abs/2508.06471).\n\n## Model Downloads\n\n| Model            | Download Links                                                                                                                                | Model Size | Precision |\n|------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|------------|-----------|\n| GLM-4.7          | [🤗 Hugging Face](https://huggingface.co/zai-org/GLM-4.7)<br> [🤖 ModelScope](https://modelscope.cn/models/ZhipuAI/GLM-4.7)                   | 355B-A32B  | BF16      |\n| GLM-4.7-FP8      | [🤗 Hugging Face](https://huggingface.co/zai-org/GLM-4.7-FP8)<br> [🤖 ModelScope](https://modelscope.cn/models/ZhipuAI/GLM-4.7-FP8)           | 355B-A32B  | FP8      |\n| GLM-4.6          | [🤗 Hugging Face](https://huggingface.co/zai-org/GLM-4.6)<br> [🤖 ModelScope](https://modelscope.cn/models/ZhipuAI/GLM-4.6)                   | 355B-A32B  | BF16      |\n| GLM-4.6-FP8      | [🤗 Hugging Face](https://huggingface.co/zai-org/GLM-4.6-FP8)<br> [🤖 ModelScope](https://modelscope.cn/models/ZhipuAI/GLM-4.6-FP8)           | 355B-A32B  | FP8      |\n| GLM-4.5          | [🤗 Hugging Face](https://huggingface.co/zai-org/GLM-4.5)<br> [🤖 ModelScope](https://modelscope.cn/models/ZhipuAI/GLM-4.5)                   | 355B-A32B  | BF16      |\n| GLM-4.5-Air      | [🤗 Hugging Face](https://huggingface.co/zai-org/GLM-4.5-Air)<br> [🤖 ModelScope](https://modelscope.cn/models/ZhipuAI/GLM-4.5-Air)           | 106B-A12B  | BF16      |\n| GLM-4.5-FP8      | [🤗 Hugging Face](https://huggingface.co/zai-org/GLM-4.5-FP8)<br> [🤖 ModelScope](https://modelscope.cn/models/ZhipuAI/GLM-4.5-FP8)           | 355B-A32B  | FP8       |\n| GLM-4.5-Air-FP8  | [🤗 Hugging Face](https://huggingface.co/zai-org/GLM-4.5-Air-FP8)<br> [🤖 ModelScope](https://modelscope.cn/models/ZhipuAI/GLM-4.5-Air-FP8)   | 106B-A12B  | FP8       |\n| GLM-4.5-Base     | [🤗 Hugging Face](https://huggingface.co/zai-org/GLM-4.5-Base)<br> [🤖 ModelScope](https://modelscope.cn/models/ZhipuAI/GLM-4.5-Base)         | 355B-A32B  | BF16      |\n| GLM-4.5-Air-Base | [🤗 Hugging Face](https://huggingface.co/zai-org/GLM-4.5-Air-Base)<br> [🤖 ModelScope](https://modelscope.cn/models/ZhipuAI/GLM-4.5-Air-Base) | 106B-A12B  | BF16      |\n\nThe model code, tool parser and reasoning parser can be found in the implementation\nof [transformers](https://github.com/huggingface/transformers/tree/main/src/transformers/models/glm4_moe), [vLLM](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/glm4_moe_mtp.py)\nand [SGLang](https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/models/glm4_moe.py).\n\n## System Requirements\n\n### Inference with Nvidia GPUs\n\nWe provide minimum and recommended configurations for "full-featured" model inference. The data in the table below is\nbased on the following conditions:\n\n1. All models use MTP layers and specify\n   `--speculative-num-steps 3 --speculative-eagle-topk 1 --speculative-num-draft-tokens 4` to ensure competitive\n   inference speed.\n2. The `cpu-offload` parameter is not used.\n3. Inference batch size does not exceed `8`.\n4. All are executed on devices that natively support FP8 inference, ensuring both weights and cache are in FP8 format.\n5. Server memory must exceed `1T` to ensure normal model loading and operation.\n\nThe models can run under the configurations in the table below:\n\n| Model       | Precision | GPU Type and Count   | Test Framework |\n|-------------|-----------|----------------------|----------------|\n| GLM-4.5     | BF16      | H100 x 16 / H200 x 8 | sglang         |\n| GLM-4.5     | FP8       | H100 x 8 / H200 x 4  | sglang         |\n| GLM-4.5-Air | BF16      | H100 x 4 / H200 x 2  | sglang         |\n| GLM-4.5-Air | FP8       | H100 x 2 / H200 x 1  | sglang         |\n\nUnder the configurations in the table below, the models can utilize their full 128K context length:\n\n| Model       | Precision | GPU Type and Count    | Test Framework |\n|-------------|-----------|-----------------------|----------------|\n| GLM-4.5     | BF16      | H100 x 32 / H200 x 16 | sglang         |\n| GLM-4.5     | FP8       | H100 x 16 / H200 x 8  | sglang         |\n| GLM-4.5-Air | BF16      | H100 x 8 / H200 x 4   | sglang         |\n| GLM-4.5-Air | FP8       | H100 x 4 / H200 x 2   | sglang         |\n\n### Other Devices\n\n- To perform fast inference on Ascend A3 devices using [xLLM](https://github.com/jd-opensource/xllm), please refer to the [Ascend NPU Deployment Guide](example/Ascend_NPU/README_zh.md).  \n- To run inference on AMD GPUs, please refer to the [AMD GPU Deployment Guide](example/AMD_GPU/README.md).\n\n### Fine-tuning\n\nThe code can run under the configurations in the table below\nusing [Llama Factory](https://github.com/hiyouga/LLaMA-Factory):\n\n| Model       | GPU Type and Count | Strategy | Batch Size (per GPU) |\n|-------------|--------------------|----------|----------------------|\n| GLM-4.5     | H100 x 16          | Lora     | 1                    |\n| GLM-4.5-Air | H100 x 4           | Lora     | 1                    |\n\nThe code can run under the configurations in the table below using [Swift](https://github.com/modelscope/ms-swift):\n\n| Model       | GPU Type and Count | Strategy | Batch Size (per GPU) |\n|-------------|--------------------|----------|----------------------|\n| GLM-4.5     | H20 (96GiB) x 16   | Lora     | 1                    |\n| GLM-4.5-Air | H20 (96GiB) x 4    | Lora     | 1                    |\n| GLM-4.5     | H20 (96GiB) x 128  | SFT      | 1                    |\n| GLM-4.5-Air | H20 (96GiB) x 32   | SFT      | 1                    |\n| GLM-4.5     | H20 (96GiB) x 128  | RL       | 1                    |\n| GLM-4.5-Air | H20 (96GiB) x 32   | RL       | 1                    |\n\n## Quick Start\n\nvLLM and SGLang only support GLM-4.7 on their main branches. you can use their official docker images for inference.\n\n### vLLM\n\nUsing Docker as:\n\n```shell\ndocker pull vllm/vllm-openai:nightly \n```\n\nor using pip (must use pypi.org as the index url):\n\n```shell\npip install -U vllm --pre --index-url https://pypi.org/simple --extra-index-url https://wheels.vllm.ai/nightly\n```\n\n### SGLang\n\nUsing Docker as:\n\n```shell\ndocker pull lmsysorg/sglang:dev\n```\n\nor using pip install sglang from source.\n\nFor GLM-4.6 and GLM-4.5, you can follow the configuration in `requirements.txt`.\n\n### transformers\n\nPlease refer to the `trans_infer_cli.py` code in the `inference` folder.\n\n### vLLM\n\n```shell\nvllm serve zai-org/GLM-4.7-FP8 \\\n     --tensor-parallel-size 4 \\\n     --speculative-config.method mtp \\\n     --speculative-config.num_speculative_tokens 1 \\\n     --tool-call-parser glm47 \\\n     --reasoning-parser glm45 \\\n     --enable-auto-tool-choice \\\n     --served-model-name glm-4.7-fp8\n```\n\n### SGLang\n\n```shell\npython3 -m sglang.launch_server \\\n  --model-path zai-org/GLM-4.7-FP8 \\\n  --tp-size 8 \\\n  --tool-call-parser glm47  \\\n  --reasoning-parser glm45 \\\n  --speculative-algorithm EAGLE \\\n  --speculative-num-steps 3 \\\n  --speculative-eagle-topk 1 \\\n  --speculative-num-draft-tokens 4 \\\n  --mem-fraction-static 0.8 \\\n  --served-model-name glm-4.7-fp8 \\\n  --host 0.0.0.0 \\\n  --port 8000\n```\n\n- PD-Disaggregation\n\nThe following is a simple method to implement PD-Disaggregation using a single machine with multiple GPUs, P and D each use 4 GPUs for GLM-4.5\n\n```shell\npython -m sglang.launch_server --model-path zai-org/GLM-4.5-Air  --disaggregation-mode prefill --disaggregation-ib-device mlx5_0 --tp-size 4\npython -m sglang.launch_server --model-path zai-org/GLM-4.5-Air  --disaggregation-mode decode --port 30001 --disaggregation-ib-device mlx5_0 --tp-size 4 --base-gpu-id 4                                                                                                                                                        \npython -m sglang_router.launch_router --pd-disaggregation --prefill http://127.0.0.1:30000 --decode http://127.0.0.1:30001 --host 0.0.0.0 --port 8000\n```\n\n### Parameter Instructions\n\n- For GLM-4.7, `--tool-call-parser` should be set to `glm47` in both `vLLM` and `SGLang` method.\n- For agentic tasks of GLM-4.7, please turn on [Preserved Thinking mode](https://docs.z.ai/guides/capabilities/thinking-mode) by adding the following config (only sglang support):\n  \n  ```\n    "chat_template_kwargs": {\n        "enable_thinking": true,\n        "clear_thinking": false\n    }\n    ```\n  \n- When using `vLLM` and `SGLang`, thinking mode is enabled by default when sending requests. If you want to disable the\nthinking switch, you need to add the `extra_body={"chat_template_kwargs": {"enable_thinking": False}}` parameter.\n- Both support tool calling. Please use OpenAI-style tool description format for calls.\n- For specific code, please refer to `api_request.py` in the `inference` folder.\n\n### Evaluation\n\n- For tool-integrated reasoning, please refer to [this doc](resources/glm_4.6_tir_guide.md).\n- For search benchmark, we design a specific format for searching toolcall in thinking mode to support search agent, please refer to [this](resources/trajectory_search.json). for the detailed template.\n\n## Citation\n\nIf you find our work useful in your research, please consider citing the following paper:\n\n```bibtex\n@misc{5team2025glm45agenticreasoningcoding,\n      title={GLM-4.5: Agentic, Reasoning, and Coding (ARC) Foundation Models}, \n      author={GLM Team and Aohan Zeng and Xin Lv and Qinkai Zheng and Zhenyu Hou and Bin Chen and Chengxing Xie and Cunxiang Wang and Da Yin and Hao Zeng and Jiajie Zhang and Kedong Wang and Lucen Zhong and Mingdao Liu and Rui Lu and Shulin Cao and Xiaohan Zhang and Xuancheng Huang and Yao Wei and Yean Cheng and Yifan An and Yilin Niu and Yuanhao Wen and Yushi Bai and Zhengxiao Du and Zihan Wang and Zilin Zhu and Bohan Zhang and Bosi Wen and Bowen Wu and Bowen Xu and Can Huang and Casey Zhao and Changpeng Cai and Chao Yu and Chen Li and Chendi Ge and Chenghua Huang and Chenhui Zhang and Chenxi Xu and Chenzheng Zhu and Chuang Li and Congfeng Yin and Daoyan Lin and Dayong Yang and Dazhi Jiang and Ding Ai and Erle Zhu and Fei Wang and Gengzheng Pan and Guo Wang and Hailong Sun and Haitao Li and Haiyang Li and Haiyi Hu and Hanyu Zhang and Hao Peng and Hao Tai and Haoke Zhang and Haoran Wang and Haoyu Yang and He Liu and He Zhao and Hongwei Liu and Hongxi Yan and Huan Liu and Huilong Chen and Ji Li and Jiajing Zhao and Jiamin Ren and Jian Jiao and Jiani Zhao and Jianyang Yan and Jiaqi Wang and Jiayi Gui and Jiayue Zhao and Jie Liu and Jijie Li and Jing Li and Jing Lu and Jingsen Wang and Jingwei Yuan and Jingxuan Li and Jingzhao Du and Jinhua Du and Jinxin Liu and Junkai Zhi and Junli Gao and Ke Wang and Lekang Yang and Liang Xu and Lin Fan and Lindong Wu and Lintao Ding and Lu Wang and Man Zhang and Minghao Li and Minghuan Xu and Mingming Zhao and Mingshu Zhai and Pengfan Du and Qian Dong and Shangde Lei and Shangqing Tu and Shangtong Yang and Shaoyou Lu and Shijie Li and Shuang Li and Shuang-Li and Shuxun Yang and Sibo Yi and Tianshu Yu and Wei Tian and Weihan Wang and Wenbo Yu and Weng Lam Tam and Wenjie Liang and Wentao Liu and Xiao Wang and Xiaohan Jia and Xiaotao Gu and Xiaoying Ling and Xin Wang and Xing Fan and Xingru Pan and Xinyuan Zhang and Xinze Zhang and Xiuqing Fu and Xunkai Zhang and Yabo Xu and Yandong Wu and Yida Lu and Yidong Wang and Yilin Zhou and Yiming Pan and Ying Zhang and Yingli Wang and Yingru Li and Yinpei Su and Yipeng Geng and Yitong Zhu and Yongkun Yang and Yuhang Li and Yuhao Wu and Yujiang Li and Yunan Liu and Yunqing Wang and Yuntao Li and Yuxuan Zhang and Zezhen Liu and Zhen Yang and Zhengda Zhou and Zhongpei Qiao and Zhuoer Feng and Zhuorui Liu and Zichen Zhang and Zihan Wang and Zijun Yao and Zikang Wang and Ziqiang Liu and Ziwei Chai and Zixuan Li and Zuodong Zhao and Wenguang Chen and Jidong Zhai and Bin Xu and Minlie Huang and Hongning Wang and Juanzi Li and Yuxiao Dong and Jie Tang},\n      year={2025},\n      eprint={2508.06471},\n      archivePrefix={arXiv},\n      primaryClass={cs.CL},\n      url={https://arxiv.org/abs/2508.06471}, \n}\n```\n'}

In [28]:
foundation_model.setdefault("category", "foundation model")

'foundation model'

In [29]:
examples.append(foundation_model)

In [30]:
documents_about_llm_agents = (df[df["full_name"] == "oxbshw/LLM-Agents-Ecosystem-Handbook"].iloc[0].to_dict())
print(documents_about_llm_agents)

{'full_name': 'oxbshw/LLM-Agents-Ecosystem-Handbook', 'description': 'One-stop handbook for building, deploying, and understanding LLM agents with 60+ skeletons, tutorials, ecosystem guides, and evaluation tools.', 'stars': 359, 'forks': 48, 'language': 'Python', 'url': 'https://github.com/oxbshw/LLM-Agents-Ecosystem-Handbook', 'updated_year': 2025, 'last_updated': '2025-09-08T01:59:44+00:00', 'created_year': 2025, 'created_at': '2025-09-08T01:24:26+00:00', 'watchers_count': 359, 'size': 1803, 'license': 'MIT License', 'languages': "{'Python': 95865, 'Jupyter Notebook': 1109}", 'primary_language': 'Python', 'topics': "['ai', 'ai-agent', 'ai-agents', 'fine-tuning', 'finetuning-llms', 'freamework', 'llm', 'llmops', 'local-development', 'mcp-server', 'memory', 'rag', 'rag-chatbot', 'voice-agent']", 'readme_content': '# LLM Agents & Ecosystem Handbook\n\n\n<p align="center">\n  <a href="https://awesome.re"><img src="https://awesome.re/badge.svg" alt="Awesome"></a>\n  <a href="https://github.com/oxbshw/LLM-Agents-Ecosystem-Handbook/stargazers"><img src="https://img.shields.io/github/stars/oxbshw/LLM-Agents-Ecosystem-Handbook?style=social" alt="GitHub stars"></a>\n  <a href="https://github.com/oxbshw/LLM-Agents-Ecosystem-Handbook/issues"><img src="https://img.shields.io/github/issues/oxbshw/LLM-Agents-Ecosystem-Handbook" alt="Issues"></a>\n  <a href="https://github.com/oxbshw/LLM-Agents-Ecosystem-Handbook/pulls"><img src="https://img.shields.io/github/issues-pr/oxbshw/LLM-Agents-Ecosystem-Handbook" alt="Open PRs"></a>\n  <a href="https://github.com/oxbshw/LLM-Agents-Ecosystem-Handbook/graphs/contributors"><img src="https://img.shields.io/github/contributors/oxbshw/LLM-Agents-Ecosystem-Handbook" alt="Contributors"></a>\n  <a href="LICENSE"><img src="https://img.shields.io/badge/License-MIT-green.svg" alt="MIT License"></a>\n  <a href="https://github.com/oxbshw/LLM-Agents-Ecosystem-Handbook/commits/main"><img src="https://img.shields.io/github/last-commit/oxbshw/LLM-Agents-Ecosystem-Handbook" alt="Last commit"></a>\n</p>\n\n<p align="center"><strong>A unified handbook for building, deploying and understanding LLM agents and the wider ecosystem</strong></p>\n\nA polished, curated collection of **Large Language Model (LLM) agents**, tutorials and ecosystem insights. This handbook highlights projects that push the boundaries of generative AI, multi-agent collaboration, retrieval-augmented generation (RAG), voice and game agents, and more. It goes beyond simple link aggregation, aiming to be a one-stop reference for building, deploying, and understanding LLM applications across the entire stack.\n\n> **Tip:** If you enjoy this list, please consider starring the repository to help others discover it!\n\n---\n\n## Table of Contents\n\n- [Top Agent Frameworks](#top-agent-frameworks)\n- [Agent Toolkits & Platforms](#agent-toolkits--platforms)\n- [Starter AI Agents](#starter-ai-agents)\n- [Advanced AI & Domain-Specific Agents](#advanced-ai--domain-specific-agents)\n- [Multi-Agent Teams](#multi-agent-teams)\n- [Voice & Game Agents](#voice--game-agents)\n- [RAG & Memory Examples](#rag--memory-examples)\n- [MCP Agent Integrations](#mcp-agent-integrations)\n- [LLM Evaluation Frameworks](#llm-evaluation-frameworks)\n- [Example Projects](#example-projects)\n- [Tutorials & Learning Resources](#tutorials--learning-resources)\n  - [RAG Tutorials](#rag-tutorials)\n  - [Memory Apps Tutorials](#memory-apps-tutorials)\n  - [Chat with X Tutorials](#chat-with-x-tutorials)\n  - [LLM Fine-Tuning Tutorials](#llm-fine-tuning-tutorials)\n- [Other Educational Spaces](#other-educational-spaces)\n- [Unique Features](#unique-features)\n- [Languages & Multilingual Support](#languages--multilingual-support)\n- [Interactive Demos & Resources](#interactive-demos--resources)\n  - [Web Apps](#web-apps)\n  - [Jupyter Notebooks](#jupyter-notebooks)\n- [Datasets & Design Assets](#datasets--design-assets)\n- [Documentation & Roadmap](#documentation--roadmap)\n- [Complete Applications](#complete-applications)\n- [Beginner’s Guide](#beginners-guide)\n- [Contributing](#contributing)\n- [License](#license)\n- [Maintainer](#maintainer)\n\n---\n\n## Why this repository stands out\n\nThis curated collection aims to be a **comprehensive resource** for developers and researchers building their own LLM applications. In addition to code examples, it provides:\n\n- **Comparative analysis of leading agent frameworks:** A quick matrix contrasting frameworks (LangGraph, AutoGen, CrewAI, Smolagents, etc.) with key features to help you choose.\n- **Guidance on framework selection:** Practical advice based on task complexity, collaboration needs and ecosystem integrations.\n- **LLM evaluation toolbox:** Summaries of tools like Promptfoo, DeepEval, MLflow LLM Evaluate, RAGAs and Langfuse to measure performance and safety.\n- **60+ skeleton projects:** The `agents` folder contains scaffolded agents across many domains (blogging, medical imaging, music generation, multimodal input, news, finance, research, scraping, consultancy, system design, compliance, marketing, scheduling, supply-chain, healthcare, education). Each skeleton includes a `README.md` and `main.py`.\n- **Agent skeleton generator:** [`scripts/create_agent.py`](scripts/create_agent.py) to spin up new agent skeletons in seconds.\n\n---\n\n## Top Agent Frameworks\n\n| Framework | Description & Key Features |\n|---|---|\n| **LangGraph** | Graph/DAG-based orchestration for complex multi-step workflows. |\n| **OpenAI Agents SDK** | Structured runtime with tool-calling and role-based agents. |\n| **AutoGen (AG2)** | Event-driven multi-agent conversations and human-in-the-loop. |\n| **CrewAI** | Role-based “crew” collaboration with memory and error handling. |\n| **Google AgentKit (ADK)** | Modular Gemini/Vertex AI agent kit with hierarchical tools. |\n| **Dify** | Low-code builder with RAG and function calling. |\n| **LangChain & Tools** | Mature chains, memory and 3rd-party integrations. |\n| **Smolagents** | Minimal, code-centric loop (agents write & execute code). |\n| **Semantic Kernel** | .NET-first skills/plans; enterprise-friendly. |\n| **LlamaIndex Agents** | Retrieval-focused agents for data-heavy apps. |\n| **Strands Agents** | Provider-agnostic SDK with OpenTelemetry. |\n| **Pydantic AI** | Type-safe IO/tool signatures with great DX. |\n\n---\n\n## Agent Toolkits & Platforms\n\n| Project | Description |\n|---|---|\n| **AutoGPT** | Toolkit for autonomous agents (creation, benchmarking, UI/CLI). |\n| **Ollama** | Run LLMs locally across macOS/Windows/Linux/Docker. |\n| **Lobe Chat** | Open-source chat UI with plugins and multimodal support. |\n| **OpenDevin** | Open initiative towards an AI software engineer. |\n| **Open Interpreter** | Natural-language coding & local computer control. |\n| **MetaGPT** | Multi-agent “virtual company” for complex tasks. |\n| **PrivateGPT** | Secure offline Q&A over your documents. |\n| **GPT-Engineer** | From natural-language spec to code. |\n| **LlamaIndex Tools** | Connectors/tools for data agents. |\n| **Flowise** | Drag-and-drop builder for LLM workflows. |\n| **FastChat** | Train/serve/evaluate chatbots. |\n| **Mem0** | Memory layer for personalised LLMs. |\n| **Cal.ai** | Scheduling assistant with email handling. |\n| **Aider** | CLI pair-programming agent with Git integration. |\n| **Jan** | Offline ChatGPT-style desktop app. |\n\n---\n\n## Starter AI Agents\n\n| Agent | Description |\n|---|---|\n| **AI Blog to Podcast Agent** | Convert blog posts into podcasts. |\n| **AI Data Analysis Agent** | Insights from CSV/structured data. |\n| **AI Travel Agent** | Trip itineraries (local/cloud). |\n| **AI Music Generator** | Compose via generative models. |\n| **AI Meme Generator (Browser)** | Creates memes by overlaying captions on images. |\n| **AI Breakup Recovery Agent** | Supportive advice for emotional situations. |\n| **AI Health & Fitness Agent** | Health metrics & coaching. |\n| **Gemini Multimodal Agent** | Text+image multimodal demo. |\n\n---\n\n## Advanced AI & Domain-Specific Agents\n\n| Agent | Description |\n|---|---|\n| **AI Deep Research Agent** | Multi-source research & synthesis. |\n| **AI Consultant Agent** | Domain-expert strategy & advice. |\n| **AI System Architect Agent** | From requirements to architecture. |\n| **AI Lead Generation Agent** | Identify & qualify prospects. |\n| **AI Meeting Agent** | Summaries & action items. |\n| **OpenAI Research Agent** | Research workflows with tools. |\n| **Explainable AI Finance Agent** | Finance with interpretability. |\n| **Web Scraping Agent** | Crawl & extract structured data. |\n| **Document Processing Agent** | OCR + analysis/summarisation. |\n| **Sentiment Analysis Agent** | Classify sentiment at scale. |\n| **Technical Translation Agent** | Preserve domain terminology. |\n| **Research Synthesizer Agent** | RAG + coherent reporting. |\n\n---\n\n## Multi-Agent Teams\n\n| Team | Description |\n|---|---|\n| **Competitor Intelligence Team** | Market/competitor research & reporting. |\n| **Finance Agent Team** | Budgeting, forecasting and reporting. |\n| **Teaching Agent Team** | Lesson planning, delivery and assessment. |\n| **Multi-Agent Team Demo** | Cross-role collaboration patterns. |\n| **Mixture of Agents Demo** | Specialised agent ensembles. |\n\n---\n\n## Voice & Game Agents\n\n| Agent | Description |\n|---|---|\n| **Voice Summary Agent** | Transcribe and summarise audio. |\n| **AI Audio Tour Agent** | Generate audio tours for museums/cities. |\n| **Customer Support Voice Agent** | Handle spoken queries and log issues. |\n| **Voice RAG Agent** | Voice input + retrieval + TTS. |\n| **Tic-Tac-Toe Agent** | Autonomous gameplay template. |\n\n---\n\n## RAG & Memory Examples\n\n| Example | Description |\n|---|---|\n| **Agentic RAG with Reasoning** | Retrieval → reasoning → generation. |\n| **Hybrid Search RAG** | Vector + keyword retrieval. |\n| **Vision RAG** | Apply RAG to visual data. |\n| **CRAG (Corrective RAG)** | Human-feedback corrective loop. |\n| **Local RAG Agent** | Fully offline retrieval pipeline. |\n\n---\n\n## MCP Agent Integrations\n\n| Agent | Description |\n|---|---|\n| **Browser MCP Agent** | Drive a browser (search/click/forms). |\n| **GitHub MCP Agent** | Read/write/manage repositories. |\n| **Notion MCP Agent** | Create/update/query Notion pages & DBs. |\n| **Travel Planner MCP Agent Team** | Multi-agent trip planning via MCP. |\n\n---\n\n## LLM Evaluation Frameworks\n\nSee [`evaluation_frameworks/README.md`](evaluation_frameworks/README.md) for details about Promptfoo, DeepEval, MLflow LLM Evaluate, RAGAs, Deepchecks, LangSmith, TruLens, Arize Phoenix and Langfuse.\n\n---\n\n## Example Projects\n\nThe `agents` directory contains many **agent skeletons** organised by category. Category folders (`starter`, `advanced`, `teams`, `rag`) act as **indexes**, while each agent lives in its own top-level folder under `agents/`.\n\n### Quick picks\n\n- **Summarization Agent** – [agents/summarization_agent](agents/summarization_agent)  \n- **Data Analysis Agent** – [agents/data_analysis_agent](agents/data_analysis_agent)  \n- **Travel Itinerary Agent** – [agents/travel_itinerary_agent](agents/travel_itinerary_agent)  \n- **Voice Assistant Demo** – [agents/voice_agent_demo](agents/voice_agent_demo)  \n- **Meme Generator Agent** – [agents/meme_generator_agent](agents/meme_generator_agent)  \n- **Health & Fitness Agent** – [agents/health_fitness_agent](agents/health_fitness_agent)  \n- **Breakup Recovery Agent** – [agents/breakup_recovery_agent](agents/breakup_recovery_agent)  \n- **AI Blog to Podcast Agent** – [agents/ai_blog_to_podcast_agent](agents/ai_blog_to_podcast_agent)  \n- **AI Medical Imaging Agent** – [agents/ai_medical_imaging_agent](agents/ai_medical_imaging_agent)  \n- **AI Music Generator Agent** – [agents/ai_music_generator_agent](agents/ai_music_generator_agent)  \n- **Local News Agent** – [agents/local_news_agent](agents/local_news_agent)  \n- **Gemini Multimodal Demo** – [agents/gemini_multimodal_agent_demo](agents/gemini_multimodal_agent_demo)\n\n---\n\n## Tutorials & Learning Resources\n\nHands-on tutorials live in [`tutorials/`](tutorials) directory.\n\n- **RAG Tutorials** → [`tutorials/rag_tutorials`](tutorials/rag_tutorials)  \n- **Memory Apps Tutorials** → [`tutorials/memory_apps`](tutorials/memory_apps)  \n- **Chat with X Tutorials** → [`tutorials/chat_with_x_tutorials`](tutorials/chat_with_x_tutorials)  \n- **Fine-Tuning Tutorials** → [`tutorials/fine_tuning_tutorials`](tutorials/fine_tuning_tutorials)\n\n---\n\n## Other Educational Spaces\n\n- **Interactive demos & notebooks:** [`web_apps`](web_apps), [`notebooks`](notebooks)  \n- **Datasets & design assets:** [`datasets`](datasets), [`design`](design)  \n- **LLM ecosystem overview:** [`ecosystem/overview.md`](ecosystem/overview.md)  \n- **Complete applications:** [`complete_apps`](complete_apps)\n\n---\n\n## Unique Features\n\n- **Educational focus:** Detailed tutorials (RAG, memory, chat with X, fine-tuning) + 60+ scaffolded agents.  \n- **Framework comparison & guidance:** Practical, vendor-neutral advice.  \n- **Agent skeleton generator:** `scripts/create_agent.py`.  \n- **Evaluation toolbox:** Promptfoo, DeepEval, RAGAs, etc.  \n- **Ecosystem breadth:** Training, tools, production, local inference, operations, interpretability.  \n- **Community roadmap:** See [`docs/roadmap.md`](docs/roadmap.md).  \n\n---\n\n## Languages & Multilingual Support\n\nWe welcome translations. See [`TRANSLATION.md`](TRANSLATION.md). A **Technical Translation Agent** exists under `agents/technical_translation_agent`.\n\n---\n\n## Interactive Demos & Resources\n\n### Web Apps\n\n- **Streamlit Summariser** – [`web_apps/streamlit_summarizer`](web_apps/streamlit_summarizer)  \n- **Gradio FAQ Bot** – [`web_apps/gradio_faq_bot`](web_apps/gradio_faq_bot)\n\n### Jupyter Notebooks\n\n- **Getting Started** – [`notebooks/getting_started.ipynb`](notebooks/getting_started.ipynb)\n\n---\n\n## Datasets & Design Assets\n\n- **Sample dataset** – [`datasets/sample_products.csv`](datasets/sample_products.csv) (+ [`datasets/README.md`](datasets/README.md))  \n- **Architecture diagram** – [`design/architecture_diagram.png`](design/architecture_diagram.png) (+ [`design/README.md`](design/README.md))\n\n---\n\n## Documentation & Roadmap\n\n- **Best practices** – [`docs/best_practices.md`](docs/best_practices.md)  \n- **Framework comparison** – [`docs/framework_comparison.md`](docs/framework_comparison.md)  \n- **Evaluation frameworks guide** – [`evaluation_frameworks/README.md`](evaluation_frameworks/README.md)  \n- **Quickstart** – [`tutorials/quickstart.md`](tutorials/quickstart.md)  \n- **Roadmap** – [`docs/roadmap.md`](docs/roadmap.md)  \n- **Changelog** – [`CHANGELOG.md`](CHANGELOG.md)\n\n---\n\n## Complete Applications\n\n- **Task Planner** – [`complete_apps/task_planner`](complete_apps/task_planner)  \n- **Health Coach** – [`complete_apps/health_coach`](complete_apps/health_coach)\n\n---\n\n## Beginner’s Guide\n\nIf you’re new to LLMs, start here → [`docs/beginners_guide.md`](docs/beginners_guide.md)\n\n---\n\n## Contributing\n\nContributions are welcome! Please open an issue or PR. Ensure new entries are permissively licensed (MIT/Apache-2.0) and well-documented.\n\n---\n\n## License\n\nMIT — see [LICENSE](LICENSE).\n\n---\n\n## Maintainer\n\nCurated & maintained by **Sayed Allam** ([oxbshw](https://github.com/oxbshw)). If you find this helpful, please ⭐ star the repo and share feedback via issues/PRs.\n'}

In [31]:
documents_about_llm_agents.setdefault("category", "documents about llm agents")
examples.append(documents_about_llm_agents)

In [32]:
collection_of_llm_agent_projects = (df[df["full_name"] == "Shubhamsaboo/awesome-llm-apps"].iloc[0].to_dict())
print(collection_of_llm_agent_projects)

{'full_name': 'Shubhamsaboo/awesome-llm-apps', 'description': 'Collection of awesome LLM apps with AI Agents and RAG using OpenAI, Anthropic, Gemini and opensource models.', 'stars': 87393, 'forks': 12474, 'language': 'Python', 'url': 'https://github.com/Shubhamsaboo/awesome-llm-apps', 'updated_year': 2026, 'last_updated': '2026-01-07T03:39:42+00:00', 'created_year': 2024, 'created_at': '2024-04-29T05:30:25+00:00', 'watchers_count': 87393, 'size': 193688, 'license': 'Apache License 2.0', 'languages': "{'Python': 2295887, 'JavaScript': 835003, 'TypeScript': 204202, 'HTML': 32350, 'CSS': 8864, 'PLpgSQL': 3012, 'Dockerfile': 1506, 'Shell': 621}", 'primary_language': 'Python', 'topics': "['llms', 'rag', 'python']", 'readme_content': '<p align="center">\n  <a href="http://www.theunwindai.com">\n    <img src="docs/banner/unwind_black.png" width="900px" alt="Unwind AI">\n  </a>\n</p>\n\n<p align="center">\n  <a href="https://www.linkedin.com/in/shubhamsaboo/">\n    <img src="https://img.shields.io/badge/-Follow%20Shubham%20Saboo-blue?logo=linkedin&style=flat-square" alt="LinkedIn">\n  </a>\n  <a href="https://twitter.com/Saboo_Shubham_">\n    <img src="https://img.shields.io/twitter/follow/Shubham_Saboo" alt="Twitter">\n  </a>\n</p>\n\n<p align="center">\n  <!-- Keep these links. Translations will automatically update with the README. -->\n  <a href="https://www.readme-i18n.com/Shubhamsaboo/awesome-llm-apps?lang=de">Deutsch</a> | \n  <a href="https://www.readme-i18n.com/Shubhamsaboo/awesome-llm-apps?lang=es">Español</a> | \n  <a href="https://www.readme-i18n.com/Shubhamsaboo/awesome-llm-apps?lang=fr">français</a> | \n  <a href="https://www.readme-i18n.com/Shubhamsaboo/awesome-llm-apps?lang=ja">日本語</a> | \n  <a href="https://www.readme-i18n.com/Shubhamsaboo/awesome-llm-apps?lang=ko">한국어</a> | \n  <a href="https://www.readme-i18n.com/Shubhamsaboo/awesome-llm-apps?lang=pt">Português</a> | \n  <a href="https://www.readme-i18n.com/Shubhamsaboo/awesome-llm-apps?lang=ru">Русский</a> | \n  <a href="https://www.readme-i18n.com/Shubhamsaboo/awesome-llm-apps?lang=zh">中文</a>\n</p>\n\n<hr/>\n\n# 🌟 Awesome LLM Apps\n\nA curated collection of **Awesome LLM apps built with RAG, AI Agents, Multi-agent Teams, MCP, Voice Agents, and more.** This repository features LLM apps that use models from <img src="https://cdn.simpleicons.org/openai"  alt="openai logo" width="25" height="15">**OpenAI** , <img src="https://cdn.simpleicons.org/anthropic"  alt="anthropic logo" width="25" height="15">**Anthropic**, <img src="https://cdn.simpleicons.org/googlegemini"  alt="google logo" width="25" height="18">**Google**, <img src="https://cdn.simpleicons.org/x"  alt="X logo" width="25" height="15">**xAI** and open-source models like <img src="https://cdn.simpleicons.org/alibabacloud"  alt="alibaba logo" width="25" height="15">**Qwen** or  <img src="https://cdn.simpleicons.org/meta"  alt="meta logo" width="25" height="15">**Llama** that you can run locally on your computer.\n\n<p align="center">\n  <a href="https://trendshift.io/repositories/9876" target="_blank">\n    <img src="https://trendshift.io/api/badge/repositories/9876" alt="Shubhamsaboo%2Fawesome-llm-apps | Trendshift" style="width: 250px; height: 55px;" />\n  </a>\n</p>\n\n## 🤔 Why Awesome LLM Apps?\n\n- 💡 Discover practical and creative ways LLMs can be applied across different domains, from code repositories to email inboxes and more.\n- 🔥 Explore apps that combine LLMs from OpenAI, Anthropic, Gemini, and open-source alternatives with AI Agents, Agent Teams, MCP & RAG.\n- 🎓 Learn from well-documented projects and contribute to the growing open-source ecosystem of LLM-powered applications.\n\n## 🙏 Thanks to our sponsors\n\n<table align="center" cellpadding="16" cellspacing="12">\n  <tr>\n    <td align="center">\n      <a href="https://tsdb.co/shubham-gh" target="_blank" rel="noopener" title="Tiger Data">\n        <img src="docs/banner/sponsors/tigerdata.png" alt="Tiger Data" width="500">\n      </a>\n      <br>\n      <a href="https://tsdb.co/shubham-gh" target="_blank" rel="noopener" style="text-decoration: none; color: #333; font-weight: bold; font-size: 18px;">\n        Tiger Data MCP\n      </a>\n    </td>\n    <td align="center">\n      <a href="https://github.com/speechmatics/speechmatics-academy" target="_blank" rel="noopener" title="Speechmatics">\n        <img src="docs/banner/sponsors/speechmatics.png" alt="Speechmatics" width="500">\n      </a>\n      <br>\n      <a href="https://github.com/speechmatics/speechmatics-academy" target="_blank" rel="noopener" style="text-decoration: none; color: #333; font-weight: bold; font-size: 18px;">\n        Speechmatics\n      </a>\n    </td>\n  </tr>\n  <tr>\n    <td align="center">\n      <a href="https://okara.ai/?utm_source=oss&utm_medium=sponsorship&utm_campaign=awesome-llm-apps" title="Okara">\n        <img src="docs/banner/sponsors/okara.png" alt="Okara" width="500">\n      </a>\n      <br>\n      <a href="https://okara.ai/?utm_source=oss&utm_medium=sponsorship&utm_campaign=awesome-llm-apps" style="text-decoration: none; color: #333; font-weight: bold; font-size: 18px;">\n        Okara AI\n      </a>\n    </td>\n    <td align="center">\n      <a href="https://sponsorunwindai.com/" title="Become a Sponsor">\n        <img src="docs/banner/sponsor_awesome_llm_apps.png" alt="Become a Sponsor" width="500">\n      </a>\n      <br>\n      <a href="https://sponsorunwindai.com/" style="text-decoration: none; color: #333; font-weight: bold; font-size: 18px;">\n        Become a Sponsor\n      </a>\n    </td>\n  </tr>\n</table>\n\n## 📂 Featured AI Projects\n\n### AI Agents\n\n### 🌱 Starter AI Agents\n\n*   [🎙️ AI Blog to Podcast Agent](starter_ai_agents/ai_blog_to_podcast_agent/)\n*   [❤️\u200d🩹 AI Breakup Recovery Agent](starter_ai_agents/ai_breakup_recovery_agent/)\n*   [📊 AI Data Analysis Agent](starter_ai_agents/ai_data_analysis_agent/)\n*   [🩻 AI Medical Imaging Agent](starter_ai_agents/ai_medical_imaging_agent/)\n*   [😂 AI Meme Generator Agent (Browser)](starter_ai_agents/ai_meme_generator_agent_browseruse/)\n*   [🎵 AI Music Generator Agent](starter_ai_agents/ai_music_generator_agent/)\n*   [🛫 AI Travel Agent (Local & Cloud)](starter_ai_agents/ai_travel_agent/)\n*   [✨ Gemini Multimodal Agent](starter_ai_agents/gemini_multimodal_agent_demo/)\n*   [🔄 Mixture of Agents](starter_ai_agents/mixture_of_agents/)\n*   [📊 xAI Finance Agent](starter_ai_agents/xai_finance_agent/)\n*   [🔍 OpenAI Research Agent](starter_ai_agents/opeani_research_agent/)\n*   [🕸️ Web Scraping AI Agent (Local & Cloud SDK)](starter_ai_agents/web_scrapping_ai_agent/)\n\n### 🚀 Advanced AI Agents\n*   [🏚️ 🍌 AI Home Renovation Agent with Nano Banana Pro](advanced_ai_agents/multi_agent_apps/ai_home_renovation_agent)\n*   [🔍 AI Deep Research Agent](advanced_ai_agents/single_agent_apps/ai_deep_research_agent/)\n*   [📊 AI VC Due Diligence Agent Team](advanced_ai_agents/multi_agent_apps/agent_teams/ai_vc_due_diligence_agent_team)\n*   [🔬 AI Research Planner & Executor (Google Interactions API)](advanced_ai_agents/single_agent_apps/research_agent_gemini_interaction_api)\n*   [🤝 AI Consultant Agent](advanced_ai_agents/single_agent_apps/ai_consultant_agent)\n*   [🏗️ AI System Architect Agent](advanced_ai_agents/single_agent_apps/ai_system_architect_r1/)\n*   [💰 AI Financial Coach Agent](advanced_ai_agents/multi_agent_apps/ai_financial_coach_agent/)\n*   [🎬 AI Movie Production Agent](advanced_ai_agents/single_agent_apps/ai_movie_production_agent/)\n*   [📈 AI Investment Agent](advanced_ai_agents/single_agent_apps/ai_investment_agent/)\n*   [🏋️\u200d♂️ AI Health & Fitness Agent](advanced_ai_agents/single_agent_apps/ai_health_fitness_agent/)\n*   [🚀 AI Product Launch Intelligence Agent](advanced_ai_agents/multi_agent_apps/product_launch_intelligence_agent)\n*   [🗞️ AI Journalist Agent](advanced_ai_agents/single_agent_apps/ai_journalist_agent/)\n*   [🧠 AI Mental Wellbeing Agent](advanced_ai_agents/multi_agent_apps/ai_mental_wellbeing_agent/)\n*   [📑 AI Meeting Agent](advanced_ai_agents/single_agent_apps/ai_meeting_agent/)\n*   [🧬 AI Self-Evolving Agent](advanced_ai_agents/multi_agent_apps/ai_Self-Evolving_agent/)\n*   [👨🏻\u200d💼 AI Sales Intelligence Agent Team](advanced_ai_agents/multi_agent_apps/agent_teams/ai_sales_intelligence_agent_team)\n*   [🎧 AI Social Media News and Podcast Agent](advanced_ai_agents/multi_agent_apps/ai_news_and_podcast_agents/)\n\n### 🎮 Autonomous Game Playing Agents\n\n*   [🎮 AI 3D Pygame Agent](advanced_ai_agents/autonomous_game_playing_agent_apps/ai_3dpygame_r1/)\n*   [♜ AI Chess Agent](advanced_ai_agents/autonomous_game_playing_agent_apps/ai_chess_agent/)\n*   [🎲 AI Tic-Tac-Toe Agent](advanced_ai_agents/autonomous_game_playing_agent_apps/ai_tic_tac_toe_agent/)\n\n### 🤝 Multi-agent Teams\n\n*   [🧲 AI Competitor Intelligence Agent Team](advanced_ai_agents/multi_agent_apps/agent_teams/ai_competitor_intelligence_agent_team/)\n*   [💲 AI Finance Agent Team](advanced_ai_agents/multi_agent_apps/agent_teams/ai_finance_agent_team/)\n*   [🎨 AI Game Design Agent Team](advanced_ai_agents/multi_agent_apps/agent_teams/ai_game_design_agent_team/)\n*   [👨\u200d⚖️ AI Legal Agent Team (Cloud & Local)](advanced_ai_agents/multi_agent_apps/agent_teams/ai_legal_agent_team/)\n*   [💼 AI Recruitment Agent Team](advanced_ai_agents/multi_agent_apps/agent_teams/ai_recruitment_agent_team/)\n*   [🏠 AI Real Estate Agent Team](advanced_ai_agents/multi_agent_apps/agent_teams/ai_real_estate_agent_team)\n*   [👨\u200d💼 AI Services Agency (CrewAI)](advanced_ai_agents/multi_agent_apps/agent_teams/ai_services_agency/)\n*   [👨\u200d🏫 AI Teaching Agent Team](advanced_ai_agents/multi_agent_apps/agent_teams/ai_teaching_agent_team/)\n*   [💻 Multimodal Coding Agent Team](advanced_ai_agents/multi_agent_apps/agent_teams/multimodal_coding_agent_team/)\n*   [✨ Multimodal Design Agent Team](advanced_ai_agents/multi_agent_apps/agent_teams/multimodal_design_agent_team/)\n*   [🎨 🍌 Multimodal UI/UX Feedback Agent Team with Nano Banana](advanced_ai_agents/multi_agent_apps/agent_teams/multimodal_uiux_feedback_agent_team/)\n*   [🌏 AI Travel Planner Agent Team](/advanced_ai_agents/multi_agent_apps/agent_teams/ai_travel_planner_agent_team/)\n\n### 🗣️ Voice AI Agents\n\n*   [🗣️ AI Audio Tour Agent](voice_ai_agents/ai_audio_tour_agent/)\n*   [📞 Customer Support Voice Agent](voice_ai_agents/customer_support_voice_agent/)\n*   [🔊 Voice RAG Agent (OpenAI SDK)](voice_ai_agents/voice_rag_openaisdk/)\n*   [🎙️ OpenSource Voice Dictation Agent (like Wispr Flow](https://github.com/akshayaggarwal99/jarvis-ai-assistant)\n\n### <img src="https://cdn.simpleicons.org/modelcontextprotocol"  alt="mcp logo" width="25" height="20"> MCP AI Agents \n\n*   [♾️ Browser MCP Agent](mcp_ai_agents/browser_mcp_agent/)\n*   [🐙 GitHub MCP Agent](mcp_ai_agents/github_mcp_agent/)\n*   [📑 Notion MCP Agent](mcp_ai_agents/notion_mcp_agent) \n*   [🌍 AI Travel Planner MCP Agent](mcp_ai_agents/ai_travel_planner_mcp_agent_team)\n\n### 📀 RAG (Retrieval Augmented Generation)\n*   [🔥 Agentic RAG with Embedding Gemma](rag_tutorials/agentic_rag_embedding_gemma)\n*   [🧐 Agentic RAG with Reasoning](rag_tutorials/agentic_rag_with_reasoning/)\n*   [📰 AI Blog Search (RAG)](rag_tutorials/ai_blog_search/)\n*   [🔍 Autonomous RAG](rag_tutorials/autonomous_rag/)\n*   [🔄 Contextual AI RAG Agent](rag_tutorials/contextualai_rag_agent/)\n*   [🔄 Corrective RAG (CRAG)](rag_tutorials/corrective_rag/)\n*   [🐋 Deepseek Local RAG Agent](rag_tutorials/deepseek_local_rag_agent/)\n*   [🤔 Gemini Agentic RAG](rag_tutorials/gemini_agentic_rag/)\n*   [👀 Hybrid Search RAG (Cloud)](rag_tutorials/hybrid_search_rag/)\n*   [🔄 Llama 3.1 Local RAG](rag_tutorials/llama3.1_local_rag/)\n*   [🖥️ Local Hybrid Search RAG](rag_tutorials/local_hybrid_search_rag/)\n*   [🦙 Local RAG Agent](rag_tutorials/local_rag_agent/)\n*   [🧩 RAG-as-a-Service](rag_tutorials/rag-as-a-service/)\n*   [✨ RAG Agent with Cohere](rag_tutorials/rag_agent_cohere/)\n*   [⛓️ Basic RAG Chain](rag_tutorials/rag_chain/)\n*   [📠 RAG with Database Routing](rag_tutorials/rag_database_routing/)\n*   [🖼️ Vision RAG](rag_tutorials/vision_rag/)\n\n### 💾 LLM Apps with Memory Tutorials\n\n*   [💾 AI ArXiv Agent with Memory](advanced_llm_apps/llm_apps_with_memory_tutorials/ai_arxiv_agent_memory/)\n*   [🛩️ AI Travel Agent with Memory](advanced_llm_apps/llm_apps_with_memory_tutorials/ai_travel_agent_memory/)\n*   [💬 Llama3 Stateful Chat](advanced_llm_apps/llm_apps_with_memory_tutorials/llama3_stateful_chat/)\n*   [📝 LLM App with Personalized Memory](advanced_llm_apps/llm_apps_with_memory_tutorials/llm_app_personalized_memory/)\n*   [🗄️ Local ChatGPT Clone with Memory](advanced_llm_apps/llm_apps_with_memory_tutorials/local_chatgpt_with_memory/)\n*   [🧠 Multi-LLM Application with Shared Memory](advanced_llm_apps/llm_apps_with_memory_tutorials/multi_llm_memory/)\n\n\n### 💬 Chat with X Tutorials\n\n*   [💬 Chat with GitHub (GPT & Llama3)](advanced_llm_apps/chat_with_X_tutorials/chat_with_github/)\n*   [📨 Chat with Gmail](advanced_llm_apps/chat_with_X_tutorials/chat_with_gmail/)\n*   [📄 Chat with PDF (GPT & Llama3)](advanced_llm_apps/chat_with_X_tutorials/chat_with_pdf/)\n*   [📚 Chat with Research Papers (ArXiv) (GPT & Llama3)](advanced_llm_apps/chat_with_X_tutorials/chat_with_research_papers/)\n*   [📝 Chat with Substack](advanced_llm_apps/chat_with_X_tutorials/chat_with_substack/)\n*   [📽️ Chat with YouTube Videos](advanced_llm_apps/chat_with_X_tutorials/chat_with_youtube_videos/)\n\n### 🎯 LLM Optimization Tools\n\n*   [🎯 Toonify Token Optimization](advanced_llm_apps/llm_optimization_tools/toonify_token_optimization/) - Reduce LLM API costs by 30-60% using TOON format\n\n### 🔧 LLM Fine-tuning Tutorials\n\n* <img src="https://cdn.simpleicons.org/google"  alt="google logo" width="20" height="15"> [Gemma 3 Fine-tuning](advanced_llm_apps/llm_finetuning_tutorials/gemma3_finetuning/)\n* <img src="https://cdn.simpleicons.org/meta"  alt="meta logo" width="25" height="15"> [Llama 3.2 Fine-tuning](advanced_llm_apps/llm_finetuning_tutorials/llama3.2_finetuning/)\n\n\n### 🧑\u200d🏫 AI Agent Framework Crash Course\n\n<img src="https://cdn.simpleicons.org/google"  alt="google logo" width="25" height="15"> [Google ADK Crash Course](ai_agent_framework_crash_course/google_adk_crash_course/)\n  - Starter agent; model‑agnostic (OpenAI, Claude)\n  - Structured outputs (Pydantic)\n  - Tools: built‑in, function, third‑party, MCP tools\n  - Memory; callbacks; Plugins\n  - Simple multi‑agent; Multi‑agent patterns\n\n<img src="https://cdn.simpleicons.org/openai"  alt="openai logo" width="25" height="15"> [OpenAI Agents SDK Crash Course](ai_agent_framework_crash_course/openai_sdk_crash_course/)\n  - Starter agent; function calling; structured outputs\n  - Tools: built‑in, function, third‑party integrations\n  - Memory; callbacks; evaluation\n  - Multi‑agent patterns; agent handoffs\n  - Swarm orchestration; routing logic\n\n## 🚀 Getting Started\n\n1. **Clone the repository** \n\n    ```bash \n    git clone https://github.com/Shubhamsaboo/awesome-llm-apps.git \n    ```\n\n2. **Navigate to the desired project directory**\n\n    ```bash \n    cd awesome-llm-apps/starter_ai_agents/ai_travel_agent\n    ```\n\n3. **Install the required dependencies**\n\n    ```bash\n    pip install -r requirements.txt\n    ```\n\n4. **Follow the project-specific instructions** in each project\'s `README.md` file to set up and run the app.\n\n\n### <img src="https://cdn.simpleicons.org/github"  alt="github logo" width="25" height="20"> Thank You, Community, for the Support! 🙏\n\n[![Star History Chart](https://api.star-history.com/svg?repos=Shubhamsaboo/awesome-llm-apps&type=Date)](https://star-history.com/#Shubhamsaboo/awesome-llm-apps&Date)\n\n🌟 **Don’t miss out on future updates! Star the repo now and be the first to know about new and exciting LLM apps with RAG and AI Agents.**\n'}

In [33]:
collection_of_llm_agent_projects.setdefault("category", "collection of llm agent projects")
examples.append(collection_of_llm_agent_projects)

In [34]:
collection_of_datasets = (df[df["full_name"] == "fangyuan-ksgk/RuleAlign"].iloc[0].to_dict())
print(collection_of_datasets)

{'full_name': 'fangyuan-ksgk/RuleAlign', 'description': 'Rule-Based Adherance evaluation for LLM Agent', 'stars': 3, 'forks': 0, 'language': 'Python', 'url': 'https://github.com/fangyuan-ksgk/RuleAlign', 'updated_year': 2024, 'last_updated': '2024-09-02T02:31:10+00:00', 'created_year': 2024, 'created_at': '2024-08-18T09:35:56+00:00', 'watchers_count': 3, 'size': 133, 'license': nan, 'languages': "{'Python': 23146, 'Jupyter Notebook': 3432, 'Shell': 350}", 'primary_language': 'Python', 'topics': '[]', 'readme_content': '<div align="center">\n<h2 align="center">\n   <b>RuleAlign Dataset</b>\n</h2>\n<div>\n<a target="_blank" href="https://scholar.google.com.sg/citations?user=GqZfs_IAAAAJ&hl=en">Fangyuan&#160;Yu</a><sup>1 2</sup>\n</div>\n<sup>1</sup>Temus&#160&#160&#160</span>\n<sup>2</sup>Stanford University</span>\n<br />\n<sup>&#9993&#160;</sup>Corresponding author&#160;&#160;</span>\n<br/>\n<br/>\n<div align="center">\n    <a href="https://arxiv.org/abs/2408.16667" target="_blank">\n</div>\n</div>\n<h3 align="center">\n<b>:fire: Code will be released soon</b>\n</h3>\n\n## :books: RuleEval Dataset\n\nRuleAlign is a dataset designed to evaluate rule-based alignment of language models. It accompanies the paper "Iterative Graph Reasoning" and contains:\n\n- 5 distinct rule-based scenarios\n- 200 training queries per scenario (low-data learning scenario)\n- 100 test queries per scenario\n- Weak annotations provided for each query\n\n## :new: Updates\n- [08/2024] [Arxiv paper](https://arxiv.org/abs/2408.16667) released.\n- [08/2024] RuleAlign dataset announced.\n\n## :gear: Evaluation\n\nTo run the evaluation on the RuleAlign dataset, use the following command:\n\n```shell\npython -m script.eval --model_name xxx\n```\n\nReplace `xxx` with the name of the model you want to evaluate.\n\n## :hugs: Citation\nIf you find this dataset useful for your research, please kindly cite our paper:\n\n```\n@misc{yu2024iterativegraphreasoning,\n      title={Iterative Graph Reasoning}, \n      author={Fangyuan Yu},\n      year={2024},\n      eprint={2408.03615},\n      archivePrefix={arXiv},\n      primaryClass={cs.AI}\n}\n```\n\n## :mailbox: Contact\n\nFor any questions or issues regarding the RuleEval dataset, please contact the corresponding author.\n'}

In [35]:
collection_of_datasets.setdefault("category", "collection of datasets")
examples.append(collection_of_datasets)

In [36]:
LLM_based_agentic_system = (df[df["full_name"] == "sathvik-23/hope"].iloc[0].to_dict())
print(LLM_based_agentic_system)

{'full_name': 'sathvik-23/hope', 'description': "Voice Agent Project :  This project implements a voice agent that can:  1. Convert speech to text using Whisper 2. Generate responses using Google's Gemini LLM 3. Convert text responses to speech using gTTS 4. Store all interactions in MongoDB", 'stars': 0, 'forks': 0, 'language': 'Python', 'url': 'https://github.com/sathvik-23/hope', 'updated_year': 2025, 'last_updated': '2025-05-14T20:41:01+00:00', 'created_year': 2025, 'created_at': '2025-05-14T14:28:25+00:00', 'watchers_count': 0, 'size': 513, 'license': nan, 'languages': "{'Python': 5141}", 'primary_language': 'Python', 'topics': '[]', 'readme_content': "# Voice Agent Project\n\nThis project implements a voice agent that can:\n\n1. Convert speech to text using Whisper\n2. Generate responses using Google's Gemini LLM\n3. Convert text responses to speech using gTTS\n4. Store all interactions in MongoDB\n\n## Prerequisites\n\n- Python 3.8 or higher\n- MongoDB installed and running\n- Google Gemini API key\n- FFmpeg (required for Whisper)\n\n## Project Structure\n\n```\nhope/\n├── venv/                      # Main project virtual environment\n├── requirements.txt           # Main project dependencies\n├── .env                      # Environment variables (not committed)\n├── Piper-tts/\n│   ├── venv/                  # Piper-tts virtual environment\n│   └── requirements.txt       # Piper-tts dependencies\n├── whisper/\n│   ├── venv/                  # Whisper virtual environment\n│   └── requirements.txt       # Whisper dependencies\n├── audio/\n│   ├── input/                 # Input audio files\n│   └── output/                # Generated audio responses\n├── voice_agent.py             # Main implementation\n├── test_voice_agent.py        # Test script\n└── README.md                  # This file\n```\n\n## Setup Instructions\n\n### 1. Clone the repository\n\n```bash\ngit clone <repository-url>\ncd hope\n```\n\n### 2. Set up the main project virtual environment\n\n```bash\npython3 -m venv venv\nsource venv/bin/activate  # On Windows: venv\\Scripts\\activate\npip install -r requirements.txt\n```\n\n### 3. Set up the Piper-tts virtual environment (if needed)\n\n```bash\ncd Piper-tts\npython3 -m venv venv\nsource venv/bin/activate\npip install -r requirements.txt\ncd ..\n```\n\n### 4. Set up the Whisper virtual environment (if needed)\n\n```bash\ncd whisper\npython3 -m venv venv\nsource venv/bin/activate\npip install -r requirements.txt\ncd ..\n```\n\n### 5. Set up your environment variables\n\nCopy the example and edit it:\n\n```bash\ncp .env.example .env\n```\n\nEdit `.env` and add your:\n\n- MongoDB connection string\n- Gemini API key (as `GEMINI_API_KEY`)\n- Audio input/output paths if needed\n\n### 6. Ensure MongoDB is running\n\nStart MongoDB if it is not already running:\n\n```bash\nbrew services start mongodb-community  # macOS (Homebrew)\n# or use your OS-specific method\n```\n\n### 7. Run the voice agent\n\n```bash\nsource venv/bin/activate\npython test_voice_agent.py\n```\n\n## Notes\n\n- The main project uses the main `venv` and `requirements.txt`.\n- Piper-tts and Whisper subfolders have their own `venv` and `requirements.txt` if you want to run or develop them independently.\n- The `.env` file is required for API keys and configuration.\n- All virtual environments and `.env` are excluded from git by `.gitignore`.\n\n## Contributing\n\nFeel free to submit issues and enhancement requests!\n"}

In [37]:
LLM_based_agentic_system.setdefault("category", "llm based agentic system")
examples.append(LLM_based_agentic_system)

In [38]:
len(examples)

7

In [39]:
df_examples = pd.DataFrame(examples)

print("Total examples:", len(df_examples))
df_examples[["full_name", "category"]]

Total examples: 7

                              full_name                          category
0         kaushikb11/awesome-llm-agents                 agentic framework
1                      THUDM/AgentBench                 agentic benchmark
2                       zai-org/GLM-4.5                  foundation model
3  oxbshw/LLM-Agents-Ecosystem-Handbook        documents about llm agents
4         Shubhamsaboo/awesome-llm-apps  collection of llm agent projects
5               fangyuan-ksgk/RuleAlign            collection of datasets
6                       sathvik-23/hope          llm based agentic system

In [40]:
with open(FEW_SHOT_JSON, "w") as f:
    json.dump(examples, f, indent=4)

In [41]:
def build_few_shot(path="data/few_shot_examples.json", max_readme_words=3000):
    with open(path, "r") as f:
        examples = json.load(f)

    blocks = []

    for i, ex in enumerate(examples, 1):
        #readme = ex["readme"][:max_readme_chars]
        # Prefer readme_content, fallback to readme_snippet
        readme = ex['readme_content'] 

        if not isinstance(readme, str):
            readme = ""

        words = readme.split()
        if len(words) > max_readme_words:
            readme = " ".join(words[:max_readme_words]) + "\n\n[TRUNCATED]"

        blocks.append(f"""
        ### Example {i}
        Input:
        name: "{ex['full_name']}"
        description: "{ex['description']}"
        topics: {ex['topics']}
        readme:
        \"\"\"
        {readme}
        \"\"\"

        Output:
        {{"category":"{ex['category']}"}}
        """)

    return "\n".join(blocks)

In [42]:
FEW_SHOT = build_few_shot(FEW_SHOT_JSON, max_readme_words=3000)
print(FEW_SHOT)

        ### Example 1
        Input:
        name: "kaushikb11/awesome-llm-agents"
        description: "A curated list of awesome LLM agents frameworks."
        topics: ['agents', 'langchain', 'llm']
        readme:
        """
        # Awesome LLM Agent Frameworks [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)

A curated list of awesome LLM frameworks and agent development tools. If you have a
suggestion, feel free to open an issue or pull request. (Last updated: 2026-01-04)

## Frameworks

- [CrewAI](https://github.com/joaomdmoura/crewAI) - Framework for orchestrating
  role-playing AI agents

  42,166 stars · 5,646 forks · 269 contributors · 187 issues · Python · MIT

  - Role-based agent design
  - Multi-agent collaboration
  - Flexible memory system
  - Built-in error handling


- [Langchain](https://github.com/hwchase17/langchain) - Building applications with LLMs
  through composability

  123,299 stars · 20,329 forks · 470 contributors · 354 issues · Python · MIT

  - Modular and extensible architecture
  - Unified interface for LLMs
  - Pre-built agent toolkits
  - CSV, JSON, and SQL agents
  - Python and Pandas integration
  - Vector store capabilities


- [Microsoft AutoGen](https://github.com/microsoft/autogen) - Framework for building
  multi-agent conversational systems

  53,102 stars · 8,065 forks · 446 contributors · 536 issues · Python · CC-BY-4.0

  - Multi-agent architecture
  - Customizable agents
  - Code execution support
  - Flexible human involvement
  - Advanced conversation management


- [OpenManus](https://github.com/FoundationAgents/OpenManus) - Open-source AI agent
  platform for building general-purpose agents

  52,009 stars · 9,129 forks · 53 contributors · 522 issues · Python · MIT

  - Modular architecture for customization
  - Data analysis and visualization agents
  - Reinforcement learning integration (OpenManus-RL)
  - No invitation code required
  - Built by MetaGPT contributors


- [Llama Index](https://github.com/run-llama/llama_index) - Data framework for LLM
  applications

  46,128 stars · 6,678 forks · 474 contributors · 277 issues · Python · MIT

  - Advanced indexing and retrieval
  - Support for 160+ data sources
  - Customizable RAG workflows
  - Structured data handling
  - Query optimization


- [Microsoft Semantic Kernel](https://github.com/microsoft/semantic-kernel) -
  Integration framework for AI models

  26,959 stars · 4,408 forks · 389 contributors · 540 issues · C# · MIT

  - Enterprise-grade security
  - Multi-language support
  - Plugin architecture
  - Responsible AI features
  - Memory management


- [Dify](https://github.com/langgenius/dify) - Open-source framework for LLM
  applications

  124,493 stars · 19,359 forks · 464 contributors · 660 issues · Python · NOASSERTION

  - Visual prompt orchestration
  - Long context integration
  - API-based development
  - Multi-model support
  - RAG pipeline


- [Haystack](https://github.com/deepset-ai/haystack) - End-to-end NLP framework

  23,780 stars · 2,542 forks · 307 contributors · 112 issues · MDX · Apache-2.0

  - Document processing
  - Neural search
  - Question answering
  - Semantic search
  - Agent capabilities


- [Embedchain](https://github.com/embedchain/embedchain) - Framework for ChatGPT-like
  bots

  44,944 stars · 4,903 forks · 245 contributors · 586 issues · Python · Apache-2.0

  - Multi-source data ingestion
  - Automated embedding
  - Context window management
  - Multiple LLM support
  - RAG optimization


- [Google ADK](https://github.com/google/adk-python) - Agent Development Kit for
  building, evaluating, and deploying AI agents

  16,907 stars · 2,718 forks · 213 contributors · 532 issues · Python · Apache-2.0

  - Code-first development approach
  - Modular multi-agent systems
  - Model-agnostic and deployment-agnostic
  - Built-in developer UI (adk-web)
  - Deploy on Cloud Run or Vertex AI


- [SuperAGI](https://github.com/TransformerOptimus/SuperAGI) - Open-source autonomous AI
  agent framework

  17,019 stars · 2,144 forks · 63 contributors · 202 issues · Python · MIT

  - Customizable agent workflows
  - Tool creation framework
  - Performance monitoring
  - Resource management
  - Multi-vector memory storage


- [Kiln AI](https://github.com/Kiln-AI/Kiln) - Tools for building AI products including
  agents, evals, RAG systems, and fine-tuning

  4,516 stars · 334 forks · 12 contributors · 34 issues · Python · NOASSERTION

  - Free desktop application for no-code development
  - Evaluation frameworks
  - RAG system building
  - Synthetic data generation
  - Agent development tools


- [AGiXT](https://github.com/Josh-XT/AGiXT) - Scalable framework for AI agents

  3,139 stars · 443 forks · 41 contributors · 1 issues · Python · MIT

  - Multi-provider support
  - Chain of thought processing
  - Extensible plugin system
  - Command chaining
  - Web UI included


- [XAgent](https://github.com/OpenBMB/XAgent) - Autonomous LLM-based agent framework

  8,484 stars · 891 forks · 33 contributors · 55 issues · Python · Apache-2.0

  - Human-like planning
  - Autonomous task decomposition
  - Tool learning capabilities
  - Advanced error recovery
  - Built-in action validation


- [Neurolink](https://github.com/juspay/neurolink) - Multi-provider AI agent framework
  with workflow orchestration capabilities, unifying 12+ providers (OpenAI, Google,
  Anthropic, AWS, Azure, Groq, Together AI, Mistral, Cohere, Fireworks, Cloudflare,
  Ollama)

  102 stars · 88 forks · 50 contributors · 402 issues · TypeScript · MIT

  - Multi-agent framework with workflow orchestration
  - Unified interface for 12+ AI providers
  - Edge-first architecture with local/cloud deployment
  - Production-grade streaming and tool calling
  - Battle-tested at Juspay (15M+ requests/month)


- [OpenAgents](https://github.com/xlang-ai/OpenAgents) - Open platform for language
  agents

  4,656 stars · 512 forks · 16 contributors · 12 issues · Python · Apache-2.0

  - Data analysis capabilities
  - Web browsing integration
  - Coding assistance
  - Plugin ecosystem
  - Interactive visualization


- [AI Legion](https://github.com/eumemic/ai-legion) - Swarm framework for autonomous
  agents

  1,431 stars · 174 forks · 6 contributors · 8 issues · TypeScript · MIT

  - Multi-agent coordination
  - Dynamic task allocation
  - Emergent behavior support
  - Flexible agent roles
  - Real-time collaboration


- [Agent Protocol](https://github.com/e2b-dev/agent-protocol) - Unified interface for AI
  agents

  1,432 stars · 171 forks · 14 contributors · 42 issues · Python · MIT

  - Standardized communication
  - Language-agnostic design
  - Tool integration specs
  - Interoperability focus
  - Protocol versioning


- [Agents.js](https://github.com/Webgburnet/Agents.js) - JavaScript framework for
  building AI agents

  - Browser-native implementation
  - Event-driven architecture
  - Tool abstraction layer
  - Memory management
  - Real-time processing- [Cache-to-Cache](https://github.com/thu-nics/C2C) - Novel paradigm for direct
  semantic communication between LLMs via KV-Cache

  87 stars · 6 forks · 2 contributors · 2 issues · Python · Apache-2.0

  - Direct semantic communication via KV-Cache
  - Multi-agent system integration
  - Neural cache projection and fusion- [CAMEL](https://github.com/camel-ai/camel) - Communicative Agents for "Mind"
  Exploration

  14,875 stars · 1,638 forks · 171 contributors · 599 issues · Python · Apache-2.0

  - Role-playing framework
  - Task-oriented dialogue
  - Multi-agent conversations
  - Behavioral analysis
  - Cognitive architecture- [BabyAGI](https://github.com/yoheinakajima/babyagi) - Lightweight framework for AI
  task management

  - Task prioritization
  - Autonomous execution
  - Memory persistence
  - Goal-oriented planning
  - Resource optimization- [Autonomous-GPT](https://github.com/Significant-Gravitas/Auto-GPT) - Framework for
  autonomous GPT-4 agents

  179,412 stars · 46,089 forks · 433 contributors · 273 issues · Python · NOASSERTION

  - Internet access capabilities
  - Long-term memory
  - Goal-oriented behavior
  - File operations
  - Command execution- [MetaGPT](https://github.com/geekan/MetaGPT) - Multi-agent framework for software
  development

  59,615 stars · 7,299 forks · 115 contributors · 57 issues · Python · MIT

  - Role-based development
  - Code generation
  - Project management
  - Documentation writing
  - Testing automation- [GenoMAS](https://github.com/Liu-Hy/GenoMAS) - Multi-agent framework for scientific
  discovery and automated data analysis

  123 stars · 19 forks · 1 contributors · 0 issues · Python · MIT

  - Guided planning framework
  - Typed message-passing protocol
  - Heterogeneous LLM architecture
  - Domain-agnostic design
  - Scientific workflow automation- [minions](https://github.com/getminions/minions) - Extensible framework for AI
  assistants

  - Custom behavior definition
  - Tool integration
  - State management
  - Event handling
  - Parallel execution- [ix](https://github.com/kreneskyp/ix) - Autonomous agent framework

  1,037 stars · 129 forks · 5 contributors · 14 issues · Python · MIT

  - Visual workflow builder
  - Sandbox environments
  - Tool integration
  - Process monitoring
  - Agent collaboration- [saplings](https://github.com/shobrook/saplings) - Build smarter agents using tree
  search

  269 stars · 17 forks · 4 contributors · 0 issues · Python · Apache-2.0

  - Boost reasoning abilities
  - Supports popular search algorithms
  - Minimal setup, 2 lines of code- [Smolagents](https://github.com/huggingface/smolagents) - Minimalist framework for
  building powerful agents

  24,406 stars · 2,180 forks · 189 contributors · 327 issues · Python · Apache-2.0

  - Code-first approach
  - Multi-agent orchestration
  - LLM provider flexibility
  - Tool integration
  - Hub integration for sharing- [Flowise](https://github.com/FlowiseAI/Flowise) - Drag & drop UI framework for
  building LLM flows

  47,784 stars · 23,485 forks · 268 contributors · 747 issues · TypeScript · NOASSERTION

  - Visual flow builder
  - Custom LLM integrations
  - API generation
  - Authentication support
  - Docker deployment


- [Pydantic AI](https://github.com/pydantic/pydantic-ai) - Production-grade agent
  framework built on Pydantic

  14,116 stars · 1,513 forks · 332 contributors · 422 issues · Python · MIT

  - Type-safe development
  - Multi-model support
  - Structured responses
  - Dependency injection
  - Logfire integration


- [Upsonic](https://github.com/upsonic/upsonic) - Reliable agent framework that
  support MCP.

  7,737 stars · 712 forks · 33 contributors · 78 issues · Python · MIT

  - Easy-to-activate reliability layers
  - Model Context Protocol (MCP)
  - Integrated Browser Use and Computer Use
  - Isolated environment to run agents
  - Task-Centric Design


- [EvoAgentX](https://github.com/EvoAgentX/EvoAgentX) - Building a Self-Evolving
  Ecosystem of AI Agents

  2,431 stars · 193 forks · 24 contributors · 12 issues · Python · NOASSERTION

  - Easy Agent and Workflow Customization
  - Workflow Optimization & Self-Evolving
  - Agent/workflow evolution algorithms integrated
  - Execution Toolkit


- [Portia AI](https://github.com/portiaAI/portia-sdk-python) - Open source framework for predictable,
  controllable and authenticated agents.

  1,141 stars · 101 forks · 26 contributors · 44 issues · Python · NOASSERTION

  - Structured planning
  - Stateful execution
  - Human in the loop controls
  - Tool catalogue with built-in auth
  - MCP support- [Agentic Radar](https://github.com/splx-ai/agentic-radar) - A security scanner for
  agentic workflows

  848 stars · 106 forks · 8 contributors · 10 issues · Python · Apache-2.0

  - Scans agentic workflow source code
  - Finds vulnerabilities (CVE & OWASP)
  - Generates interactive reports
  - Suggests remediation steps
  - Supports popular agentic workflows
- [AgentFlow](https://github.com/lupantech/AgentFlow) - Trainable multi-agent framework
  with in-the-flow optimization

  1,465 stars · 188 forks · 4 contributors · 7 issues · Python · MIT

  - Four specialized modules (planner, executor, verifier, generator)
  - Flow-GRPO reinforcement learning
  - Tool integration (math, coding, scientific, search)
  - Stanford research project
  - Performance gains over monolithic approaches


- [Mastra](https://github.com/mastra-ai/mastra) - TypeScript AI agent framework with
  assistants, RAG, and observability

  19,103 stars · 1,379 forks · 279 contributors · 300 issues · TypeScript · NOASSERTION

  - Type-safe development
  - Multi-model support (GPT-4, Claude, Gemini, Llama)
  - Structured responses
  - API generation
  - Tool integration


- [Flappy](https://github.com/pleisto/flappy) - Production-ready LLM agent SDK

  307 stars · 23 forks · 7 contributors · 10 issues · Rust · Apache-2.0

  - Production-grade reliability
  - Type-safe agent development
  - Multi-language support
  - Performance optimized
  - Developer-friendly SDK


- [CleverBee](https://github.com/SureScaleAI/cleverbee) - Deep research assistant agent
  with web browsing capabilities

  309 stars · 16 forks · 1 contributors · 1 issues · Python · AGPL-3.0

  - Interactive web UI via Chainlit
  - MCP tool support for external integrations
  - Multi-LLM research (configurable LLMs)
  - Automated web browsing with Playwright
  - Token tracking and cost estimation


- [RAI](https://github.com/RobotecAI/rai) - Agentic framework for robotics using ROS 2

  428 stars · 54 forks · 22 contributors · 59 issues · Python · Apache-2.0

  - ROS 2 integration
  - Complex action execution
  - Scenario-based testing
  - Voice interaction support
  - Vendor-agnostic architecture


- [Floom](https://github.com/FloomAI/Floom) - AI gateway and agent/pipeline marketplace

  46 stars · 4 forks · 2 contributors · 0 issues · C# · MIT

  - AI pipeline orchestration
  - Agent marketplace integration
  - Kubernetes-style architecture
  - Streamlined AI integration
  - DevOps-friendly deployment


- [CoreAgent](https://github.com/CoreAgent-Project/CoreAgent) - Minimalist agent framework
  with stateful tools

  25 stars · 3 forks · 2 issues · Python

  - Simplicity-first design
  - Stateful tool support
  - Multi-agent coordination
  - Shared state management
  - Built-in tools library- [Project Alice](https://github.com/MarianoMolina/project_alice) - Framework and
  platform for building and deploying agentic workflows

  253 stars · 34 forks · 1 contributors · 1 issues · Python · BSD-3-Clause

  - No-code and coding interface
  - Visual workflow builder
  - Live demo available
  - Workflow deployment platform
  - Alpha stage development- [AgentSquare](https://github.com/tsinghua-fib-lab/AgentSquare) - Automatic LLM agent
  search in modular design space

  199 stars · 14 forks · 10 issues · HTML

  - Module evolution and recombination
  - Planning, Reasoning, Tool Use, Memory modules
  - Adaptive agent search framework
  - Unified framework for six agent tasks
  - Tsinghua University research project

        """

        Output:
        {"category":"agentic framework"}


        ### Example 2
        Input:
        name: "THUDM/AgentBench"
        description: "A Comprehensive Benchmark to Evaluate LLMs as Agents (ICLR'24)"
        topics: ['chatgpt', 'gpt-4', 'llm', 'llm-agent']
        readme:
        """
        # AgentBench

![](./assets/cover.jpg)

<p align="center">
   <a href="https://docs.google.com/spreadsheets/d/e/2PACX-1vRR3Wl7wsCgHpwUw1_eUXW_fptAPLL3FkhnW_rua0O1Ji_GIVrpTjY5LaKAhwO-WeARjnY_KNw0SYNJ/pubhtml" target="_blank">🌐 Leaderboard (new)</a> | <a href="https://twitter.com/thukeg" target="_blank">🐦 Twitter</a> | <a href="mailto:agentbench@googlegroups.com">✉️ Google Group</a> | <a href="https://arxiv.org/abs/2308.03688" target="_blank">📃 Paper </a>
</p>

<p align="center">
👋 Join our <a href="https://join.slack.com/t/agentbenchcol-huw1944/shared_invite/zt-20ixabcuv-31cFLBAkqGQxQkJqrWVEVg" target="_blank">Slack</a>  for <i>Q & A</i> or <i><b>collaboration</b> on next version of AgentBench</i>!
</p>

## 🔥[2025.10.10] Introducing **AgentBench FC (Function Calling)** based on [AgentRL](https://github.com/THUDM/AgentRL)

The current repository contains the function-calling version of AgentBench, integrated with [AgentRL](https://github.com/THUDM/AgentRL), an end-to-end multitask and mutliturn LLM Agent RL framework.
If you wish to use the older version, you can revert to [v0.1](https://github.com/THUDM/AgentBench/tree/v0.1) and [v0.2](https://github.com/THUDM/AgentBench/tree/v0.2).

Comparing to the original AgentBench, this version uses a function-calling style prompt,
and adds fully-containerized deployment support for the following tasks:

- `alfworld` (AF)
- `dbbench` (DB)
- `knowledgegraph` (KG)
- `os_interaction` (OS)
- `webshop` (WS)

### Quick Start

We support a quick one-command setup for all the above tasks using Docker Compose.

Before starting, please download or build the following Docker images required by the tasks:

```shell
# dbbench
docker pull mysql:8

# os_interaction
docker build -t local-os/default -f ./data/os_interaction/res/dockerfiles/default data/os_interaction/res/dockerfiles
docker build -t local-os/packages -f ./data/os_interaction/res/dockerfiles/packages data/os_interaction/res/dockerfiles
docker build -t local-os/ubuntu -f ./data/os_interaction/res/dockerfiles/ubuntu data/os_interaction/res/dockerfiles
```

To run the KG freebase server, you will also need a copy of the data found [here](https://github.com/dki-lab/Freebase-Setup).
Download, extract and place the data at `./virtuoso_db/virtuoso.db` (or modify `extra/docker-compose.yml` and set the mount point to your data location).

Then, you can bring up the stack with:

```shell
docker compose -f extra/docker-compose.yml up
```

This command will download or build the necessary Docker images and start the following services in Docker:

- AgentRL Controller
- `alfworld` task worker (x1, increase as needed)
- `dbbench` task worker (x1, increase as needed)
- `knowledgegraph` task worker (x1, increase as needed)
- `os_interaction` task worker (x1, increase as needed)
- `webshop` task worker (x1, increase as needed)
- freebase server (for `knowledgegraph` task)
- Redis server (for container allocation)

If your machine already has Redis (version 7+) running, you can omit the Redis service from the `docker-compose.yml`.

> [!WARNING]
> Please note that the `webshop` environment requires ~16GB of RAM to start,
> and the current implementation of `alfworld` leaks memory and disk space until the task worker is restarted.
> Make sure your machine has sufficient resources before running.

### Benchmarking Results

We report the results of various models on the test set of AgentBench FC.

![img.png](assets/fc_leaderboard.png)

Please see our [Leaderboard](https://docs.google.com/spreadsheets/d/e/2PACX-1vRR3Wl7wsCgHpwUw1_eUXW_fptAPLL3FkhnW_rua0O1Ji_GIVrpTjY5LaKAhwO-WeARjnY_KNw0SYNJ/pubhtml) for full results.
Please contact [agentbench_fc&#64;googlegroups.com](mailto:agentbench_fc@googlegroups.com) if you have any questions or would like to contribute your results.

---

## 🔥[2024.08.13] Introducing [VisualAgentBench](https://github.com/THUDM/VisualAgentBench)

VisualAgentBench is designed for evaluating and training visual foundation agents based on large multimodel models (LMMs). We introduce 5 distinct environments spanning

* Embodied: VAB-OmniGibson, VAB-Minecraft
* GUI: VAB-Mobile, VAB-WebArena-Lite
* Visual Design: VAB-CSS

to systematically benchmark 17 LMMs (proprietary & open LMMs). We also provide the trajectory dataset for behavior cloning training on open LMMs for you to develop your own visual foundation agents!

---

The following is the introduction to the original AgentBench (v0.2).

# AgentBench: Evaluating LLMs as Agents


In [43]:
CATEGORIES = [
    "collection of llm agent projects", 
    "collection of datasets",
    "agentic framework", 
    "agentic benchmark", 
    "foundation model", 
    "llm based agentic system",
    "documents about llm agents" # (books, chapters, papers ...)
    "other"
]

category_list = "\n".join(f"- {c}" for c in CATEGORIES)
print(category_list)

- collection of llm agent projects
- collection of datasets
- agentic framework
- agentic benchmark
- foundation model
- llm based agentic system
- documents about llm agentsother

In [44]:
SAMPLE_CSV = "csv/sample_for_llm.csv"
sample_df = pd.read_csv(SAMPLE_CSV)
sample_df.head(2)

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,watchers_count,size,license,languages,primary_language,topics,readme_content
0,Axaled/LinkedIn-Agents-Challenge,Building 31 AI agents in 31 days — practical u...,0,0,Python,https://github.com/Axaled/LinkedIn-Agents-Chal...,2025,2025-05-26T08:12:43+00:00,2025,2025-05-01T18:03:30+00:00,0,73,NaN,{'Python': 62124},Python,[],# 🤖 30 AI Agents in 30 Days\n\nWelcome to my p...
1,VanGongwanxiaowan/llm-agents-interview,收集大模型相关面试题｜agent｜上下文工程｜强化学习｜langgraph｜langchai...,24,1,Python,https://github.com/VanGongwanxiaowan/llm-agent...,2026,2026-01-09T05:20:03+00:00,2025,2025-08-30T09:04:10+00:00,24,29009,NaN,"{'Python': 140953, 'Jupyter Notebook': 98794, ...",Python,[],# llm-agents-interview\n强化学习微调指导文档：https://doc...

In [45]:
len(sample_df)

200