Sample Data Cleaning [for "sample_for_llm_shortReadme.csv"]

In [2]:
pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 5.4 MB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: six in /Users/urinalama/LLM-Based-Agent-Systems/venv/lib/python3.11/site-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (pyproject.toml) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993332 sha256=bd6ff6e88155bc07db34d0999a899369ec99aec37e8f60b2b8904aa352c280d9
  Stored in directory: /Users/urinalama/Library/Caches/pip/wheels/0a/f2/b2/e5ca405801e05eb7c8ed5b3b4bcf1fcabcd6272c167640072e
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
from langdetect import detect
import pandas as pd

In [8]:
def detect_lang(text): 
    if not isinstance(text, str) or len(text.strip()) == 0:
        return "nan" 
    try: 
        return detect(text) 
    except:
        return "unknown"

In [33]:
df_sample = pd.read_csv("csv/sample_for_llm_shortReadme.csv")
len(df_sample)

200

In [37]:
null_readme = df_sample["readme_snippet"].isna() | (df_sample["readme_snippet"].str.strip() == "")
print(f"Number of null or empty readme_snippet: {null_readme.sum()}")
df_sample[null_readme].head(3)

Number of null or empty readme_snippet: 21

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,watchers_count,size,license,languages,primary_language,topics,readme_snippet
1,jesvijonathan/Repo-Vision,A full-fledged program agent suite powered by ...,1,0,Python,https://github.com/jesvijonathan/Repo-Vision,2025,2025-12-23T19:05:54+00:00,2025,2025-01-25T09:40:37+00:00,1,24216,GNU General Public License v3.0,"{'Python': 6701, 'PowerShell': 4841}",Python,[],NaN
7,jayapat/genai_llm_agentic,Project on connecting with open ai llm via api...,0,0,Python,https://github.com/jayapat/genai_llm_agentic,2025,2025-08-03T20:34:09+00:00,2025,2025-08-03T01:23:27+00:00,0,6,NaN,{'Python': 1487},Python,[],NaN
30,SnehaR26/HealthOSS,An agentic AI based app that handles health re...,0,0,Python,https://github.com/SnehaR26/HealthOSS,2025,2025-12-16T18:04:47+00:00,2025,2025-10-05T17:39:27+00:00,0,2,NaN,{'Python': 5183},Python,[],NaN

In [39]:
df_sample = df_sample.drop(df_sample[null_readme].index)
len(df_sample)

179

In [40]:
df_sample["readme_lang"] =  df_sample["readme_snippet"].apply(detect_lang) 
df_sample["desc_lang"] = df_sample["description"].apply(detect_lang)

In [43]:
df_notenglish = df_sample[(df_sample["readme_lang"] != "en") & (df_sample["desc_lang"] != "en")]
print("Number of repositories not in English:", len(df_notenglish))
df_notenglish

Number of repositories not in English: 4

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,watchers_count,size,license,languages,primary_language,topics,readme_snippet,readme_lang,desc_lang
34,vitobrat/report_llm_agent,NaN,0,0,Python,https://github.com/vitobrat/report_llm_agent,2025,2025-08-01T06:06:36+00:00,2025,2025-07-10T06:09:19+00:00,0,142,NaN,"{'Python': 53181, 'Dockerfile': 936}",Python,[],Report_llm_agent Добавить файл .env в директор...,ru,nan
64,comnhuman/kt_ai_agent_document_llm,문서작성 LLM 개발 kt dacon 참여 레포지토리입니다.,0,1,Python,https://github.com/comnhuman/kt_ai_agent_docum...,2025,2025-09-01T01:55:42+00:00,2025,2025-08-21T01:37:48+00:00,0,1030,NaN,"{'Python': 55916, 'Shell': 1340, 'Dockerfile':...",Python,[],🚀 지원사업 데이터 수집 & 사업계획서 초안 작성 Agent 중소기업 지원사업 정보...,ko,ko
120,HAM1722/agente_ejecutivo,Extractor OCR - Facturas EMCALI: sistema autom...,0,0,Python,https://github.com/HAM1722/agente_ejecutivo,2025,2025-10-19T02:55:14+00:00,2025,2025-10-13T19:44:41+00:00,0,74,NaN,{'Python': 94689},Python,"['energia', 'facturas', 'llm', 'ocr', 'openai'...",Extractor OCR - Facturas EMCALI README.md,es,es
165,mjamal/SimpleAgent,Basic LLM AI Agent,0,0,Python,https://github.com/mjamal/SimpleAgent,2025,2025-11-16T05:44:25+00:00,2025,2025-11-08T22:16:22+00:00,0,6,NaN,{'Python': 7086},Python,[],SimpleAgent,ca,ca

In [44]:
df_clean = df_sample.drop(df_notenglish.index)
df_clean = df_clean.drop(columns=["desc_lang", "readme_lang"])

In [45]:
print("Length of cleaned dataset:", len(df_clean))
df_clean.head(3)

Length of cleaned dataset: 175

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,watchers_count,size,license,languages,primary_language,topics,readme_snippet
0,chrisjcc/llm-applied-research,Research and development framework for large l...,0,0,Python,https://github.com/chrisjcc/llm-applied-research,2025,2025-10-02T00:18:15+00:00,2025,2025-09-23T15:05:14+00:00,0,301,Apache License 2.0,"{'Python': 65791, 'Shell': 2297}",Python,[],llm-applied-research Research and development ...
2,RoshanM24/Langgraph-with-Astra-DB---Multi-Sour...,This project demonstrates the integration of L...,1,0,Python,https://github.com/RoshanM24/Langgraph-with-As...,2025,2025-08-13T00:07:51+00:00,2025,2025-08-12T23:24:58+00:00,1,12,NaN,{'Python': 7957},Python,[],LangGraph with Astra DB — Intelligent Query Ro...
3,karaalv/portfolio-agent,RAG based portfolio chat agent 🤖,0,0,Python,https://github.com/karaalv/portfolio-agent,2025,2025-08-31T17:49:06+00:00,2025,2025-07-28T22:28:51+00:00,0,204,Apache License 2.0,"{'Python': 169011, 'HCL': 14250, 'Shell': 4827...",Python,"['ai', 'llm', 'portfolio-website', 'rag-chatbot']",Portfolio Agent 🤖 The agent can also email the...

In [46]:
df_clean.to_csv("csv/clean_sample_for_llm_shortReadme.csv", index=False)

In [ ]:
mask = ( 
    (df_sample["description"].isna() | (df_sample["description"].str.strip() == "")) & 
    (df_sample["readme_snippet"].isna() | (df_sample["readme_snippet"].str.strip() == "")) 
)

In [8]:
df_sample[mask]

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,watchers_count,size,license,languages,primary_language,topics,readme_snippet
91,krmui/LLM_Agent,NaN,0,0,Python,https://github.com/krmui/LLM_Agent,2025,2025-03-24T05:53:15+00:00,2025,2025-03-24T03:26:15+00:00,0,2755,NaN,"{'Python': 13147, 'HTML': 12474}",Python,[],NaN
180,adinasa22/MultiAgentLLM,NaN,0,0,Python,https://github.com/adinasa22/MultiAgentLLM,2025,2025-07-30T11:22:15+00:00,2025,2025-07-22T12:23:32+00:00,0,11,NaN,{'Python': 2103},Python,[],NaN

In [17]:
row_nan = df_sample.iloc[91]   # pick the first row (or any index you want)
row_nan

full_name                              krmui/LLM_Agent
description                                        NaN
stars                                                0
forks                                                0
language                                        Python
url                 https://github.com/krmui/LLM_Agent
updated_year                                      2025
last_updated                 2025-03-24T05:53:15+00:00
created_year                                      2025
created_at                   2025-03-24T03:26:15+00:00
watchers_count                                       0
size                                              2755
license                                            NaN
languages             {'Python': 13147, 'HTML': 12474}
primary_language                                Python
topics                                              []
readme_snippet                                     NaN
Name: 91, dtype: object

In [18]:
print("README language:", detect_lang(row_nan["readme_snippet"]))
print("Description language:", detect_lang(row_nan["description"]))

README language: nan
Description language: nan

In [19]:
row_notEnglish = df_sample.iloc[161]   # pick the first row (or any index you want)
row_notEnglish

full_name                                       NiJingzhe/SimpleManus
description         An Extremely simple agent framework just like ...
stars                                                               2
forks                                                               0
language                                                       Python
url                          https://github.com/NiJingzhe/SimpleManus
updated_year                                                     2025
last_updated                                2025-10-28T02:28:12+00:00
created_year                                                     2025
created_at                                  2025-06-27T01:21:04+00:00
watchers_count                                                      2
size                                                            12062
license                               GNU General Public License v2.0
languages           {'Python': 231264, 'Dockerfile': 2605, 'Shell'...
primary_language                                               Python
topics              ['agent', 'agent-framework', 'agentic-ai', 'ag...
readme_snippet      SimpleAgent 一个基于 SimpleLLMFunc 构建的模块化智能体框架，支持多...
Name: 161, dtype: object

In [20]:
print("README language:", detect_lang(row_notEnglish["readme_snippet"]))
print("Description language:", detect_lang(row_notEnglish["description"]))

README language: ca
Description language: en

In [7]:
df_sample["readme_lang"] =  df_sample["readme_snippet"].apply(detect_lang) 
df_sample["desc_lang"] = df_sample["description"].apply(detect_lang)

In [25]:
df_english = df_sample[(df_sample["readme_lang"] == "en") & (df_sample["desc_lang"] == "en")]
print("Number of repositories in en:", len(df_english))
df_english.tail(2)

Number of repositories in en: 149

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,watchers_count,size,license,languages,primary_language,topics,readme_snippet,readme_lang,desc_lang
198,felipemaciasventura/snowflake_nlp_agent_v2,Snowflake NLP Agent v2 - Advanced Natural Lang...,0,0,Python,https://github.com/felipemaciasventura/snowfla...,2025,2025-11-12T15:16:02+00:00,2025,2025-09-18T19:06:35+00:00,0,591,NaN,{'Python': 130329},Python,[],🤖 Snowflake NLP Agent v2 An intelligent web ap...,en,en
199,pixeltable/pixelmemory,Pixelmemory — A multimodal memory layer for yo...,5,0,Python,https://github.com/pixeltable/pixelmemory,2025,2025-09-12T02:02:06+00:00,2025,2025-05-19T20:28:27+00:00,5,418,Apache License 2.0,"{'Python': 20352, 'Shell': 1804}",Python,"['ai', 'llm', 'mcp', 'memory', 'python']",Pixelmemory Pixelmemory demonstrates how to bu...,en,en

In [8]:
df_notenglish = df_sample[(df_sample["readme_lang"] != "en") & (df_sample["desc_lang"] != "en")]
print("Number of repositories not in English:", len(df_notenglish))
print(df_notenglish["readme_lang"], df_notenglish["desc_lang"])

Number of repositories not in English: 6
34      ru
64      ko
91     nan
120     es
165     ca
180    nan
Name: readme_lang, dtype: object 34     nan
64      ko
91     nan
120     es
165     ca
180    nan
Name: desc_lang, dtype: object

In [12]:
df_notenglish.head(4)

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,watchers_count,size,license,languages,primary_language,topics,readme_snippet,readme_lang,desc_lang
34,vitobrat/report_llm_agent,NaN,0,0,Python,https://github.com/vitobrat/report_llm_agent,2025,2025-08-01T06:06:36+00:00,2025,2025-07-10T06:09:19+00:00,0,142,NaN,"{'Python': 53181, 'Dockerfile': 936}",Python,[],Report_llm_agent Добавить файл .env в директор...,ru,nan
64,comnhuman/kt_ai_agent_document_llm,문서작성 LLM 개발 kt dacon 참여 레포지토리입니다.,0,1,Python,https://github.com/comnhuman/kt_ai_agent_docum...,2025,2025-09-01T01:55:42+00:00,2025,2025-08-21T01:37:48+00:00,0,1030,NaN,"{'Python': 55916, 'Shell': 1340, 'Dockerfile':...",Python,[],🚀 지원사업 데이터 수집 & 사업계획서 초안 작성 Agent 중소기업 지원사업 정보...,ko,ko
91,krmui/LLM_Agent,NaN,0,0,Python,https://github.com/krmui/LLM_Agent,2025,2025-03-24T05:53:15+00:00,2025,2025-03-24T03:26:15+00:00,0,2755,NaN,"{'Python': 13147, 'HTML': 12474}",Python,[],NaN,nan,nan
120,HAM1722/agente_ejecutivo,Extractor OCR - Facturas EMCALI: sistema autom...,0,0,Python,https://github.com/HAM1722/agente_ejecutivo,2025,2025-10-19T02:55:14+00:00,2025,2025-10-13T19:44:41+00:00,0,74,NaN,{'Python': 94689},Python,"['energia', 'facturas', 'llm', 'ocr', 'openai'...",Extractor OCR - Facturas EMCALI README.md,es,es

In [ ]:
df_single_english = df_sample[
    ((df_sample["readme_lang"] == "en") & (df_sample["desc_lang"] != "en")) |
    ((df_sample["readme_lang"] != "en") & (df_sample["desc_lang"] == "en"))
]

print("Number of repositories with only one English field:", len(df_single_english))
df_single_english.tail(3)

Number of repositories with only one English field: 45

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,watchers_count,size,license,languages,primary_language,topics,readme_snippet,readme_lang,desc_lang
188,xzxzlala/Small-LLM-RAG-and-Agent,NaN,0,0,Python,https://github.com/xzxzlala/Small-LLM-RAG-and-...,2024,2024-07-30T08:12:16+00:00,2024,2024-06-25T05:40:44+00:00,0,1854,NaN,{'Python': 47554},Python,[],Introduction for each file and folder Here is ...,en,nan
193,yquemener/server-agent,My own take on using LLMs to automate a task. ...,0,0,Python,https://github.com/yquemener/server-agent,2023,2023-06-18T12:22:40+00:00,2023,2023-05-13T13:18:49+00:00,0,823,GNU Affero General Public License v3.0,"{'Python': 64298, 'HTML': 6299, 'Shell': 956, ...",Python,[],NaN,nan,en
195,rholanx/NVExp_Automation,With build-in LLM agent to run NV experiment s...,0,0,Python,https://github.com/rholanx/NVExp_Automation,2025,2025-11-20T20:25:05+00:00,2025,2025-05-19T18:38:24+00:00,0,183,MIT License,{'Python': 82329},Python,[],NaN,nan,en

In [31]:
len(df_single_english)

45

In [30]:
df_single_english["full_name"]

1                              jesvijonathan/Repo-Vision
4               bhevin/Search-Engine-With-LLm-and-Agents
7                              jayapat/genai_llm_agentic
14                          paulgresens/simple-llm-agent
27                         gbid/llm-voice-agent-retellai
30                                    SnehaR26/HealthOSS
32                                  GourabNath/Resume_AI
39                    appugouda-architect/local-ai-agent
40                        takazawasorato/multi-llm-agent
43                             thanhtungvudata/cinemood2
46                                 json2x/zen-llm-agents
48               arshgulati/Llm-powered-autonomous-agent
49     Ian-Kwach/Intelligent-LLM-Agent-for-Automated-...
51                            rcsunanda/calculator_agent
56     TrevinoParker7/Agentic_AI_LLM_Top_10_OWASP_Che...
57     tanush2508/INFO-5940-Final-Project-Multi-Agent...
62                                          Gonzih/ssher
75                                    HighFlip/deus_flow
76                        MypaceEngine/llm_desktop_agent
79                           Tathagata51/email-clasifier
100                       Killianx256/LLMs-to-Agentic-AI
117                      hjleal75/llm-data-analyst-agent
119                                Trojan3877/HelixAgent
122               21f3001385/LLM-Based-Automation-Agent-
126                        subeerhaldar/multi-step-agent
136             fashion-ai-dev/LLM-Agents-MOOC-Hackathon
137                                      Wenremo/allmeca
138                            anciri/LLM_Agent_Personal
140                       aishvaryaraj/llm-agent-society
142                     shivDroid/SQL-Database-AI-Agents
150                       Gao2546/LLM_Chatbot_With_Agent
154                  daniyalshahzad/financial-agent-api-
156                  Tushar-S-Mole/voice-agent-by-Tushar
160                             aadesh006/Basic-AI-Agent
161                                NiJingzhe/SimpleManus
164                    EduardoRenz/LLMS-Langchain-Agents
166                  AnonymousRepo12/LLM-Agent-Bug-Study
168                                NagaChetana/LLM_Agent
169                                       mmqtx/cardio-x
170    yutokeio/Complexification-of-Strategies-Among-...
175                 arindam-giri/excel-agent-project-llm
184                           Pravin98651/Mult_Agent_LLM
188                     xzxzlala/Small-LLM-RAG-and-Agent
193                               yquemener/server-agent
195                             rholanx/NVExp_Automation
Name: full_name, dtype: object

In [33]:
df_single_english_nanReadme = df_sample[
    ((df_sample["readme_lang"] != "en") & (df_sample["desc_lang"] == "en"))]

In [34]:
len(df_single_english_nanReadme)

24

In [35]:
df_single_english_nanReadme.head(4)

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,watchers_count,size,license,languages,primary_language,topics,readme_snippet,readme_lang,desc_lang
1,jesvijonathan/Repo-Vision,A full-fledged program agent suite powered by ...,1,0,Python,https://github.com/jesvijonathan/Repo-Vision,2025,2025-12-23T19:05:54+00:00,2025,2025-01-25T09:40:37+00:00,1,24216,GNU General Public License v3.0,"{'Python': 6701, 'PowerShell': 4841}",Python,[],NaN,nan,en
7,jayapat/genai_llm_agentic,Project on connecting with open ai llm via api...,0,0,Python,https://github.com/jayapat/genai_llm_agentic,2025,2025-08-03T20:34:09+00:00,2025,2025-08-03T01:23:27+00:00,0,6,NaN,{'Python': 1487},Python,[],NaN,nan,en
30,SnehaR26/HealthOSS,An agentic AI based app that handles health re...,0,0,Python,https://github.com/SnehaR26/HealthOSS,2025,2025-12-16T18:04:47+00:00,2025,2025-10-05T17:39:27+00:00,0,2,NaN,{'Python': 5183},Python,[],NaN,nan,en
32,GourabNath/Resume_AI,An LLM-based Agentic AI Framework to Generate ...,0,0,Python,https://github.com/GourabNath/Resume_AI,2025,2025-11-23T20:22:47+00:00,2025,2025-11-23T14:18:28+00:00,0,6,NaN,{'Python': 8030},Python,[],NaN,nan,en

Normalizing and cleaning manual csv

In [3]:
df_sample_manual = pd.read_csv("data/sample_agent_repos_llm_filtered_withShortReadme_manual.csv")

In [4]:
df_sample_manual.head(2)

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,...,size,license,languages,primary_language,topics,readme_snippet,category,Manual,Comment,Unnamed: 20
0,chrisjcc/llm-applied-research,Research and development framework for large l...,0,0,Python,https://github.com/chrisjcc/llm-applied-research,2025,2025-10-02T00:18:15+00:00,2025,2025-09-23T15:05:14+00:00,...,301,Apache License 2.0,"{'Python': 65791, 'Shell': 2297}",Python,[],llm-applied-research Research and development ...,other,agentic framework,It has less information in its readme,NaN
1,jesvijonathan/Repo-Vision,A full-fledged program agent suite powered by ...,1,0,Python,https://github.com/jesvijonathan/Repo-Vision,2025,2025-12-23T19:05:54+00:00,2025,2025-01-25T09:40:37+00:00,...,24216,GNU General Public License v3.0,"{'Python': 6701, 'PowerShell': 4841}",Python,[],NaN,agentic framework,RAG-based LLM application,Less info in readme,NaN

In [5]:
null_readme = df_sample_manual["readme_snippet"].isna() | (df_sample_manual["readme_snippet"].str.strip() == "")
print(f"Number of null or empty readme_snippet: {null_readme.sum()}")
df_sample_manual[null_readme].head(3)

Number of null or empty readme_snippet: 21

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,...,size,license,languages,primary_language,topics,readme_snippet,category,Manual,Comment,Unnamed: 20
1,jesvijonathan/Repo-Vision,A full-fledged program agent suite powered by ...,1,0,Python,https://github.com/jesvijonathan/Repo-Vision,2025,2025-12-23T19:05:54+00:00,2025,2025-01-25T09:40:37+00:00,...,24216,GNU General Public License v3.0,"{'Python': 6701, 'PowerShell': 4841}",Python,[],NaN,agentic framework,RAG-based LLM application,Less info in readme,NaN
7,jayapat/genai_llm_agentic,Project on connecting with open ai llm via api...,0,0,Python,https://github.com/jayapat/genai_llm_agentic,2025,2025-08-03T20:34:09+00:00,2025,2025-08-03T01:23:27+00:00,...,6,NaN,{'Python': 1487},Python,[],NaN,llm-based agentic system,LLM-powered script,NaN,NaN
30,SnehaR26/HealthOSS,An agentic AI based app that handles health re...,0,0,Python,https://github.com/SnehaR26/HealthOSS,2025,2025-12-16T18:04:47+00:00,2025,2025-10-05T17:39:27+00:00,...,2,NaN,{'Python': 5183},Python,[],NaN,llm-based agentic system,LLM-Based agentic system,NaN,NaN

In [6]:
df_sample_manual = df_sample_manual.drop(df_sample_manual[null_readme].index)
len(df_sample_manual)

179

In [11]:
df_sample_manual["readme_lang"] =  df_sample_manual["readme_snippet"].apply(detect_lang) 
df_sample_manual["desc_lang"] = df_sample_manual["description"].apply(detect_lang)

In [12]:
df_sample_manual_notenglish = df_sample_manual[(df_sample_manual["readme_lang"] != "en") & (df_sample_manual["desc_lang"] != "en")]
print("Number of repositories not in English:", len(df_sample_manual_notenglish))
df_sample_manual_notenglish

Number of repositories not in English: 4

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,...,languages,primary_language,topics,readme_snippet,category,Manual,Comment,Unnamed: 20,readme_lang,desc_lang
34,vitobrat/report_llm_agent,NaN,0,0,Python,https://github.com/vitobrat/report_llm_agent,2025,2025-08-01T06:06:36+00:00,2025,2025-07-10T06:09:19+00:00,...,"{'Python': 53181, 'Dockerfile': 936}",Python,[],Report_llm_agent Добавить файл .env в директор...,llm-based agentic system,LLM-Based agentic system,NaN,NaN,bg,nan
64,comnhuman/kt_ai_agent_document_llm,문서작성 LLM 개발 kt dacon 참여 레포지토리입니다.,0,1,Python,https://github.com/comnhuman/kt_ai_agent_docum...,2025,2025-09-01T01:55:42+00:00,2025,2025-08-21T01:37:48+00:00,...,"{'Python': 55916, 'Shell': 1340, 'Dockerfile':...",Python,[],🚀 지원사업 데이터 수집 & 사업계획서 초안 작성 Agent 중소기업 지원사업 정보...,documents about llm agents,Not English,NaN,NaN,ko,ko
120,HAM1722/agente_ejecutivo,Extractor OCR - Facturas EMCALI: sistema autom...,0,0,Python,https://github.com/HAM1722/agente_ejecutivo,2025,2025-10-19T02:55:14+00:00,2025,2025-10-13T19:44:41+00:00,...,{'Python': 94689},Python,"['energia', 'facturas', 'llm', 'ocr', 'openai'...",Extractor OCR - Facturas EMCALI README.md,other,Other,NaN,NaN,es,es
165,mjamal/SimpleAgent,Basic LLM AI Agent,0,0,Python,https://github.com/mjamal/SimpleAgent,2025,2025-11-16T05:44:25+00:00,2025,2025-11-08T22:16:22+00:00,...,{'Python': 7086},Python,[],SimpleAgent,llm-based agentic system,LLM-Based agentic system,NaN,NaN,ca,ca

In [ ]:
df_clean = df_sample.drop(df_notenglish.index)
df_clean = df_clean.drop(columns=["desc_lang", "readme_lang"])

In [13]:
df_clean_sample_manual = df_sample_manual.drop(df_sample_manual_notenglish.index)
df_clean_sample_manual = df_clean_sample_manual.drop(columns=["desc_lang", "readme_lang"])

In [15]:
print("Length of cleaned dataset:", len(df_clean_sample_manual))
df_clean_sample_manual.head(2)

Length of cleaned dataset: 175

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,...,size,license,languages,primary_language,topics,readme_snippet,category,Manual,Comment,Unnamed: 20
0,chrisjcc/llm-applied-research,Research and development framework for large l...,0,0,Python,https://github.com/chrisjcc/llm-applied-research,2025,2025-10-02T00:18:15+00:00,2025,2025-09-23T15:05:14+00:00,...,301,Apache License 2.0,"{'Python': 65791, 'Shell': 2297}",Python,[],llm-applied-research Research and development ...,other,agentic framework,It has less information in its readme,NaN
2,RoshanM24/Langgraph-with-Astra-DB---Multi-Sour...,This project demonstrates the integration of L...,1,0,Python,https://github.com/RoshanM24/Langgraph-with-As...,2025,2025-08-13T00:07:51+00:00,2025,2025-08-12T23:24:58+00:00,...,12,NaN,{'Python': 7957},Python,[],LangGraph with Astra DB — Intelligent Query Ro...,other,LLM-Based agentic system,NaN,NaN

In [16]:
df_clean_sample_manual["manual_normalized"] = df_clean_sample_manual["Manual"].apply(
    lambda x: "llm-based agentic system" if x.strip().lower() == "llm-based agentic system" else "other"
)

In [18]:
df_clean_sample_manual.tail(5)

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,...,license,languages,primary_language,topics,readme_snippet,category,Manual,Comment,Unnamed: 20,manual_normalized
194,dr-data/TheoremExplainAgent,"Official Repo for ""TheoremExplainAgent: Toward...",0,0,Python,https://github.com/dr-data/TheoremExplainAgent,2025,2025-08-17T14:10:01+00:00,2025,2025-08-17T12:32:00+00:00,...,MIT License,"{'Python': 359990, 'Jupyter Notebook': 19022}",Python,[],TheoremExplainAgent (TEA) 🍵 TheoremExplainAgen...,other,LLM-Based agentic system,NaN,NaN,llm-based agentic system
196,jchryssanthacopoulos/VLA-LLM,A virtual leasing agent using large language m...,0,0,Python,https://github.com/jchryssanthacopoulos/VLA-LLM,2023,2023-09-29T11:03:10+00:00,2023,2023-07-25T11:59:18+00:00,...,NaN,"{'Python': 129411, 'Jupyter Notebook': 39343, ...",Python,[],VLA-LLM This repository uses LangChain to crea...,llm-based agentic system,LLM-Based agentic system,NaN,NaN,llm-based agentic system
197,IBEX-TUDelft/IBEX-LLM,A first pilot project to link LLM agents as ac...,0,0,Python,https://github.com/IBEX-TUDelft/IBEX-LLM,2025,2025-03-25T18:42:30+00:00,2024,2024-02-24T12:14:01+00:00,...,MIT License,{'Python': 214365},Python,[],Project Overview This project introduces an ap...,other,LLM-Based agentic system,NaN,NaN,llm-based agentic system
198,felipemaciasventura/snowflake_nlp_agent_v2,Snowflake NLP Agent v2 - Advanced Natural Lang...,0,0,Python,https://github.com/felipemaciasventura/snowfla...,2025,2025-11-12T15:16:02+00:00,2025,2025-09-18T19:06:35+00:00,...,NaN,{'Python': 130329},Python,[],🤖 Snowflake NLP Agent v2 An intelligent web ap...,other,Other,NaN,NaN,other
199,pixeltable/pixelmemory,Pixelmemory — A multimodal memory layer for yo...,5,0,Python,https://github.com/pixeltable/pixelmemory,2025,2025-09-12T02:02:06+00:00,2025,2025-05-19T20:28:27+00:00,...,Apache License 2.0,"{'Python': 20352, 'Shell': 1804}",Python,"['ai', 'llm', 'mcp', 'memory', 'python']",Pixelmemory Pixelmemory demonstrates how to bu...,agentic framework,Other,NaN,NaN,other

In [19]:
df_clean_sample_manual = df_clean_sample_manual.drop(columns=["category"])

In [20]:
df_clean_sample_manual.head(2)

,full_name,description,stars,forks,language,url,updated_year,last_updated,created_year,created_at,...,size,license,languages,primary_language,topics,readme_snippet,Manual,Comment,Unnamed: 20,manual_normalized
0,chrisjcc/llm-applied-research,Research and development framework for large l...,0,0,Python,https://github.com/chrisjcc/llm-applied-research,2025,2025-10-02T00:18:15+00:00,2025,2025-09-23T15:05:14+00:00,...,301,Apache License 2.0,"{'Python': 65791, 'Shell': 2297}",Python,[],llm-applied-research Research and development ...,agentic framework,It has less information in its readme,NaN,other
2,RoshanM24/Langgraph-with-Astra-DB---Multi-Sour...,This project demonstrates the integration of L...,1,0,Python,https://github.com/RoshanM24/Langgraph-with-As...,2025,2025-08-13T00:07:51+00:00,2025,2025-08-12T23:24:58+00:00,...,12,NaN,{'Python': 7957},Python,[],LangGraph with Astra DB — Intelligent Query Ro...,LLM-Based agentic system,NaN,NaN,llm-based agentic system

In [21]:
df_clean_sample_manual.to_csv("data/clean_sample_agent_repos_withShortReadme_manual.csv", index=False)